[KERNEL32] proper argument info for stubs
reactos/reactos pull request #1322
Opened 2019-01-29 15:13 UTC by Getequ

App can fail when called our stub w/o args but function actually have them and app is pushing data to stack

2019-01-29 17:21 UTC, learn-more commented
What?

2019-01-29 18:21 UTC, Getequ commented
@learn-more firefox 48 is calling GetProcessDEPPolicy and failed with 8000100 exception code. Similar result was with WerSetFlags while installing .net 4.5

I built ros with guOsVersion=0x600 in spec2def (and no limit by endversion)

2019-01-30 02:58 UTC, encodedpr commented
i like it

2019-02-02 15:13 UTC, HBelusca commented on dll/win32/kernel32/kernel32.spec
> +@ stdcall -stub -version=0x600+ CreateSymbolicLinkA(str str long)
What about making a redirection to kernel32_vista then?

2019-02-02 15:31 UTC, tkreuzer commented on dll/win32/kernel32/kernel32.spec
> +@ stdcall -stub -version=0x600+ CreateSymbolicLinkA(str str long)
It depends on how we want to use this. Currently it is not used at all IIRC. Our versioning system is WIP and should eventually result in one core library with all the exports and a number of wrappers, not different full implementations or a mixture of half implementations and forwarders.

2019-02-02 18:02 UTC, Getequ commented on dll/win32/kernel32/kernel32.spec
> +@ stdcall -stub -version=0x600+ CreateSymbolicLinkA(str str long)
Oops, sorry. I don't remember how/why I did it :) fixed

2021-01-06 18:11 UTC, Getequ commented
@tkreuzer  hi, is all ok atm?)  Yes, almost 2 years passed from PR was opened but i rebased that commit onto master

2022-06-18 22:06 UTC, HBelusca requested changes

2022-06-18 22:06 UTC, HBelusca commented on dll/win32/kernel32/kernel32.spec
> +@ stdcall -stub -version=0x600+ VirtualAllocExNuma(ptr ptr long long long long)
3rd parameter is SIZE_T (and is pointer-sized); may require "ptr" instead

2022-06-18 22:06 UTC, HBelusca commented on dll/win32/kernel32/kernel32.spec
> +@ stdcall -stub -version=0x600+ Wow64GetThreadContext(ptr ptr)
```suggestion
@ stdcall -stub -version=0x600+ -arch=x86_64 Wow64GetThreadContext(ptr ptr)
```

2022-06-18 22:06 UTC, HBelusca commented on dll/win32/kernel32/kernel32.spec
> +@ stdcall -stub -version=0x600+ Wow64SetThreadContext(ptr ptr)
```suggestion
@ stdcall -stub -version=0x600+ -arch=x86_64 Wow64SetThreadContext(ptr ptr)
```

2022-06-18 22:06 UTC, HBelusca commented on dll/win32/kernel32/kernel32.spec
> +@ stdcall -stub -version=0x600+ Wow64SuspendThread(ptr)
```suggestion
@ stdcall -stub -version=0x600+ -arch=x86_64 Wow64SuspendThread(ptr)
```

2022-06-18 22:06 UTC, HBelusca commented on dll/win32/kernel32/kernel32.spec
>  @ stdcall Wow64DisableWow64FsRedirection(ptr)
All those Wow64 functions quite probably need an extra `-arch=x86_64`.
Cc @tkreuzer for confirmation.

2022-07-03 01:06 UTC, closed without merging