[NTOS:MM] Replace ASSERT by UNIMPLEMENTED_ONCE macro for unimplemented code path CORE-16478
reactos/reactos pull request #3011
Opened 2020-07-30 09:58 UTC by oleg-dubinskiy

## Purpose

Replace the `ASSERT` by `UNIMPLEMENTED_ONCE` macro for unimplemented code path in `MiRemoveMappedPtes` function of our MM.
It seems to me that asserts should not be used in unimplemented code paths, so I replaced it by the correct macro instead.
Also comment out now unused `ProtoPte` variable (and its value definition), which currently does nothing anyway, same as before.
It allows ReactOS win32k Frankenstein no longer hang (in debug builds) when using any apps which require layered window support (e. g. RocketDock 1.3.5) and also in some other cases, like when trying to use VirtualBox display integration mode.

JIRA issue: [CORE-16478](https://jira.reactos.org/browse/CORE-16478)

## Proposed changes

- Comment out `ProtoPte` declaration, same as it done for the `FirstPte` variable.
- Also comment out its value definition, which is `MiProtoPteToPte(&PteContents)`. It will be commented out until that code will not be implemented properly.
- Replace the `ASSERT(ProtoPte->u.Long == 0)` by `UNIMPLEMENTED_ONCE`.

## Result

RocketDock 1.3.5:
![RocketDock_MS_Win32SS_fixed](https://user-images.githubusercontent.com/26385117/88908449-89474a00-d262-11ea-9311-023b26787da2.gif)

VirtualBox 5.1.38 display integration mode:
![VBox_mode_after](https://user-images.githubusercontent.com/26385117/88908606-bf84c980-d262-11ea-9b81-73e4f0bd522f.png)

2020-07-30 16:58 UTC, SergeGautherie commented
1)
```
-                ASSERT(ProtoPte->u.Long == 0);
+                if (ProtoPte->u.Long != 0) UNIMPLEMENTED_ONCE;
```

2) Would `UNIMPLEMENTED` be enough or spam too much?

2020-07-30 18:18 UTC, oleg-dubinskiy commented
1. Thanks @SergeGautherie. :+1: This works for me too. So it's not required to comment out `ProtoPte` then.
2. As I see, yes, too much, to affect the performance in debug mode. 320 lines of the spam appeared after simple launching the dock, moving mouse cursor on it a few seconds and exiting. So I think `UNIMPLEMENTED_ONCE` will be better in this case. With the last one, there is no spam at all.

2020-09-09 10:12 UTC, tkreuzer requested changes
ASSERTs exist for a reason. If it gets triggered, it usually means there is something seriously broken. And this is kernel code, so silencing the issue is a really bad idea. Please investigate where the problem is: What are the contents of the PTE when it hits? Use ```!pte <pte address>``` in WinDbg.

2021-04-26 09:04 UTC, GeoB99 commented
I agree with Timo regarding this. Dismissing the assert is not only the bad way to fix this problem but is also a hack. Judging by the comment in the code I highly assume that specific part in `MiRemoveMappedPtes` has to be implemented.

Considering this is a stale PR I'm going to close this. Feel free to come back working on this in a proper way, let me know when you're ready as I'll open the PR back.

2021-04-26 09:04 UTC, closed without merging