[BASE] Improve Spanish translation
reactos/reactos pull request #3088
Opened 2020-08-22 16:54 UTC by jeffbox12

## Purpose

General translation in Spanish.

## Changes

Missing translations and spell corrections.

- Missing translations from applications: `mspaint`, `notepad` & `rapps`

- Missing translations and improvements on `osk`

- Missing translations on cmd help descriptions: `assoc`, `CTTY`, `replace`, `prompt `& `set`

- Missing translation on system: `subst`, `userinit` & `winlogon`

2020-08-23 20:44 UTC, jeffbox12 commented on base/applications/osk/lang/es-ES.rc
>      DEFPUSHBUTTON "OK", IDOK, 193, 76, 50, 14
> El mensaje que aparece al abrir Teclado en Pantalla, el botón OK parece no tener un string para traducción.
> ![imagen](https://user-images.githubusercontent.com/69764719/90981433-43c82500-e561-11ea-9220-7ae386f61820.png)

Resulta que si que tenia string para traducir. Fallo mio.

2020-08-23 21:10 UTC, binarymaster commented on base/system/userinit/lang/es-ES.rc
> +    IDS_INSTALLER_FAIL "Userinit no pudo iniciar el instalador."
These sentences end with an exclamation sign in other translations:
- https://git.reactos.org/?p=reactos.git&a=search&h=master&st=grep&s=IDS_SHELL_FAIL
- https://git.reactos.org/?p=reactos.git&a=search&h=master&st=grep&s=IDS_INSTALLER_FAIL

2020-08-25 09:26 UTC, julenuri commented
Ready to merge

2020-08-25 09:29 UTC, binarymaster requested changes
Hello,
Thanks for your interest in ReactOS!
We ask our contributors [to use their full name when committing](https://github.com/reactos/reactos/blob/master/CONTRIBUTING.md#rules-and-recommendations).
[Please amend your commit with your full name](https://stackoverflow.com/a/3042512), and update this PR.

To change this for future PR's, you can update it for globally (for the system):
```
git config --global user.name "Catalin Gabriel Draghita"
git config --global user.email catalin.draghita@hotmail.es
```

Or just for the current repository:
```
git config user.name "Catalin Gabriel Draghita"
git config user.email catalin.draghita@hotmail.es
```

Also please update your name in [GitHub profile settings](https://github.com/settings/profile).

Regards,

2020-08-25 15:12 UTC, merged