[NTOS:PS] Initial implementation of VDM Ps support
reactos/reactos pull request #3103
Opened 2020-08-27 12:42 UTC by Fraizeraust

- Create the "psvdm.c" file and implement PspVdmInitialize()
- Use PspVdmInitialize in PspInitPhase0
- Move the PspDeleteVdmObjects() code into the new file and implement the rest parts of it

Further documentation details of `PspDeleteVdmObjects()` and `PspVdmInitialize()` can be found in [this page](https://fraizeraust.github.io/pages/doc/ntoskrnl/ps/vdm.html).

2020-08-27 16:58 UTC, HBelusca commented
Is this (private) function going to be used somewhere else right now? Maybe you could just continue working on the VDM kernel interface before marking this PR as non-draft?

2020-08-29 10:08 UTC, Fraizeraust commented
As I said on Mattermost, in order to have a fully complete VDM kernel interface it'd require a huge amount of work which I am comfortable providing separate PRs with code in a gradual manner. In addition to what I've said, I must first and foremost publish documentation details of VDM/Ps VDM related routines before I start writing code.

To answer your question -- no, I'm not going to make this PR as draft. Furthermore both `PspVdmInitialize` and `PspDeleteVdmObjects` are used explicitly in code.

2020-09-09 08:24 UTC, tkreuzer requested changes

2020-09-09 08:24 UTC, tkreuzer commented on ntoskrnl/ps/i386/psvdm.c
> +    DPRINT1("PspDeleteVdmObjects(): Successfully deleted the VDM objects!\n");
Why do you delete the global resource on per-process cleanup? And why return the quota for the process here? Non of this seems to make any sense.

2020-09-09 08:49 UTC, ThFabba reviewed
Any particular reason you're working on this? Our ntvdm doesn't rely on V86 mode, and there are no plans to change that AFAIK. So this might end up being dead code.

2020-09-09 08:49 UTC, ThFabba commented on ntoskrnl/ps/i386/psvdm.c
> +    PsReturnProcessNonPagedPoolQuota(Process->VdmObjects, sizeof(Process->VdmObjects));
The first argument should be the `Process` to charge, not VdmObjects.
For the second argument, `VdmObjects` is a pointer so you'll only get `sizeof(PVOID)` here. You'll need the actual struct size.

2020-09-09 08:49 UTC, ThFabba commented on ntoskrnl/ps/psmgr.c
> +    PspVdmInitialize();
If the return value doesn't get checked, why does the function return it?

2020-09-25 11:40 UTC, closed without merging