Update he-IL.rc
reactos/reactos pull request #3121
Opened 2020-09-01 23:34 UTC by omeritzics

2020-09-01 23:41 UTC, HBelusca commented
Cc @reactos/lang-hebrew

2020-09-01 23:47 UTC, omeritzics commented
> Cc @reactos/lang-hebrew

Hello, I think @reactos/lang-hebrew isn't active because the page was not found.

2020-09-02 00:25 UTC, HBelusca commented
@omeritzics : there are two people in the list who recently contributed: @peterooch and @shytzedaka .

2020-09-02 00:54 UTC, omeritzics commented
Is there another way to reach the group list?

2020-09-02 11:10 UTC, binarymaster commented
> the page was not found

@omeritzics this page is available only for team members, that's why you get 404.

2020-09-08 20:06 UTC, peterooch requested changes
Some nitpicks, everything else is alright.

2020-09-08 20:06 UTC, peterooch commented on dll/cpl/input/lang/he-IL.rc
> +    IDS_LEFT_ALT_SHIFT "מקש Alt השמאלי+Shift"
I think "שמאלי" would be better than "השמאלי"

2020-09-08 20:06 UTC, peterooch commented on dll/cpl/input/lang/he-IL.rc
> +    IDS_REBOOT_NOW, "לאתחל כעת?"
I think "?להפעיל מחדש כעת" or something like that would be more clearer.

2020-09-08 20:30 UTC, omeritzics commented
OK, changed it.

2020-09-08 21:01 UTC, merged

2020-09-08 21:02 UTC, HBelusca commented
thanks!