[RICHED20_WINETEST] txtsrv.c: Workaround for 'thiscall' handling
reactos/reactos pull request #3124
Opened 2020-09-03 01:51 UTC by SergeGautherie

Pseudo-revert a part of 76cf09c.

JIRA issue: [ROSTESTS-355](https://jira.reactos.org/browse/ROSTESTS-355)

NB:
* GCC: 4 failures, instead of crash. Should fix test runs!
* MSVC: still crash. I did not check whether it was already broken before the Wine 4.18 update...

2020-09-05 19:02 UTC, JoachimHenze requested changes
I do request changes (of unknown nature), see
https://jira.reactos.org/browse/ROSTESTS-355?focusedCommentId=125110&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-125110

2020-09-07 20:55 UTC, SergeGautherie commented
> request changes (of unknown nature)

With regard to discussion on Jira, I still think this PR is good (as self-contained) as it is.

2020-10-23 13:03 UTC, Extravert-ir commented
Closed due to inactivity

2020-10-23 13:03 UTC, closed without merging

2020-10-24 00:02 UTC, SergeGautherie commented
> Closed due to inactivity

Which inactivity?

2020-10-24 01:08 UTC, Extravert-ir commented
The patch introduces a test crash, test crash was not fixed

2020-10-24 03:39 UTC, SergeGautherie commented
> The patch introduces a test crash, test crash was not fixed

Hum, I disagree with that point of view, as I already replied on Jira.

2021-10-10 18:13 UTC, SergeGautherie commented
Eventually superseded by 5a9535e694b6baaa4b028523263a39357d6d589b and e30b0a356db25fd982c14717a6363bc4032abcb6.