[SHELL] Localization of "System Folder" in My Computer types
reactos/reactos pull request #3168
Opened 2020-09-12 17:56 UTC by KyleKatarn31

## Purpose

- "System folder" in My Computer types is not localized (code indicates "/* FIXME: translate */")

![image](https://user-images.githubusercontent.com/24843587/93001820-01777f80-f532-11ea-8520-de3615844d2e.png)

## Proposed changes

- Localize this string

![image](https://user-images.githubusercontent.com/24843587/93001810-f886ae00-f531-11ea-8943-62e42bb5d04a.png)

2020-09-12 18:14 UTC, HBelusca commented on dll/win32/shell32/folders/CRegFolder.cpp
> +            return SHSetStrRet(&psd->str, strSysFolder);
```suggestion
            return SHSetStrRet(&psd->str, IDS_SYSTEMFOLDER);
```

2020-09-12 18:56 UTC, KyleKatarn31 commented on dll/win32/shell32/folders/CRegFolder.cpp
> +            return SHSetStrRet(&psd->str, strSysFolder);
Done !

2020-09-12 19:10 UTC, Saibamen requested changes
Polish translation

2020-09-12 19:10 UTC, Saibamen commented on dll/win32/shell32/lang/pl-PL.rc
> +    IDS_SYSTEMFOLDER "System Folder"
```suggestion
    IDS_SYSTEMFOLDER "Folder systemowy"
```

2020-09-13 08:20 UTC, JoseSanchezz commented on dll/win32/shell32/lang/ru-RU.rc
> +    IDS_SYSTEMFOLDER "System Folder"
```suggestion
    IDS_SYSTEMFOLDER "Системная папка"
```

2020-09-13 09:42 UTC, KyleKatarn31 commented
Thanks @JoseSanchezz  and @Saibamen for your contributions !

2020-09-13 12:26 UTC, Saibamen commented
BTW How to "add"/show these System Folders in `My Computer` view in Windows XP? By default I see only drivers.

I am asking, because I'm not sure if polish translation for this string is `Folder` (ang. Folder) or `Katalog` (ang. Catalog) and I need to check this somehow. Plus after this I will be able to see polish translation for `Comments` column (https://github.com/reactos/reactos/pull/3167 which was merged in https://github.com/reactos/reactos/commit/e358d1d2197906669e9d20fbba55d2383a0bfe70).

2020-09-13 12:34 UTC, learn-more commented
> BTW How to "add"/show these System Folders in `My Computer` view in Windows XP? By default I see only drivers.
> 
> I am asking, because I'm not sure if polish translation for this string is `Folder` (ang. Folder) or `Katalog` (ang. Catalog) and I need to check this somehow. Plus after this I will be able to see polish translation for `Comments` column (#3167 which was merged in [e358d1d](https://github.com/reactos/reactos/commit/e358d1d2197906669e9d20fbba55d2383a0bfe70)).

Install those shell extensions in Windows xp.
They are specific to ReactOS

2020-09-13 21:15 UTC, HBelusca approved these changes

2020-09-13 21:16 UTC, merged