[WIN32K:ENG] EngInitializeSafeSemaphore(): Do not busy wait
reactos/reactos pull request #3201
Opened 2020-09-17 11:19 UTC by SergeGautherie

2020-09-17 12:16 UTC, learn-more commented
Why?
What does this fix?

2020-09-17 12:19 UTC, katahiromz reviewed
Initialization timing of `Interval` can be moved.

2020-09-17 14:40 UTC, SergeGautherie commented
> Why? What does this fix?

Why not? No fix, minor improvement.

> can be moved

Right. Moved.

2020-09-17 14:54 UTC, katahiromz reviewed
Okay.

2020-09-19 19:24 UTC, learn-more requested changes
> > Why? What does this fix?
> 
> Why not? No fix, minor improvement.
> 

That is subjective.
Without a valid reason of changing stuff like this, it makes no sense to change random stuff to your own liking.

2020-09-20 16:52 UTC, SergeGautherie commented
> subjective

Well, I don't understand what is subjective about busy wait being unwanted...
Similar (goal) to
https://git.reactos.org/?p=reactos.git&a=search&h=HEAD&st=commit&s=busy+wait
for example.

2020-09-20 17:52 UTC, tkreuzer requested changes

2020-09-20 17:52 UTC, tkreuzer commented on win32ss/gdi/eng/semaphor.c
> +            KeDelayExecutionThread(KernelMode, FALSE, &Interval);
- [ ] Use ZwYieldExecution()

2020-09-21 09:26 UTC, SergeGautherie commented on win32ss/gdi/eng/semaphor.c
> +            KeDelayExecutionThread(KernelMode, FALSE, &Interval);
Thanks for the reminder. Done.

2020-09-26 14:42 UTC, tkreuzer approved these changes

2022-05-08 19:11 UTC, GeoB99 commented
You should provide some explanation on what it has exactly improved since you're the author of this PR and henceforth of your code. We cannot simply take a guess or playing mind games on trying to understand your intention of this patch,

When you come back with a proper description of your patch, I will open the PR back.

2022-05-08 19:11 UTC, closed without merging