[REACTOS] spec: Fix Nt*Information*() and *Terminate*() parameter types
reactos/reactos pull request #3217
Opened 2020-09-21 11:31 UTC by SergeGautherie

2020-11-03 09:47 UTC, tkreuzer requested changes

2020-11-03 09:47 UTC, tkreuzer commented on dll/ntdll/def/ntdll.spec
> +@ stdcall NtQueryInformationAtom(ptr long ptr long ptr)
This is wrong, RTL_ATOM is a USHORT.

2020-11-04 10:31 UTC, SergeGautherie commented on dll/ntdll/def/ntdll.spec
> +@ stdcall NtQueryInformationAtom(ptr long ptr long ptr)
Indeed.
Fixed, plus another case.

2021-05-01 18:10 UTC, GeoB99 approved these changes

2021-05-01 19:11 UTC, merged