[NTOS:KE] KiIdleLoop(): Add DECLSPEC_NORETURN to it and its callers
reactos/reactos pull request #3268
Opened 2020-10-05 19:33 UTC by SergeGautherie

## Purpose

Be explicit about code flow.

## Proposed changes

Add DECLSPEC_NORETURN, Remove FASTCALL.

2020-11-01 10:55 UTC, tkreuzer approved these changes

2021-03-02 18:52 UTC, HBelusca commented
@SergeGautherie Please fix the conflicts.

2021-03-03 09:55 UTC, SergeGautherie commented
Rebased.

2021-03-03 19:31 UTC, Extravert-ir requested changes

2021-03-03 19:31 UTC, Extravert-ir commented on ntoskrnl/include/internal/ke.h
> +// TODO: Add DECLSPEC_NORETURN, after checking it applies everywhere.
Please, finish the work

2021-03-04 04:21 UTC, SergeGautherie commented on ntoskrnl/include/internal/ke.h
> +// TODO: Add DECLSPEC_NORETURN, after checking it applies everywhere.
Finished.

2021-03-04 13:23 UTC, Extravert-ir commented
I don't like powerpc changes, just remove them

2021-03-04 20:38 UTC, SergeGautherie commented
> powerpc changes

Removed.

2021-03-04 21:43 UTC, Extravert-ir approved these changes

2021-03-04 21:43 UTC, merged