Update COpenWithMenu.cpp
reactos/reactos pull request #3449
Opened 2021-02-05 18:46 UTC by siakc

## Purpose

Fixing the bug where open with menu where OpenWithMenu does not handle handler's path when there are spaces in the path string.

JIRA issue: [CORE-XXXX](https://jira.reactos.org/browse/CORE-XXXX)

## Proposed changes

- Adds quote marks around %1 when recording the registry entry for file handler.

2021-02-05 18:50 UTC, binarymaster requested changes
Hello,
Thanks for your interest in ReactOS!
We ask our contributors [to use their full name when committing](https://github.com/reactos/reactos/blob/master/CONTRIBUTING.md#rules-and-recommendations).
[Please amend your commit with your full name](https://stackoverflow.com/a/3042512), and update this PR.

To change this for future PR's, you can update it for globally (for the system):
```
git config --global user.name "Your Name"
git config --global user.email you@example.com
```

Or just for the current repository:
```
git config user.name "Your Name"
git config user.email you@example.com
```

Also please update your name in [GitHub profile settings](https://github.com/settings/profile).

Regards,

2021-02-06 13:21 UTC, learn-more approved these changes

2021-02-06 13:29 UTC, HBelusca approved these changes

2021-02-06 13:33 UTC, binarymaster approved these changes

2021-02-06 13:35 UTC, merged

2021-02-06 13:35 UTC, HBelusca commented
Thanks for your patch!

2021-02-06 13:44 UTC, siakc commented
Thank you. Sorry for not following commit comment style in the first place.