[tasklist] Polish translation (pl-PL)
reactos/reactos pull request #3484
Opened 2021-02-24 11:06 UTC by pithwz

## Proposed changes
Translate strings from **ENGLISH** to **POLISH**

2021-02-24 11:24 UTC, Saibamen requested changes
Please replace strings instead of duplicating them

2021-02-24 12:59 UTC, pithwz commented
> 
> 
> Please replace strings instead of duplicating them

Add suggestions & i apply. Thanks

2021-02-24 13:10 UTC, Saibamen requested changes
I cannot add comments on lines 9-12 (new: 13-16)

Please commit changes to your branch `patch-47`

2021-02-24 13:10 UTC, Saibamen commented on base/applications/cmdutils/tasklist/lang/pl-PL.rc
> +    IDS_USAGE, "Użycie: TASKLIST [/?] [/NH]\n"
```suggestion
    IDS_USAGE, "Użycie: TASKLIST [/?] [/NH]\n"
```

2021-02-24 13:10 UTC, Saibamen commented on base/applications/cmdutils/tasklist/lang/pl-PL.rc
> +    IDS_HEADER_MEMUSAGE, "Użycie pam."
```suggestion
    IDS_HEADER_SESSION, "Numer sesji"
    IDS_HEADER_MEMUSAGE, "Użycie pam."
```

2021-02-24 13:14 UTC, Saibamen commented on base/applications/cmdutils/tasklist/lang/pl-PL.rc
> +    IDS_HEADER_MEMUSAGE, "Użycie pam."
Also please build ROS with your changes and check if `Numer sesji` is not too long.
Alternative: `Nr sesji`

2021-03-02 18:09 UTC, HBelusca requested changes

2021-03-02 18:09 UTC, HBelusca commented on base/applications/cmdutils/tasklist/lang/pl-PL.rc
> +Opis:\
Can you remove all the old english strings please? Thanks.

2021-03-03 06:59 UTC, closed without merging

2021-03-03 06:59 UTC, pithwz commented
.