[CMAKE] target_compile_definitions() calls: Remove (now) useless '-D'
reactos/reactos pull request #3490
Opened 2021-02-27 02:12 UTC by SergeGautherie

Documented as automatically removed, since CMake 3.12.4 at least.

https://cmake.org/cmake/help/v3.12/command/target_compile_definitions.html

2021-03-01 11:01 UTC, encodedpr approved these changes

2021-03-02 18:25 UTC, HBelusca commented on sdk/lib/rossym/CMakeLists.txt
> +target_compile_definitions(rossym INTERFACE "__ROS_ROSSYM__")
Maybe the quotes are not needed too.

2021-03-02 18:25 UTC, HBelusca approved these changes

2021-03-02 18:28 UTC, zefklop requested changes
Please remove the extra quotes and this is good to go.

2021-03-02 18:58 UTC, HBelusca commented on sdk/lib/rossym/CMakeLists.txt
> +target_compile_definitions(rossym INTERFACE "__ROS_ROSSYM__")
```suggestion
target_compile_definitions(rossym INTERFACE __ROS_ROSSYM__)
```

2021-03-03 00:36 UTC, SergeGautherie commented on sdk/lib/rossym/CMakeLists.txt
> +target_compile_definitions(rossym INTERFACE "__ROS_ROSSYM__")
Done.

2021-03-03 00:38 UTC, SergeGautherie commented on sdk/lib/rossym/CMakeLists.txt
> +target_compile_definitions(rossym INTERFACE "__ROS_ROSSYM__")
Also removed a couple double quotes.

2021-03-03 03:16 UTC, merged