[fc] Polish [pl-PL] translation
reactos/reactos pull request #3629
Opened 2021-04-26 08:22 UTC by pithwz

fc cmd tool, "POLISH pl-pl" translation

## Purpose

_Do a quick recap of your work here._

JIRA issue: [CORE-XXXX](https://jira.reactos.org/browse/CORE-XXXX)

## Proposed changes

_Describe what you propose to change/add/fix with this pull request._

- 
- 

## TODO

_Use a TODO when your pull request is Work in Progress._

- [ ] 
- [ ]

2021-04-26 08:55 UTC, GeoB99 commented
Cc @reactos/lang-polish

2021-04-26 10:57 UTC, katahiromz commented
`IDS_RESYNCH_FAILED` needs a newline added. I will fix them later.

2021-04-26 11:25 UTC, binarymaster commented on base/applications/cmdutils/fc/lang/pl-PL.rc
> +*/
I'd say adding these headers is not necessary, because you can see all contributors with Git history and Git blame.

2021-04-26 13:33 UTC, Saibamen requested changes

2021-04-26 13:33 UTC, Saibamen commented on base/applications/cmdutils/fc/lang/pl-PL.rc
> +  /N         Przy porównaniu ASCII Wyświetla numery wierszy .\n\
```suggestion
  /N         Przy porównaniu ASCII wyświetla numery wierszy .\n\
```

2021-04-26 13:33 UTC, Saibamen commented on base/applications/cmdutils/fc/lang/pl-PL.rc
> +  /W         Kompresuje do porównania białe miejsca (tabulatory i spacje).\n\
```suggestion
  /W         Kompresuje do porównania białe znaki (tabulatory i spacje).\n\
```

2021-04-26 13:33 UTC, Saibamen commented on base/applications/cmdutils/fc/lang/pl-PL.rc
> +             po wystąpieniu niezgodności (domyślny: 2).\n\
```suggestion
             po wystąpieniu niezgodności (domyślnie: 2).\n\
```

2021-04-26 13:33 UTC, Saibamen commented on base/applications/cmdutils/fc/lang/pl-PL.rc
> +    IDS_RESYNCH_FAILED "Ponowna synchronizacja nie powiódła się. Pliki za bardzo się różnią. ."
```suggestion
    IDS_RESYNCH_FAILED "Ponowna synchronizacja nie powiódła się. Pliki za bardzo się różnią."
```

2021-04-26 15:12 UTC, archeYR requested changes

2021-04-26 15:12 UTC, archeYR commented on base/applications/cmdutils/fc/lang/pl-PL.rc
>      IDS_CANT_USE_WILDCARD "Wildcard ('*' and '?') are not supported yet\n"
```suggestion
    IDS_CANT_USE_WILDCARD "Symbole wieloznaczne ('*' i '?') nie są jeszcze obsługiwane\n"
```

2021-04-26 15:12 UTC, archeYR commented on base/applications/cmdutils/fc/lang/pl-PL.rc
> +  /A         Wyświetla tylko pierwsze i ostatni wiersz każdego zestawu różnic.\n\
```suggestion
  /A         Wyświetla tylko pierwszy i ostatni wiersz każdego zestawu różnic.\n\
```

2021-04-26 15:12 UTC, archeYR commented on base/applications/cmdutils/fc/lang/pl-PL.rc
> +    IDS_RESYNCH_FAILED "Ponowna synchronizacja nie powiódła się. Pliki za bardzo się różnią."
```suggestion
    IDS_RESYNCH_FAILED "Ponowna synchronizacja nie powiodła się. Pliki za bardzo się różnią."
```

2021-04-26 18:45 UTC, Saibamen approved these changes
Translation OK

2021-04-26 19:12 UTC, ivall approved these changes

2021-04-27 08:11 UTC, binarymaster commented on base/applications/cmdutils/fc/lang/pl-PL.rc
> +
```suggestion
/*
 * PROJECT:     ReactOS FC Command
 * LICENSE:     GPL-2.0-or-later (https://spdx.org/licenses/GPL-2.0-or-later)
 * PURPOSE:     Polish language translation
 * TRANSLATORS: Copyright 2021 Piotr Hetnarowicz <piotrhwz@gmail.com>
 */

```

2021-04-27 09:20 UTC, merged