[cdrom_new.inf] pl-PL translation
reactos/reactos pull request #3659
Opened 2021-05-12 05:20 UTC by pithwz

Added Polish pl-PL translation

2021-05-12 11:28 UTC, binarymaster commented on drivers/storage/class/cdrom_new/cdrom.inf
> +Mitsumi_Generic_FriendlyName = "Stacja dysków CD-ROM Mitsumi"
Translation for `ISO_Generic_FriendlyName` is missing.

2021-05-18 07:55 UTC, archeYR requested changes

2021-05-18 07:55 UTC, archeYR commented on drivers/storage/class/cdrom_new/cdrom.inf
> +
```suggestion
ISO_Generic_FriendlyName = "Wirtualna stacja dysków DVD-ROM firmy Microsoft"

```

2021-05-18 08:59 UTC, archeYR approved these changes

2021-05-18 11:56 UTC, merged