[NTOS:MM] Properly set PTE dirty bit after serving an access fault.
reactos/reactos pull request #3748
Opened 2021-06-16 11:00 UTC by zefklop

## Purpose

Set the dirty bit. The CPU is actually writing to the page, but it doesn't set the bit.

JIRA issue: [CORE-17595](https://jira.reactos.org/browse/CORE-17595)

2021-06-16 11:32 UTC, HBelusca approved these changes

2021-06-16 11:32 UTC, HBelusca commented on ntoskrnl/mm/i386/page.c
>      // We shouldnl't set dirty bit on non-mapped adresses
```suggestion
    // We shouldn't set dirty bit on non-mapped addresses
```

2021-06-16 14:35 UTC, JoachimHenze requested changes
I tested PR3748 on top of 0.4.15-dev-2707-gd042f51, but it did not fix the bug for me: Again I got the strong name bug on first try.
I can not judge whether the patch is an improvement or not, but it definitely does not fix CORE-17595 and therefore at least the commit comment would need adjustment.
Committing makes only sense in case it would fix "something else".

2021-06-26 11:44 UTC, JoachimHenze commented
No sorry, this does still not work. I got the strong-name-bug CORE-17595 again upon first try. It does not fix the ticket. I attached the fresh logs to the ticket
https://jira.reactos.org/browse/CORE-17595?focusedCommentId=128626&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-128626

2021-07-05 08:36 UTC, closed without merging

2021-07-05 08:36 UTC, zefklop commented
Closing this one, reopening with a propoer description