[WIN32K] Revert NtGdiStretchDIBitsInternal to Previous Logic (2011-03-09)
reactos/reactos pull request #3757
Opened 2021-06-20 00:17 UTC by Doug-Lyons

## Revert to old logic for NtGdiStretchDIBitsInternal to fix SIMS graphics.

_Reviewed full history of changes to this function and merged significant changes into reverted logic._

JIRA issue: [CORE-16236](https://jira.reactos.org/browse/CORE-16236)

## Fix SIMS graphics by reverting problematic function change.

Graphics After Patch:

![Sims_Complete_01](https://user-images.githubusercontent.com/32620577/122658416-939c5c00-d132-11eb-9dc9-1a9df32bd8be.png)

![Sims_Complete_02](https://user-images.githubusercontent.com/32620577/122658419-9c8d2d80-d132-11eb-8e4b-6038eaa894a6.png)

![Sims_Complete_03](https://user-images.githubusercontent.com/32620577/122658421-a31ba500-d132-11eb-820c-a3f15cc0d088.png)

2021-06-20 00:24 UTC, HBelusca commented
@tkreuzer @zefklop , could you have a look at this PR? This function has been improved in the past by you both, and here it would appear most of your changes get reverted.

2021-06-20 00:45 UTC, Doug-Lyons commented
I did a complete testbot run of these changes previously before the last revision to dibobj.c and here are their results

KVM:  https://reactos.org/testman/compare.php?ids=77396,77417, LGTM
 VBox: https://reactos.org/testman/compare.php?ids=77397,77418, LGTM

We now have about 100 fewer failures in gdi32:dib.

2021-06-21 10:47 UTC, tkreuzer requested changes
The resulting code doesn't resemble what we had pre 2011-03-09. E.g. it's not copying user mode data safely, which the old version did.
- [ ] Copy user mode data to KM buffer
- [ ] Make sure it works with RLE compressed bitmaps
- [ ] Investigate / fix the new failures in gdi32:bitmap

2021-06-22 06:01 UTC, Doug-Lyons commented
> The resulting code doesn't resemble what we had pre 2011-03-09. E.g. it's not copying user mode data safely, which the old version did.
> 
> * [ ]  Copy user mode data to KM buffer
> * [ ]  Make sure it works with RLE compressed bitmaps
> * [ ]  Investigate / fix the new failures in gdi32:bitmap

I have updated the PR to fix the "Copy use mode date to KM buffer"
A graphic showing an RLE test is now shown here in the header.

Here are the most recent TestBot results:
VBox: https://reactos.org/testman/compare.php?ids=77832,77837 LGTM
 KVM:  https://reactos.org/testman/compare.php?ids=77833,77836 LGTM

Over 100 fewer failures in gdi32:dib

I am working on a very UGLY patch that should lower the gdi32:bitmap failures by five (5).
Maybe I can post it and its results to the CORE-16236 soon.

Can you offer any suggestions on handling the final item of your check list? Thanks, Doug Lyons

2021-06-23 03:53 UTC, Doug-Lyons commented
Testbot Results of PR#3757

CORE-16236 JID59722 dibobj_NtGdiStretchDIBitsInternal_01.patch on top of 13073e1

VBox: https://reactos.org/testman/compare.php?ids=77832,77846 LGTM
 KVM: https://reactos.org/testman/compare.php?ids=77833,77847 LGTM

Over 100 fewer failures in gdi32:dib
 Four (4) fewer failures in gdi32:bitmap

2021-06-24 05:15 UTC, Doug-Lyons commented
> 
> * [x]  Copy user mode data to KM buffer
> * [x]  Make sure it works with RLE compressed bitmaps
> * [x ]  Investigate / fix the new failures in gdi32:bitmap

Ready for comments. Thanks.

2021-06-29 21:49 UTC, Doug-Lyons commented
Closed and replaced by https://github.com/reactos/reactos/pull/3774

2021-06-29 21:49 UTC, closed without merging