[GITHUB] Remove VS 2015 build from the CI
reactos/reactos pull request #3872
Opened 2021-08-01 16:48 UTC by Extravert-ir

Let's establish a set of rules regarding compiler support in ReactOS to avoid holywars in future.

## Proposed rules
- We officially support __no more than two versions__ of each compiler.
- The term "officially supported" means there is a job on one of our CI systems (either GitHub Actions or BuildBot), and every developer has to check changes against those compilers and/or fix breakages ASAP if they happen.
- Two versions usually mean having one "stable" version which is not changed often and one "latest" version. For example, VS 2017 and VS 2019 (or that will likely be VS 2022 soon) or RosBE-provided GCC 8.4.0 and the current latest release (GCC 11.1.0).
- "stable" compiler should be upgraded once in 2-3 years, or by a demand (for example, when it can't support our code anymore without too many hacks)
- Contributors can maintain support for other compilers and toolchains, but the topic of merging such changes should be treated carefully. First of all, it shouldn't require too many changes in our code base, especially for 3rd party modules.

So according to this set of rules, I suggest to leave these compilers as "officially supported":
- GCC 8.4.0 for RosBE (aka "gcc-stable")
- MSVC/VS 2019 (aka "msvc-latest")
- MSVC/VS 2017 (aka "msvc-stable")
- LLVM/Clang 12 (with MSVC and GNU-like APIs) (aka "clang-latest")

Clang does not have a "stable" version yet, as the work about its support is still in progress.

## Reasoning
- Supporting each compiler requires an extra effort from every developer contributing to the project. Considering the size of our team, I think we may spend that time on something more useful. 4 versions is already a lot.
- The more a compiler gets old, the more work is required to update the codebase for a newer version. Remember our GCC 4.7.2 -> 8.4.0 transition, it took about 1.5 years in total to make it stable.
- Old compilers don't support newer language features and static analysis hints. This is especially relevant considering our plan to incorporate libcxx (LLVM's C++ standard library) into our project.

Additions and remarks are welcome.

2021-08-04 15:12 UTC, SergeGautherie commented
Setting an explicit policy is fine.
But it still seems odd to me that such a PR/discussion looks to come out of nowhere. It reminds me a lot of #2658...

2021-08-04 15:36 UTC, SergeGautherie commented
Official: why remove 2015 support already, especially when current 2019 is broken?
GitHub: why not simply mark 14.0 build as non-blocking for the time being, as still/contributor maintained, if need be?

2021-08-04 15:51 UTC, SergeGautherie commented
Why not add 'GCC 11.1.0 (aka "gcc-latest")' to the CI?

2021-08-04 16:04 UTC, Extravert-ir commented
> why remove 2015 support already, especially when current 2019 is broken?
Because there is 2017 which works perfectly fine, and it doesn't make sense to support two compilers with the same set of features.

> why not simply mark 14.0 build as deprecated/non-blocking for the time being, as still/contributor maintained, if need be?

Contributors may support whatever they want, but that shouldn't put an obligation on code devs. That's why I want to leave only "officially supported" toolchains in the CI

> Why not add 'GCC 11.1.0 (aka "gcc-latest")' to the CI?
That fits the scheme I described, so if there will be a PR which sets up such a build and makes it green, it will be accepted

2021-08-04 16:30 UTC, SergeGautherie commented
> > why not simply mark 14.0 build as deprecated/non-blocking for the time being, as still/contributor maintained, if need be?
> 
> Contributors may support whatever they want, but that shouldn't put an obligation on code devs. That's why I want to leave only "officially supported" toolchains in the CI

I understand your goal, but why link the two things?
Move 2015 from officially-supported to contributor-supported (not unsupported), mark 14.0 jobs as not failing the whole run, until 2015 can't actually handle future ROS code.
That should be enough to remove dev obligation, while still helping 2015 contributors.

2021-11-20 13:07 UTC, SergeGautherie commented
> VS 2022 soon

`windows-2022` is now official and seems to work right (for i386 at least).

2024-05-12 18:19 UTC, DarkFire01 approved these changes

2024-05-12 18:19 UTC, JoachimHenze requested changes
NO!

2024-05-12 18:36 UTC, DarkFire01 commented
Leave it open, I’m taking it over.

2024-05-12 19:20 UTC, cbialorucki approved these changes

2024-05-12 20:53 UTC, DarkFire01 commented
Anyway; All the drama aside let's discuss the REAL reason I'm for this.

1) The WINESYNC movement has been going strong but we're currently running into some usages of C11,
According to the Microsoft documentation 
> C11 Compiler support for C11 and C17 requires Visual Studio 2019 version 16.8 or higher.
https://learn.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-170

MSVC 2015 is a no go, although; It seems 2017 manages currently. 
This discussion will need to happen once more when we run into an issue with it, for now. we're just discussing Vs2015

2) https://github.com/dotnet/wpf/tree/main/src/Microsoft.DotNet.Wpf/src/WpfGfx
This can be used as a replacement for milcore.dll from Vista RTM, the next version we're targeting therefore for implementing WDDM this is a requirement.

This entire code base uses a bunch of C/C++ that isn't supported under VS2015.

3) ucrtbase.dll
The new ucrt requires some feature vs2015 doesn't support as well.

4) https://github.com/microsoft/SymCrypt
Symcrypt is the next step to our bcrypt.dll. it's what windows 10 currently uses, and it's under MIT as well.

ALSO it needs features vs2015 doesn't support.

These tasks bring too much benefit, and in general we've outgrown vs2015


For these reasons and more, we're dropping vs2015. 
This is more then just a troll, it's a logical choice. 

This PR will be merged in a few days :) or when another approval has been obtained.

2024-05-12 21:02 UTC, SigmaTel71 commented
> 3\. The new ucrt requires some feature vs2015 doesn't support as well.

Wait, didn't VS2015 *introduce* Universal CRT? Or do you mean that UCRT in VS2017 is more feature-rich than VS2015 one?
<details>

![image](https://github.com/reactos/reactos/assets/17989678/32e84e4f-a999-450f-8a17-ee97a2db2f64)
</details>

2024-05-12 21:04 UTC, DarkFire01 commented
> > 3. The new ucrt requires some feature vs2015 doesn't support as well.
> 
> Wait, didn't VS2015 _introduce_ Universal CRT? Or do you mean that UCRT in VS2017 is more feature-rich than VS2015 one?
> 
> ![image](https://private-user-images.githubusercontent.com/17989678/329880106-32e84e4f-a999-450f-8a17-ee97a2db2f64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NDgwODEsIm5iZiI6MTcxNTU0Nzc4MSwicGF0aCI6Ii8xNzk4OTY3OC8zMjk4ODAxMDYtMzJlODRlNGYtYTk5OS00NTBmLThhMTctZWU5N2EyZGIyZjY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDIxMDMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMDVmMDRiYWViY2Y4ZTBjYTAwZmM2OTEzNjJlYTEwNDNmYjZiN2JiYmUzYTZjNGRjNTY1ZDdjMWI0YWI0OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9WCPp3VAuRvCwq2WlnW4MyasIZDNp_BUuCjOeZ79jA8)

Nah we're talking about a code base MS released under MIT Timo has been working importing.

2024-05-12 21:18 UTC, maj113 requested changes
Remove the windows-2019 builder since it was used only for VS2015 (14.0) builds, after that you can also remove all the os excludes that mention windows-2019 builder since it won't be used anymore

2024-05-13 01:29 UTC, SergeGautherie commented
> Remove the windows-2019 builder

Indeed, see/update line 92.

2024-05-13 07:59 UTC, tkreuzer approved these changes

2024-05-14 14:45 UTC, maj113 approved these changes

2024-05-15 02:39 UTC, merged