[SYSSETUP] Add en-GB.rc
reactos/reactos pull request #3950
Opened 2021-09-09 23:32 UTC by PopuriAO29

The British Language wasn't included here. However, i have corrected some texts that are still American English.

## Purpose

The British English resource wasn't exist while during Setup. however, There might include various American English text including the word "Customize", So i have decided add these on it.

## Proposed changes

_Describe what you propose to change/add/fix with this pull request._

- The file en-GB.rc isn't exist on SYSSETUP Language Resource folder.

2021-09-09 23:35 UTC, binarymaster requested changes
Please add created `en-GB.rc` file to the main resource source here: https://github.com/reactos/reactos/blob/master/dll/win32/syssetup/syssetup.rc#L65

2021-09-09 23:35 UTC, binarymaster commented on dll/win32/syssetup/lang/en-GB.rc
> +
Also you can just drop this header.

2021-09-10 10:50 UTC, binarymaster approved these changes
Ok I also noticed PR you created in your own repo https://github.com/PopuriAO29/reactos/pull/1 - I think it's highly related and it should be done here as well, so I committed it to the branch of this PR.

2021-09-10 11:10 UTC, merged

2021-09-11 08:44 UTC, eason329 commented
Actually what is the purpose of changing the translation for language files other than English? (Because it made conflicts to my PR.)

2021-09-11 20:57 UTC, binarymaster commented
There was a typo in english translation, but some other translation files were untranslated, so they contained the same typo.