[TRANSLATION] Chinese Traditional (zh-TW) translation update - Oct 2021
reactos/reactos pull request #4039
Opened 2021-10-15 15:59 UTC by eason329

## Purpose
update Chinese Traditional (zh-TW) translation

## Proposed changes
- Translate strings still have original English text
- Replace and unify terms with one used in Taiwan
- replacing the symbols with full width equivalents when appropriate as stated in PR 3954
- Rename and update for For_Chinese_Translation.txt
- Two separated Chinese translation for `COMCTL32` (which is came from Wine) will be combined into one file 
>ROS supports multiple sublanguages in a single language RC file

-----
please add the 'hacktoberfest-accepted' label to this if this PR fits. Thanks 
> I assume this PR may merge after October

2021-11-18 08:46 UTC, eason329 commented
If there is no more review in next 7 days, I will assume this PR can be merged.

2021-11-25 07:19 UTC, eason329 commented
> If there is no more review in next 7 days, I will ping a maintainer to merge this PR.

7 days has passed, so @binarymaster may you check whether this PR can be merged?

2021-12-09 18:40 UTC, binarymaster commented on dll/shellext/acppage/lang/zh-TW.rc
> + * LICENSE:     GPL-2.0-or-later (https://spdx.org/licenses/GPL-2.0-or-later)
See https://github.com/reactos/reactos/blob/3b008a87d86eda31ea3177f043dfc4c151668d47/dll/shellext/acppage/ACPPage.cpp
```suggestion
 * PROJECT:     ReactOS Compatibility Layer Shell Extension
 * LICENSE:     GPL-2.0+ (https://spdx.org/licenses/GPL-2.0+)
```

2021-12-09 18:40 UTC, binarymaster commented on dll/shellext/devcpux/lang/zh-TW.rc
> + * TRANSLATOR:  Copyright 2018 Luo Yufan <njlyf2011@hotmail.com>
Didn't added yourself here :)
```suggestion
 * TRANSLATOR:  Copyright 2018 Luo Yufan <njlyf2011@hotmail.com>
 *              Copyright 2021 Chan Chilung <eason066@gmail.com>
```

2021-12-09 18:40 UTC, binarymaster commented on dll/shellext/mydocs/lang/zh-TW.rc
> + * LICENSE:     GPL-2.0-or-later (https://spdx.org/licenses/GPL-2.0-or-later)
See https://github.com/reactos/reactos/blob/3b008a87d86eda31ea3177f043dfc4c151668d47/dll/shellext/mydocs/mydocs.cpp
```suggestion
 * PROJECT:     ReactOS MyDocs
 * LICENSE:     LGPL-2.1+ (https://spdx.org/licenses/LGPL-2.1+)
```

2021-12-09 18:40 UTC, binarymaster commented on dll/shellext/netshell/lang/zh-TW.rc
> + * LICENSE:     GPL-2.0-or-later (https://spdx.org/licenses/GPL-2.0-or-later)
See https://github.com/reactos/reactos/blob/3b008a87d86eda31ea3177f043dfc4c151668d47/dll/shellext/netshell/netshell.cpp
```suggestion
 * PROJECT:     ReactOS Network Shell
 * LICENSE:     LGPL-2.1-or-later (https://spdx.org/licenses/LGPL-2.1-or-later)
```

2021-12-09 18:40 UTC, binarymaster commented on dll/win32/comctl32/lang/comctl_Tw.rc
> -END
I'm not sure it's correct to delete this file.

2021-12-09 18:40 UTC, binarymaster commented on media/doc/Chinese translation notes.txt
> +（最近更新日期：2021 年 11 月 20 日）
If you want to rename this file, better do it in separate commit, for clearer history.

2021-12-09 18:40 UTC, binarymaster commented on base/applications/taskmgr/lang/zh-TW.rc
> + * LICENSE:     GPL-2.0-or-later (https://spdx.org/licenses/GPL-2.0-or-later)
See https://github.com/reactos/reactos/blob/3b008a87d86eda31ea3177f043dfc4c151668d47/base/applications/taskmgr/taskmgr.c
```suggestion
 * LICENSE:     LGPL-2.1-or-later (https://spdx.org/licenses/LGPL-2.1-or-later)
```

2021-12-09 18:40 UTC, binarymaster commented on base/applications/rapps/lang/zh-TW.rc
> + * PROJECT:     ReactOS ReactOS Applications Manager
```suggestion
 * PROJECT:     ReactOS Applications Manager
```

2021-12-09 18:40 UTC, binarymaster commented on base/applications/games/spider/lang/zh-TW.rc
> + * PROJECT:     ReactOS Spider Solitaire
Leave as is
```suggestion
 * PROJECT:     Spider Solitaire
```

2021-12-09 18:40 UTC, binarymaster commented on base/applications/dxdiag/lang/zh-TW.rc
> + * LICENSE:     GPL-2.0-or-later (https://spdx.org/licenses/GPL-2.0-or-later)
Actually LGPL - https://github.com/reactos/reactos/blob/3b008a87d86eda31ea3177f043dfc4c151668d47/base/applications/dxdiag/dxdiag.c
```suggestion
 * LICENSE:     LGPL-2.1-or-later (https://spdx.org/licenses/LGPL-2.1-or-later)
```

2021-12-09 18:41 UTC, binarymaster commented on base/applications/dxdiag/lang/zh-TW.rc
> + * PROJECT:     ReactOS ReactX-Diagnostic program
```suggestion
 * PROJECT:     ReactX Diagnosis Application
```

2021-12-09 19:15 UTC, binarymaster requested changes
:warning: I cannot apply suggestions to your PR. Please allow edits from maintainers.

```
 ! [remote rejected]         pr_branch -> patch-15 (permission denied)
error: failed to push some refs to 'https://github.com/eason329/reactos'
```

2021-12-09 21:53 UTC, binarymaster commented
Ok I'm going to do it with a temporary branch strategy.

2021-12-09 21:54 UTC, merged

2021-12-09 22:26 UTC, binarymaster commented on dll/win32/comctl32/lang/comctl_Zh.rc
> +LANGUAGE LANG_CHINESE, SUBLANG_CHINESE_TRADITIONAL
Ok I verified with Wine, even them have two separate files for zh-CN and zh-TW accordingly:

- https://source.winehq.org/git/wine.git/blob/f69d4a865f926aa5c4a9c55cfe4d2dbc10746e5c:/po/zh_CN.po#l408
- https://source.winehq.org/git/wine.git/blob/f69d4a865f926aa5c4a9c55cfe4d2dbc10746e5c:/po/zh_TW.po#l403

2021-12-09 22:32 UTC, binarymaster commented
Finally merged into c1c59624 and 21d71c28, thanks!

2021-12-10 13:41 UTC, eason329 commented
> ⚠️ I cannot apply suggestions to your PR. Please allow edits from maintainers.
> 
> ```
>  ! [remote rejected]         pr_branch -> patch-15 (permission denied)
> error: failed to push some refs to 'https://github.com/eason329/reactos'
> ```

I can't respond at that moment because that's actually midnight for me and I have exam in the following day. sorry for that

> Ok I verified with Wine, even them have two separate files for zh-CN and zh-TW accordingly:
> 
> * https://source.winehq.org/git/wine.git/blob/f69d4a865f926aa5c4a9c55cfe4d2dbc10746e5c:/po/zh_CN.po#l408
> * https://source.winehq.org/git/wine.git/blob/f69d4a865f926aa5c4a9c55cfe4d2dbc10746e5c:/po/zh_TW.po#l403

I am actually thinking to separating zh translation file for Wine into two, but the veto on [CORE-17110](https://jira.reactos.org/browse/CORE-17110) may prevent me from doing this. I will discuss this on my next PR / on the chat.