[NTDLL_APITEST] NtDuplicateToken.c: Fix error handling
reactos/reactos pull request #4077
Opened 2021-10-28 06:55 UTC by SergeGautherie

## Purpose

Properly handle "all" error cases.

## Results

- Windows:
All succeed.
https://testbot.winehq.org/JobDetails.pl?Key=100888
- ReactOS:
Privileges are reduced to 2, as on Windows.
Groups are reduced by 1, whereas no change on Windows. (Intended or not? See also existing test comment.)
Starts with 20/8, whereas WS03 seems to start with 20/10. (Intended or not?)
NB: On LiveCD, `AdjustTokenPrivileges()` fails with Last Error `1300` (`ERROR_NOT_ALL_ASSIGNED`). (Assumed expected?)

2021-10-31 17:15 UTC, GeoB99 requested changes
>Groups are reduced by 1, whereas no change on Windows. (Intended or not? See also existing test comment.)

`UserAndGroups` member of an access token not only holds groups but also the main user as the first element in the array and what you get in the final results of the tests is the user that's being removed. The user in this context is an administrator (with a SID equivalent to `S-1-5-21-<ID>-500`) and due to the fact that's removed because it's not enabled by default -- a similar behavior with Windows XP where one has such administrator user account disabled.

> Starts with 20/8, whereas WS03 seems to start with 20/10. (Intended or not?)

That's mainly because we aren't assigning two more mandatory groups in the access token upon its creation. I haven't looked deeper which are those but when I get the time for it I'll see.

> NB: On LiveCD, AdjustTokenPrivileges() fails with Last Error 1300 (ERROR_NOT_ALL_ASSIGNED). (Assumed expected?)

`SeImpersonatePrivilege` is a privilege that an object whose token holds it allows to impersonate a client's access token. In this context, virtually every process has it more or less and so is the Command Prompt (as `ntdll_apitest.exe`'s parent process is `cmd.exe`). If on LiveCD the public routine didn't find this specific privilege within the token's privileges of the current process, then that means the blame is on the underlying code and not on the testcase.

Most of the changes you proposed and your doubts as a whole makes me feel you barely have any idea of what you touched so it's better that you don't touch stuff you don't know. The only change that actually makes sense here is the STATUS_BUFFER_TOO_SMALL thing.

2021-10-31 17:15 UTC, GeoB99 commented on modules/rostests/apitests/ntdll/NtDuplicateToken.c
> +    ok_ntstatus(Status, STATUS_ACCESS_VIOLATION);
Revert it back to where it was before.

2021-10-31 17:15 UTC, GeoB99 commented on modules/rostests/apitests/ntdll/NtDuplicateToken.c
> +    }
This is pointless because this is a situation that's highly unlikely to happen for the current calling thread of the process to not have the token.

2021-10-31 17:15 UTC, GeoB99 commented on modules/rostests/apitests/ntdll/NtDuplicateToken.c
> +    }
Revert this.

2021-10-31 17:15 UTC, GeoB99 commented on modules/rostests/apitests/ntdll/NtDuplicateToken.c
> +        goto cleanup;
You're already printing out that token statistics buffer hasn't been allocated due to a failure, no need for a `skip()` call to print the nearly same information again.

2021-10-31 17:15 UTC, GeoB99 commented on modules/rostests/apitests/ntdll/NtDuplicateToken.c
> +    }
When the testcase has reached this path `NtDuplicateToken` is supposed to always succeed and give you the duplicated effective token so this extra code is unnecessary.

2021-10-31 17:15 UTC, GeoB99 commented on modules/rostests/apitests/ntdll/NtDuplicateToken.c
> +
Remove this TODO.

2021-11-01 21:00 UTC, RepOfCATV95 commented
Revert the unnecessary changes as @GeoB99 had said. The code will surely break.

2021-11-19 12:11 UTC, GeoB99 commented
I'm closing this since you haven't yet and for sure won't provide feedback for the reviews I have posted, as this PR will rot as is just like the others of yours. I seriously can't trust you that way. I'll be going to say for the last time -- **don't change stuff you have no idea about**.

2021-11-19 12:11 UTC, closed without merging