[WIN32SS:NTUSER] Fix window state after restoring snapped window. CORE-16477
reactos/reactos pull request #4119
Opened 2021-11-20 16:42 UTC by Getequ

InternalPos.NormalRect is a key data for detecting is window was snapped. Keeping it after restore affecting next snap actions

JIRA issue: [CORE-16477](https://jira.reactos.org/browse/CORE-16477)

2021-11-20 19:13 UTC, JoachimHenze requested changes
I believe that this would not compile C89 because the declaration of variable empty is not top of the block. Please improve. Otherwise I can not merge it back.
Even better: Use RECTL_vSetEmptyRect() instead and avoid that local variable entirely!

2021-11-21 03:36 UTC, Getequ commented on win32ss/user/ntuser/defwnd.c
> +                       // after restoring "normal size" is a trash, erasing it
describe why it must be erased) change a bit

2021-11-21 03:36 UTC, Getequ commented on win32ss/user/ntuser/defwnd.c
>                     else
done

2021-11-21 12:42 UTC, JoachimHenze approved these changes

2021-11-21 17:31 UTC, HBelusca approved these changes

2021-11-23 22:34 UTC, merged