[WIN32SS:NTUSER] Level up Snapping to Windows 10
reactos/reactos pull request #4132
Opened 2021-12-02 07:42 UTC by NikkiNext

I made a window Snap like in Windows 10. Snap works in the upper left corner. So far, it only works with hockey. Hotkey: Win+F2

I checked on the VM. Snapping works

2021-12-02 08:06 UTC, JoachimHenze requested changes

2021-12-02 08:06 UTC, JoachimHenze commented on win32ss/user/ntuser/defwnd.c
> +         TRACE("UDCB Flags %08x\n");
This change is wrong, and makes me think that you created your PR from an outdated state.

2021-12-02 08:06 UTC, JoachimHenze commented on win32ss/user/ntuser/defwnd.c
> +
This change makes no sense.

2021-12-02 09:37 UTC, SergeGautherie commented on win32ss/user/ntuser/defwnd.c
> +               }
No.

2021-12-02 09:37 UTC, SergeGautherie commented on win32ss/user/ntuser/defwnd.c
> +                  if (wParam == VK_RIGHT) // VK_RIGHT
```suggestion
                  else if (wParam == VK_RIGHT) // VK_RIGHT
```

2021-12-02 09:37 UTC, SergeGautherie commented on win32ss/user/ntuser/defwnd.c
> +				  if (wParam == VK_F2)
```suggestion
				  else if (wParam == VK_F2)
```

2021-12-02 09:43 UTC, SergeGautherie commented
Use spaces, not tabulations.

2021-12-02 10:24 UTC, learn-more commented on win32ss/user/ntuser/defwnd.c
> +				  if (wParam == VK_F2)
because any key is the same as VK_F2?

2021-12-02 10:26 UTC, learn-more requested changes
Hello,
Thanks for your interest in ReactOS!
We ask our contributors [to use their full name when committing](https://github.com/reactos/reactos/blob/master/CONTRIBUTING.md#rules-and-recommendations).
[Please amend your commit with your full name](https://stackoverflow.com/a/3042512), and update this PR.

To change this for future PR's, you can update it for globally (for the system):
```
git config --global user.name "Your Name"
git config --global user.email you@example.com
```

Or just for the current repository:
```
git config user.name "Your Name"
git config user.email you@example.com
```

Regards,

2021-12-02 15:54 UTC, HBelusca commented
I don't understand why the hotkey "Win+F2". On my windows 10 machine this doesn't do anything. If I want to use hotkeys to snap on the top-left I press successively "Win+LeftArrow" (twice) then "Win+UpArrow".

2021-12-02 15:54 UTC, HBelusca commented on win32ss/user/ntuser/defwnd.c
> +					 snapRect.bottom = (snapRect.top + snapRect.bottom) / 2;
```suggestion
                     snapRect.bottom = (snapRect.top + snapRect.bottom) / 2;
```
(fixed tabs vs. spaces)

2021-12-02 15:54 UTC, HBelusca commented on win32ss/user/ntuser/input.c
> +				UserRegisterHotKey(PWND_BOTTOM, IDHK_SNAP_LEFTUP, MOD_WIN, VK_F2);
```suggestion
               UserRegisterHotKey(PWND_BOTTOM, IDHK_SNAP_LEFTUP, MOD_WIN, VK_F2);
```

2021-12-02 23:44 UTC, SergeGautherie commented on win32ss/user/ntuser/input.c
> +               UserRegisterHotKey(PWND_BOTTOM, IDHK_SNAP_LEFTUP, MOD_WIN, VK_F2);
Misaligned.

2021-12-19 13:05 UTC, binarymaster requested changes
Did you added unrelated changes to your PR accidentally? Please remove them. Also this PR won't be merged until you address request from Mark.

2021-12-19 13:54 UTC, NikkiNext commented
@learn-more @binarymaster I'm sorry for the confusion. But can you check if my email and name are displayed on Github patches?

2021-12-19 13:57 UTC, closed without merging

2021-12-19 14:34 UTC, NikkiNext commented
I temporarily closed it in order not to mix everything into a mess