Add missing "not" to an install string
reactos/reactos pull request #4172
Opened 2021-12-18 18:12 UTC by cspiegel

## Purpose

A string in the installer is missing the word "not", and as a result is slightly confusing.  Add the missing word.

2021-12-18 18:24 UTC, milawynsrealm commented
The dialog is asking if the computer will be part of a domain. By answering no, the user is essentially saying that it will be part of a workgroup instead, since it can either be part of a domain, or part of a workstation.

2021-12-18 20:18 UTC, gonzoMD commented
> The dialog is asking if the computer will be part of a domain. By answering no, the user is essentially saying that it will be part of a workgroup instead, since it can either be part of a domain, or part of a workgroup.

Like Lee wrote, to make it clear you could add the word 'instead' after 'workgroup' in the RC files.

2021-12-19 12:49 UTC, binarymaster requested changes
Computer can be either part of workgroup or in a domain. It can't belong to neither of these. Please review your changes and correct the wording accordingly.

2021-12-21 08:14 UTC, binarymaster approved these changes
LGTM now. :+1: 

![VirtualBox_ReactOS_21_12_2021_11_12_39](https://user-images.githubusercontent.com/578406/146894777-b00d4a4e-55ba-482f-a16f-47f57dd4c994.png)

2021-12-21 12:40 UTC, merged