[THEMES] Octovita Theme
reactos/reactos pull request #4175
Opened 2021-12-19 14:27 UTC by NikkiNext

## Purpose

I made a Octovita theme. I was inspired by Windows 8 and Gnome 3. Octovita has a dark and light version. The name comes from "Octo" - Windows 8, "Vita"- Life

## Proposed changes

 - Add Octovita Theme resources

## TODO

I made this PR in order for you to understand the patch

P. S. The star in the Start button I temporarily made. Because I couldn't make the ReactOS logo in the Fluent style. I didn't add the wallpaper from the picture below to the repository.

I wish you a Happy New Year. 

![preview1](https://user-images.githubusercontent.com/91015030/146678185-24e12578-fe06-4979-a3bc-fba34fda0862.png)
![preview2](https://user-images.githubusercontent.com/91015030/146678190-b15302cc-3780-47cb-bf3e-2c305d5aec15.png)

2021-12-19 14:29 UTC, NikkiNext commented
I transferred dollars to you through my friend for the development of ReactOS

![donate](https://user-images.githubusercontent.com/91015030/146678458-fdf2d3ea-29da-4f87-a7a0-1c1e8488b2b4.PNG)

2021-12-19 16:30 UTC, HBelusca commented
I wonder whether there could be a dark version of this theme :)

2021-12-19 16:35 UTC, NikkiNext commented
> I wonder whether there could be a dark version of this theme :)

The dark version of the theme will be

2021-12-27 10:59 UTC, NikkiNext commented
@learn-more @binarymaster I have set up an email and a name for PR

2022-01-04 23:14 UTC, Saibamen commented on sdk/cmake/CMakeMacros.cmake
> +	elseif(${dir} STREQUAL reactos/Resources/Themes/Octovita)
```suggestion
    elseif(${dir} STREQUAL reactos/Resources/Themes/Octovita)
```

2022-01-05 08:58 UTC, learn-more commented on sdk/cmake/CMakeMacros.cmake
> +        set(${var} 82)
This also needs an edit in `boot/bootdata/packages/reactos.dff.in`

2022-01-05 10:51 UTC, JoachimHenze requested changes
Thanks for your contribution, but
we agreed in the past that we do not want to add any more Themes in the ros source tree.
At least we won't add any without deleting another one at the same time.
So unless there is common sense between the ros developers about what to drop, you have to commit this into another repository.

2022-01-05 12:00 UTC, closed without merging

2022-01-08 14:06 UTC, NikkiNext commented
@learn-more I added the design theme to the file "reactos.dff.in"

2022-01-08 15:32 UTC, Swyter commented
This one seems really well made, especially if it has light and dark variants. At the very least it can probably be added to RAPPS for a one-click install.

2022-03-04 13:03 UTC, GatoGit21 commented
Honestly Octovita looks beautiful! Good job.
I suggest you that if you still want to publish this theme, create an installer compatible with ROS with your theme's files, upload it to the Internet, create a new txt file in RAPPS, write the download link to your installer and the SHA Key to the file, and commit it to rapps-db. If you created correctly the txt file and complied with the mods' requests, they will merge your file to the db.
This way Octovita could be downloaded and used by ROS users.

2022-03-04 15:50 UTC, Swyter commented
@NikkiNext Yeah, even a self-extracting archive pointed to the right default folder would do the trick. You can contact the ReactOS devs easily through IRC or Matrix, and they can give you some tips. 

The RAPPS file can be as easy to do as this one: https://github.com/reactos/rapps-db/blob/8b572a5644904327f8ff812f1f80351452265af8/longhorn5048.txt

Once it can be installed by normal ReactOS users and they like what they see it will be much easier to convince them to add it to normal builds. Maybe replacing some other theme.

So yeah, I'd do some «lobbying» over Matrix chat. Get it into the project in small increments. 

Your theme is pretty good, I think this was just closed because they already have a lot of themes in the ISO and they wanted to keep them lean. Good luck. :)