[AC97] Add Open Source AC'97 Driver
reactos/reactos pull request #4246
Opened 2022-01-04 07:53 UTC by Obaid51

2022-01-04 08:03 UTC, gonzoMD commented
I'll close this one for several reasons:

There were several attempts to add this in the past by a guy who is not very well accepted by the community.
I suspect that it's either you (hello zero3k), or that, at least, he pushed you to send this pull request (he did that in the past).
Also there is no description, no tests, no prove that it works.
If it has nothing to do with zero3k, feel free to get in touch with us, but at this state, we will not accept it.

2022-01-05 11:24 UTC, JoachimHenze commented
When running that SuperDX ball from the attached video with that new driver, and then exiting SuperDX-ball, will that trigger a heap assertion @Obaid51, or "03k", or "Bryan Kirk"?

2022-01-05 12:03 UTC, gonzoMD commented
OK. I'll reopen it for now. Some people gave careful positive feedback. Give it some time because this has to be tested very well because of known bugs, at least with the proprietary ac97 driver. If the improvement is better than the drawbacks, there is a chance.

2022-01-05 13:35 UTC, Obaid51 commented
Super-DX Ball does not cause a heap assertion for me after I have closed it with the driver included in this PR being installed. 
The patch at https://jira.reactos.org/secure/attachment/61263/NTOS%20MM%20-%20undo%20%09c7e090.diff should help make sure it doesn't happen for anyone that is experiencing it.

2022-01-05 13:52 UTC, ROCKNROLLKID commented
I am not a developer, however before any work should be done on this, can you tell us who actually hired you. I don't think anyone from the actual team hired anyone, so this is likely someone else who did. The reason for our concerned is because the person (zero3K/Bryan) has done this before, and it ended up being a scam. See here for the other pr that he "hired" and ended up being a scam: https://github.com/reactos/reactos/pull/3653

2022-01-05 14:16 UTC, Obaid51 commented
@ROCKNROLLKID Yes, Bryan Kirk (Zero3K) hired me via Upwork.com. I was informed by other developers about his past experiences in the chat room. So I confronted him and then paid the money he agreed to pay in the job post.

2022-01-05 23:35 UTC, jimtabor commented
I have tested and built the original source and it crashes.....

Fix the crash and we can talk.

2022-01-06 00:36 UTC, binarymaster commented
@jimtabor from what I remember you got the crash in QEMU 6.x.x, can you please share your configuration and exact QEMU version?

That could help to reproduce the crash, so @Obaid51 could fix it.

2022-01-07 01:01 UTC, sskras commented
@gonzoMD commented [3 days ago](#issuecomment-1004597470)

> Also there is no description, no tests, no prove that it works.

By the way, speaking of tests: is there any documentation about extending the existing ReactOS test infrastructure?

When to use the `apitests`, the `tests` or the `winetests` in case of regular APIs?
And this case: the `drivers`, the `kmtests` or the `win32`?

I found only [Writing tests](https://reactos.org/wiki/Writing_tests) page on wiki. Tried reading it, but it looks both too bloated and non-uniform (in some places too dense, in some too scarce) to me.

Eg. it still unclear in what dir in the tree should I put these `.xml` files.

2022-01-07 10:27 UTC, learn-more commented
> @gonzoMD commented [3 days ago](#issuecomment-1004597470)
> 
> > Also there is no description, no tests, no prove that it works.
> 
> By the way, speaking of tests: is there any documentation about extending the existing ReactOS test infrastructure?
> 
> When to use the `apitests`, the `tests` or the `winetests` in case of regular APIs? And this case: the `drivers`, the `kmtests` or the `win32`?
> 
> I found only [Writing tests](https://reactos.org/wiki/Writing_tests) page on wiki. Tried reading it, but it looks both too bloated and non-uniform (in some places too dense, in some too scarce) to me.
> 
> Eg. it still unclear in what dir in the tree should I put these `.xml` files.

This page is completely outdated.
Apitests are our own tests, winetests are apitests from wine.
kmtests are driver tests

2022-01-07 11:55 UTC, sskras commented
@learn-more commented [16 minutes ago](#issuecomment-1007300514):

> kmtests are driver tests

Thanks.

So this PR will need test cases, which should be added into `kmtests\ac97`, right?

Or maybe some generic `kmtests\audio` dir?
(as there is common part of audio subsystem that's involved into running ac97, no?)

Maybe `kmtests\wdm\audio`? (as this is WDM driver)

Maybe even `kmtests\wdm\audio\legacy\wdmaud` which would reflect [drivers\wdm\audio\legacy\wdmaud](https://github.com/reactos/reactos/tree/master/drivers/wdm/audio/legacy/wdmaud) path I just found in the repo?

Or did I get the comment from @gonzoMD wrong?

2022-01-14 18:06 UTC, binarymaster requested changes

2022-01-14 18:06 UTC, binarymaster commented on drivers/wdm/audio/drivers/ac97/ac97.inf
> +ac97.DeviceDesc="AC'97 Treiberbeispiel f�r Intel(r) 82801 Kontroller"
```suggestion
ac97_AA.DeviceDesc="Intel 82801AA AC'97 Audiocontroller"
ac97_AB.DeviceDesc="Intel 82801AB AC'97 Audiocontroller"
ac97_BA.DeviceDesc="Intel 82801BA/BAM AC'97 Audiocontroller"
ac97.DeviceDesc="Intel 82801 AC'97 Audiocontroller"
```

2022-01-14 18:06 UTC, binarymaster commented on sdk/include/ddk/portcls.h
> +
All these changes outside the driver also must go by a separate commit(s).

2022-01-22 23:31 UTC, Extravert-ir requested changes
Information about the driver needs to be added to https://github.com/reactos/reactos/blob/master/media/doc/3rd%20Party%20Files.txt file.
Now please address remaining remarks and we're good to go.

2022-01-22 23:31 UTC, Extravert-ir commented on drivers/wdm/audio/drivers/ac97/license.txt
> +    MIT License
Please, remove extra spaces in the beginning (all lines)

2022-01-22 23:31 UTC, Extravert-ir commented on sdk/include/psdk/ksmedia.h
> +#define STATIC_KSAUDFNAME_PC_SPEAKER_VOLUME\
Either move the change to a separate commit, or move it to a separate PR

2022-01-22 23:31 UTC, Extravert-ir commented on drivers/wdm/audio/drivers/ac97/CMakeLists.txt
> +set_module_type(ac97 wdmdriver UNICODE)
```suggestion
set_module_type(ac97 wdmdriver)
```

2022-01-22 23:31 UTC, Extravert-ir commented on drivers/wdm/audio/drivers/ac97/CMakeLists.txt
> +if(USE_CLANG_CL OR (NOT MSVC))
```suggestion
if(CMAKE_C_COMPILER_ID STREQUAL "GNU" OR CMAKE_C_COMPILER_ID STREQUAL "Clang")
```

2022-01-22 23:31 UTC, Extravert-ir commented on drivers/wdm/audio/drivers/ac97/CMakeLists.txt
> +add_cd_file(FILE "${CMAKE_CURRENT_SOURCE_DIR}/ac97.inf" DESTINATION reactos/inf FOR all)
```suggestion
add_driver_inf(ac97 ac97.inf)
```

2022-01-22 23:31 UTC, Extravert-ir commented on drivers/wdm/audio/drivers/ac97/CMakeLists.txt
> +)
```suggestion
    wavecyclicstream.cpp)
```

2022-01-23 01:00 UTC, Vayne2500 commented
How do I fix the duplicate commits?

2022-01-23 17:51 UTC, Vayne2500 commented
I have done all of the requested changes under my Zero3K account.

2022-01-25 00:17 UTC, closed without merging