[FREELDR] LoadModule(): Add error handling
reactos/reactos pull request #4294
Opened 2022-01-16 23:23 UTC by SergeGautherie

## Purpose

Better fail gracefully, than later load default file(s) silently...

Another testcase:
Select kdscreen.dll entry on a msvc build!

JIRA issue: [CORE-17645](https://jira.reactos.org/browse/CORE-17645)

## Proposed changes

- LoadModule(): Check/log errors.
- LoadWindowsCore(): Check/log/return LoadModule() failures.

2022-01-17 07:00 UTC, SergeGautherie commented
> Select kdscreen.dll entry on a msvc build!

Actually, gcc build is affected too.
Only kdcom and kdvbox exist: kdscreen and kdfile do not, so kdcom is loaded later/instead.
Then, why is there code to try to load such nonexistent filenames?

2022-01-17 12:39 UTC, HBelusca requested changes

2022-01-17 12:39 UTC, HBelusca commented on boot/freeldr/freeldr/ntldr/winldr.c
>               * or: /DEBUGPORT=FOO
These are **just** examples, not the only actual list of options supported. (and "FOO" is definitively placeholder for any name).

2022-01-17 12:39 UTC, HBelusca commented on boot/freeldr/freeldr/ntldr/winldr.c
> +                (OptionLength == 6 && _strnicmp(Option, "SCREEN", 6) == 0))
Now, if we happen (or some user happen) to introduce a genuine "kdscreen.dll" (for example) debug transport dll file, you are forbidding it from loading?

Please don't change code you don't fully understand why it is there.

2022-02-18 19:28 UTC, HBelusca commented
Parts of this PR have been merged into master, see commit 15e1489c7f.

2022-02-18 19:28 UTC, closed without merging