[ACCESS] Improve pt-PT translation
reactos/reactos pull request #4326
Opened 2022-01-30 16:15 UTC by zecarlos1957

[CPL.ACCESS] Improve pt-PT translation
[CPL:ACCESS] Adjust object position for better appearance

2022-01-30 16:16 UTC, zecarlos1957 commented
![Before](https://user-images.githubusercontent.com/49964946/151707694-62bfd26e-5601-4b29-ad37-dd4a4c638b7a.png)
![After](https://user-images.githubusercontent.com/49964946/151707698-01935699-1400-4ebe-80d1-884e16d33aa1.png)

2022-01-30 16:19 UTC, zecarlos1957 commented
![Before](https://user-images.githubusercontent.com/49964946/151707805-735af9d0-c8b2-4cfa-a9a9-6472c542e2e9.png)
![After](https://user-images.githubusercontent.com/49964946/151707806-1bfce375-d7c3-4e64-95c2-cfae63fa561e.png)

2022-02-06 01:22 UTC, zecarlos1957 commented
Before
![FindBefore](https://user-images.githubusercontent.com/49964946/152664462-93adb2ac-9a76-4561-8dd9-dbe9b2184576.png)

After
![FindAfter](https://user-images.githubusercontent.com/49964946/152664465-ac7ec697-4732-4c36-af1b-5f14e3c7009f.png)

2022-02-24 19:15 UTC, HBelusca requested changes

2022-02-24 19:15 UTC, HBelusca commented on base/applications/regedit/lang/pt-PT.rc
> +    CONTROL "Corresponder apenas &cadeia completa", IDC_MATCHSTRING, "Button", BS_AUTOCHECKBOX |
keyboard accelerator for "c" is already taken by "Chaves" button, see above.

2022-02-24 19:15 UTC, HBelusca commented on dll/cpl/access/lang/pt-PT.rc
> +    LTEXT "O atalho para ""Teclas lentas"" é:\nManter premida a tecla SHIFT da direita  durante oito segundos.",
```suggestion
    LTEXT "O atalho para ""Teclas lentas"" é:\nManter premida a tecla SHIFT da direita durante oito segundos.",
```

2022-03-27 19:20 UTC, HBelusca approved these changes

2022-03-31 12:58 UTC, merged