[TRANSLATION][NOTEPAD] Croatian Notepad translation
reactos/reactos pull request #4330
Opened 2022-02-01 15:45 UTC by Andrej123456789

## Purpose
Translate Notepad to Croatian
JIRA issue: N/A

## Proposed changes
- Upload hr-HR.rc

## TODO
Nothing :)

2022-02-02 20:36 UTC, HBelusca requested changes

2022-02-02 20:36 UTC, HBelusca commented on base/applications/notepad/hr-Hr.rc
> + LANGUAGE LANG_CROATIAN, SUBLANG_DEFAULT
```suggestion
LANGUAGE LANG_CROATIAN, SUBLANG_DEFAULT
```

2022-02-02 20:36 UTC, HBelusca commented on base/applications/notepad/rsrc.rc
> -/*
Please revert this change, and be sure that *no encoding change* happens there.
(in particular, don't use github editor to work on translations.)

2022-02-05 12:45 UTC, Andrej123456789 commented
I will close this and create new Pull Request

2022-02-05 12:45 UTC, closed without merging