[NTGDI] Check if face->charmap is not zero before accessing its encoding
reactos/reactos pull request #4390
Opened 2022-03-13 10:04 UTC by julcar

## Purpose

Attempting to start DevExpress Ribbon Notepad makes crash ReactOS due to null pointer access, after some investigation, I found that `(face->charmap)` might return 0 sometimes, and we are not making this check.

This allows DevExpress Ribbon Notepad sample to start.

JIRA issue: [CORE-18091](https://jira.reactos.org/browse/CORE-18091)

2022-03-13 11:56 UTC, learn-more commented
There are a few places where it's checked for NULL already,
but all these places also assign a charmap in that case.
Sadly, there are some changes between how they manage that, but I suspect that they should all do the same.
(And that it should happen in all cases before `->charmap` is accessed.

https://git.reactos.org/?p=reactos.git&a=search&h=HEAD&st=grep&sr=1&s=charmap+%3D%3D+NULL

2022-03-13 22:50 UTC, vicmarcal commented
> There are a few places where it's checked for NULL already, but all these places also assign a charmap in that case. Sadly, there are some changes between how they manage that, but I suspect that they should all do the same. (And that it should happen in all cases before `->charmap` is accessed.
> 
> https://git.reactos.org/?p=reactos.git&a=search&h=HEAD&st=grep&sr=1&s=charmap+%3D%3D+NULL

Mmm comparing all the uses, seems the first result in that link is following a different pattern (encoding checking) to assign a charmap  compared with the other 2 (which are blindly assigning the first one found). Any reasoning behind that? Just curious.

2022-07-17 19:45 UTC, katahiromz approved these changes

2022-09-07 07:21 UTC, KRosUser commented
Does it fixes the refered Jira ticket ? Or is it a side fix ?

2022-09-14 19:10 UTC, julcar commented
> Does it fixes the refered Jira ticket ? Or is it a side fix ?

It is a real fix, the program affected started to run after applying the fix

2022-09-14 19:35 UTC, KRosUser commented
So good to merge since July, right ?

2022-12-11 18:18 UTC, KRosUser2 commented
@julcar : Still OK to go with this PR ?

2022-12-12 14:47 UTC, learn-more approved these changes

2023-01-18 06:28 UTC, KRosUser2 approved these changes

2023-01-18 06:29 UTC, KRosUser2 commented
Please note it also fixes https://jira.reactos.org/browse/CORE-18558

2023-01-18 09:32 UTC, tkreuzer requested changes
This is at best a band-aid. There is a lot wrong in the code. 

- With this fix ftGetFontUnicodeRanges would simply fail, instead of selecting the proper charmap.
- In some places the code alls FT_Set_Charmap, first acquiring, then instantly releasing the freetype lock. This is wrong. Either we set the charset only once and keep it immutable in the rest of the code, or all code that relies on it must run with the freetype lock help.
- Code duplication.

I'm ok with a quick-fix, but put at least a fat DPRINT1 there.

2023-01-18 09:32 UTC, tkreuzer commented on win32ss/gdi/ntgdi/freetype.c
> +    if (!(face->charmap)) return 0;
```suggestion
    if (face->charmap == NULL)
    {
        DPRINT1("FIXME: No charmap selected! This is a BUG!\n");
        return 0;
    }
```

2023-01-18 17:28 UTC, JoachimHenze approved these changes

2023-01-18 18:18 UTC, tkreuzer approved these changes

2023-01-18 18:24 UTC, merged