Bg language part one
reactos/reactos pull request #4429
Opened 2022-04-06 19:20 UTC by delphipro

## Purpose

_Do a quick recap of your work here._

JIRA issue: [CORE-XXXX](https://jira.reactos.org/browse/CORE-XXXX)

## Proposed changes

_Describe what you propose to change/add/fix with this pull request._

I fixed several files with Bulgarian translation

## TODO

_Use a TODO when your pull request is Work in Progress._

- [ ] 
- [ ]

2022-04-07 17:32 UTC, HBelusca commented on base/applications/mspaint/lang/bg-BG.rc
> +    IDS_WINDOWTITLE "%s - paint"
```suggestion
    IDS_WINDOWTITLE "%s - Paint"
```

2022-04-07 17:33 UTC, HBelusca commented on dll/cpl/inetcpl/lang/bg-BG.rc
> + * English resources for the Internet control panel applet
```suggestion
 * Bulgarian resources for the Internet control panel applet
```

2022-04-07 17:37 UTC, HBelusca requested changes
Some last points to investigate.
Please also ensure that, in the new files, encoding is UTF-8 and newlines are in the CR-LF format.

2022-04-07 17:37 UTC, HBelusca commented on dll/win32/crypt32/crypt32.rc
> +#ifdef LANGUAGE_BG_BG
```suggestion

#ifdef LANGUAGE_BG_BG
```

2022-04-07 17:37 UTC, HBelusca commented on dll/win32/cryptui/cryptui.rc
> +
```suggestion
```

2022-04-07 17:37 UTC, HBelusca commented on dll/win32/cryptui/cryptui.rc
> +#include "lang/cryptui_Bg.rc"
```suggestion
    #include "lang/cryptui_Bg.rc"
```

2022-04-07 17:37 UTC, HBelusca commented on base/shell/explorer/lang/bg-BG.rc
> +CAPTION "Start menu"
Left untranslated?

2022-04-07 17:37 UTC, HBelusca commented on base/shell/explorer/lang/bg-BG.rc
> +CAPTION "Taksbar"
Left untranslated? (and there's a typo now)

2022-04-07 17:37 UTC, HBelusca commented on base/shell/explorer/lang/bg-BG.rc
> +IDD_TASKBARPROP_TASKBAR DIALOGEX 0, 60, 252, 218
OK that change is weird.

2022-04-07 18:53 UTC, delphipro commented on base/shell/explorer/lang/bg-BG.rc
> +CAPTION "Start menu"
Correct is "Старт меню"
![image](https://user-images.githubusercontent.com/25673692/162275532-75f046d7-5cc0-460d-a9ff-ee82fb9a969a.png)

but after click on "Старт меню". 
![image](https://user-images.githubusercontent.com/25673692/162275852-33ab9e0b-afc1-435f-aebe-56842fac9b78.png)

so I returned the old translation

2022-04-08 02:01 UTC, HBelusca commented on base/shell/explorer/lang/bg-BG.rc
> +CAPTION "Start menu"
huh lol
Looks like a bug.

2022-05-15 14:45 UTC, binarymaster commented on dll/win32/msgina/lang/bg-BG.rc
> +    CONTROL IDI_ROSLOGO, IDC_ROSLOGO, "Статично", SS_BITMAP, 0, 0, 275, 54
This "Static" is non-localizable, it should not be translated.

2022-09-28 15:36 UTC, binarymaster commented
@HBelusca the PR author seems to be unavailable, you can probably assign it to yourself, or I can help as well.

Note that his GitHub name is cyrillic, while we may prefer latin characters for the name -- so a manual merge will be needed in this case.

![image](https://user-images.githubusercontent.com/578406/192822886-78b2cce1-438b-4fa5-a191-ee757605a928.png)

2022-09-28 15:47 UTC, HBelusca commented
Yes I'm going to do the necessary adjustments.

2022-09-28 17:52 UTC, winterhell commented on base/shell/explorer/lang/bg-BG.rc
> +CAPTION "Taksbar"
I've seen Taskbar in literature as "Лента с инструменти"

2022-09-28 20:40 UTC, HBelusca commented on dll/cpl/inetcpl/inetcpl.rc
>   #pragma code_page(65001)
```suggestion
/* UTF-8 */
#pragma code_page(65001)
```

2022-09-28 20:40 UTC, HBelusca commented on dll/win32/msgina/lang/bg-BG.rc
> +CAPTION "Добре дошли"
English translation and others have the equivalent of "Welcome to ReactOS"

2022-09-28 20:40 UTC, HBelusca commented on dll/win32/msgina/lang/bg-BG.rc
> +    CONTROL IDI_ROSLOGO, IDC_ROSLOGO, "Статично", SS_BITMAP, 0, 0, 275, 54
```suggestion
    CONTROL IDI_ROSLOGO, IDC_ROSLOGO, "Static", SS_BITMAP, 0, 0, 275, 54
```

2022-09-28 20:40 UTC, HBelusca commented on base/shell/explorer/lang/bg-BG.rc
> +IDD_TASKBARPROP_TASKBAR DIALOGEX 0, 60, 252, 218
```suggestion
IDD_TASKBARPROP_TASKBAR DIALOGEX 0, 0, 252, 218
```

2022-09-28 20:40 UTC, HBelusca commented on base/shell/explorer/lang/bg-BG.rc
> +CONTROL "", IDC_TASKBARPROP_STARTMENU_BITMAP, "Статично", SS_BITMAP | SS_SUNKEN,7, 7, 183, 108
```suggestion
    CONTROL "", IDC_TASKBARPROP_STARTMENU_BITMAP, "Static", SS_BITMAP | SS_SUNKEN, 7, 7, 183, 108
```

2022-09-28 22:13 UTC, HBelusca commented on dll/win32/msgina/lang/bg-BG.rc
> +CAPTION "Добре дошли"
```suggestion
CAPTION "Добре Дошли в ReactOS"
```

2022-09-28 22:17 UTC, HBelusca commented on base/applications/calc/lang/bg-BG.rc
> +CAPTION "Калкулатор на ReactOS"
```suggestion
CAPTION "Калкулатор за ReactOS"
```

2022-09-29 09:51 UTC, HBelusca commented on base/shell/explorer/lang/bg-BG.rc
> +CAPTION "Taksbar"
...or "Лентата на задачите" ?
https://support.microsoft.com/bg-bg/windows/%D0%BA%D0%B0%D0%BA-%D0%B4%D0%B0-%D0%B8%D0%B7%D0%BF%D0%BE%D0%BB%D0%B7%D0%B2%D0%B0%D1%82%D0%B5-%D0%BB%D0%B5%D0%BD%D1%82%D0%B0%D1%82%D0%B0-%D0%BD%D0%B0-%D0%B7%D0%B0%D0%B4%D0%B0%D1%87%D0%B8%D1%82%D0%B5-%D0%B2-windows-11-0657a50f-0cc7-dbfd-ae6b-05020b195b07

2022-09-30 15:40 UTC, HBelusca commented on base/shell/explorer/lang/bg-BG.rc
> +    LTEXT            "Програми в менюто Старт:", IDC_STATIC, 14, 86, 112, 8
```suggestion
    LTEXT            "&Програми в менюто Старт:", IDC_STATIC, 14, 86, 112, 8
```

2022-09-30 15:40 UTC, HBelusca commented on base/shell/explorer/lang/bg-BG.rc
> +    PUSHBUTTON       "&Изчисти списъка", IDC_CLEARLIST, 182, 98, 57, 14
```suggestion
    PUSHBUTTON       "Изчисти &списъка", IDC_CLEARLIST, 182, 98, 57, 14
```

2022-09-30 15:40 UTC, HBelusca commented on base/shell/explorer/lang/bg-BG.rc
> +    AUTOCHECKBOX     "Не прави тази проверка при стартиране", IDC_NOTCHECK, 7, 62, 139, 10
```suggestion
    AUTOCHECKBOX     "&Не прави тази проверка при стартиране", IDC_NOTCHECK, 7, 62, 139, 10
```

2022-09-30 15:40 UTC, HBelusca commented on base/shell/explorer/lang/bg-BG.rc
> +    PUSHBUTTON       "Добави...", IDC_CLASSICSTART_ADD, 162, 18, 53, 14
```suggestion
    PUSHBUTTON       "&Добави...", IDC_CLASSICSTART_ADD, 162, 18, 53, 14
```

2022-09-30 15:40 UTC, HBelusca commented on base/shell/explorer/lang/bg-BG.rc
> +    PUSHBUTTON       "Разширени", IDC_CLASSICSTART_ADVANCED, 162, 49, 53, 14
```suggestion
    PUSHBUTTON       "&Премахни...", IDC_CLASSICSTART_REMOVE, 162, 33, 53, 14
    PUSHBUTTON       "&Разширени", IDC_CLASSICSTART_ADVANCED, 162, 49, 53, 14
```

2022-09-30 15:40 UTC, HBelusca commented on base/shell/explorer/lang/bg-BG.rc
> +    PUSHBUTTON "Персонализиране...", IDC_TASKBARPROP_STARTMENUCUST, 192, 132, 53, 14
```suggestion
    PUSHBUTTON "&Персонализиране...", IDC_TASKBARPROP_STARTMENUCUST, 192, 132, 53, 14
```

2022-09-30 15:40 UTC, HBelusca commented on base/shell/explorer/lang/bg-BG.rc
> +    PUSHBUTTON "Персонализиране...", IDC_TASKBARPROP_STARTMENUCLASSICCUST, 192, 172, 53, 14
```suggestion
    PUSHBUTTON "&Персонализиране...", IDC_TASKBARPROP_STARTMENUCLASSICCUST, 192, 172, 53, 14
```

2022-09-30 15:43 UTC, HBelusca commented on base/shell/explorer/lang/bg-BG.rc
> +CAPTION "Лента със задачи"
```suggestion
CAPTION "Лентата със задачите"
```

2022-09-30 16:09 UTC, HBelusca commented
Translation manually committed in master :)

2022-09-30 16:09 UTC, closed without merging