[PCIX] Add 4 OBJ_KERNEL_HANDLE
reactos/reactos pull request #4490
Opened 2022-05-05 21:59 UTC by SergeGautherie

Match `Zw*()` uses.

JIRA issue: [CORE-10207](https://jira.reactos.org/browse/CORE-10207)

2022-05-05 22:14 UTC, HBelusca approved these changes
I even wonder whether other drivers have such problems (including also when using Nt* functions).

2022-05-05 22:41 UTC, SergeGautherie commented
> I even wonder whether other drivers have such problems (including also when using Nt* functions).

That is likely. This PR is only a small step, as I was fixing nearby code, with regard to that ticket.

2022-05-06 15:25 UTC, andy-123 requested changes

2022-05-06 15:25 UTC, andy-123 commented on drivers/bus/pcix/utils.c
> +                               OBJ_KERNEL_HANDLE | OBJ_KERNEL_HANDLE,
"OBJ_KERNEL_HANDLE | OBJ_KERNEL_HANDLE" makes no sense.

2022-05-06 15:25 UTC, andy-123 commented on drivers/bus/pcix/utils.c
> +                               OBJ_KERNEL_HANDLE | OBJ_KERNEL_HANDLE,
"OBJ_KERNEL_HANDLE | OBJ_KERNEL_HANDLE" makes no sense.

2022-05-06 16:40 UTC, HBelusca requested changes

2022-05-06 16:40 UTC, HBelusca commented on drivers/bus/pcix/utils.c
> +                               OBJ_KERNEL_HANDLE | OBJ_KERNEL_HANDLE,
```suggestion
                               OBJ_KERNEL_HANDLE,
```

2022-05-06 16:40 UTC, HBelusca commented on drivers/bus/pcix/utils.c
> +                               OBJ_KERNEL_HANDLE | OBJ_KERNEL_HANDLE,
```suggestion
                               OBJ_KERNEL_HANDLE,
```

2022-05-06 19:05 UTC, SergeGautherie commented on drivers/bus/pcix/utils.c
> +                               OBJ_KERNEL_HANDLE | OBJ_KERNEL_HANDLE,
Oups! Too many copy-pastes, indeed.

2022-05-06 19:05 UTC, SergeGautherie commented on drivers/bus/pcix/utils.c
> +                               OBJ_KERNEL_HANDLE | OBJ_KERNEL_HANDLE,
Reverted.

2022-05-06 19:05 UTC, SergeGautherie commented on drivers/bus/pcix/utils.c
> +                               OBJ_KERNEL_HANDLE | OBJ_KERNEL_HANDLE,
Reverted.

2022-05-06 19:05 UTC, SergeGautherie commented on drivers/bus/pcix/utils.c
> +                               OBJ_KERNEL_HANDLE | OBJ_KERNEL_HANDLE,
Oups! Too many copy-pastes, indeed.

2022-05-06 19:28 UTC, HBelusca approved these changes

2022-05-06 20:55 UTC, SergeGautherie commented
> build-msvc-arm (14.2, arm, Debug)

The usual
`LINK : fatal error LNK1318: Unexpected PDB error; ACCESS_DENIED (15) 'D:\a\reactos\reactos\build\msvc_pdb\vfd.pdb'`

2022-05-06 23:26 UTC, binarymaster commented
> The usual `LINK : fatal error LNK1318: Unexpected PDB error; ACCESS_DENIED (15) 'D:\a\reactos\reactos\build\msvc_pdb\vfd.pdb'`

We're aware of this one happening. It does not affect PR mergeability in any way, so no need to comment.

2022-05-07 14:23 UTC, merged