[EXPLORER] Implementation proposal for Custom Icon Notification dialog page
reactos/reactos pull request #4540
Opened 2022-06-05 23:11 UTC by zecarlos1957

[EXPLORER] Implementation proposal for Custom Icon Notification dialog page

[EXPLORER] Add data to populate IDC_NOTIFICATION_LIST
Adjust object size to full fill behavior item list
Icon notify page

2022-06-05 23:12 UTC, HBelusca commented
do you have a screenshot of this?

2022-06-05 23:14 UTC, zecarlos1957 commented
![VirtualBox_ReactOS_05_06_2022_23_50_50](https://user-images.githubusercontent.com/49964946/172074523-cfacd489-14ba-4a62-97a6-e705a3598e00.png)

2022-06-06 12:00 UTC, learn-more requested changes
I have indicated some problems in your current implementation,
but before we start iterating over those, how would you like to solve the actual hiding of the tray icons?
Because currently this PR only implements the UI, but it does not actually do anything, other than just show the UI.

2022-06-15 07:56 UTC, learn-more commented on base/shell/explorer/notifyiconscust.cpp
> +    ~TrayIconView(){ImageList_Destroy(hImageList);}
If `BuildIconList` is not called, hImageList is uninitialized

2022-06-15 07:59 UTC, learn-more commented on base/shell/explorer/notifyiconscust.cpp
> +            delete m_pListView;
It's better to delete this in `WM_DESTROY`, but be sure to set it to `nullptr` after deleting it, so that a use-after-free will be noticable

2022-06-15 08:10 UTC, learn-more commented on base/shell/explorer/notifyiconscust.cpp
> +        IconData.ReadData(&tb);
This one just copies from `IconData.m_lpData` to `tb`, why?

2022-06-15 08:13 UTC, learn-more commented on base/shell/explorer/notifyiconscust.cpp
> +        HICON hIcon = CopyIcon(idata.hIcon);
This should be more or less equivalent, without some extra copies and the `TrayIconData` object.
```
TBBUTTON tb = {0};

for(int idx = 0; idx < count; idx++)
{
    ::SendMessageW(hToolbar, TB_GETBUTTON, idx, (LPARAM)&tb);
    NOTIFYICONDATAW* idata = (NOTIFYICONDATAW*)tb.dwData;
    HICON hIcon = CopyIcon(idata->hIcon);
```

2022-07-30 19:24 UTC, zecarlos1957 commented
![VirtualBox_ReactOS_05_06_2022_23_50_50](https://user-images.githubusercontent.com/49964946/181955362-676a1b4d-69c1-473b-8c2d-971d601ba438.png)

2022-07-30 19:26 UTC, zecarlos1957 commented
![VirtualBox_ReactOS_05_06_2022_23_50_50](https://user-images.githubusercontent.com/49964946/181956756-9ebce8b2-ecb2-4fc5-91d3-79c922cbd1d1.png)

2022-08-09 18:28 UTC, zecarlos1957 commented
https://user-images.githubusercontent.com/49964946/183733925-43ec1856-592a-43dd-be76-7e9985bce7fb.mp4

Uploading ROS_TrayIcons.mp4…

2022-08-09 20:46 UTC, zecarlos1957 commented
https://user-images.githubusercontent.com/49964946/183757171-e9754151-374d-4232-b750-9c3412ca6305.mp4

2022-10-25 12:17 UTC, learn-more commented on base/shell/explorer/notifyiconscust.cpp
> +    NOTIFYICONDATAW *pIcon = &m_TrayIconData[iItem];
Be careful with this, when resizing `m_TrayIconData`, the address of all items contained in it can change!

2022-10-25 12:17 UTC, learn-more commented on base/shell/explorer/notifyiconscust.cpp
> +            m_pListView->BuildIconList();
Why is `BuildIconList` not called from inside `Create` ?

2022-10-25 12:17 UTC, learn-more commented on base/shell/explorer/notifyiconscust.cpp
> +        szNotification.LoadString(IDS_NOTIFY_HIDEINACTIVE);
This does not take into account the current settings?

2022-10-25 12:17 UTC, learn-more commented on base/shell/explorer/syspager.cpp
> +    PWSTR pszExeName;
`pszExeName` is not used?

2022-10-25 12:17 UTC, learn-more commented on base/shell/explorer/syspager.cpp
> +    EnumIcons(EnumProc, reinterpret_cast<LPARAM>(GetIconList()), expand);
You are not iterating the actual active icons list,
but the list kept by an object that checks icons to see if one died.

2022-10-25 12:17 UTC, learn-more commented on base/shell/explorer/syspager.cpp
> +    AutoTray(FALSE);
If you move the `AutoTray` into the `if (wParam)` then you don't need the `return S_OK;` in the `else

2022-11-11 12:01 UTC, learn-more commented
@zecarlos1957 This ticket provides some more info about how it works in windows:
https://jira.reactos.org/browse/CORE-10849

2023-03-25 09:50 UTC, KRosUser2 commented
@zecarlos1957 beware, this PR is about to be automatically closed

2023-06-17 21:36 UTC, closed without merging