[TRANSLATION] Improved Korean translation.
reactos/reactos pull request #4574
Opened 2022-07-11 01:25 UTC by njlyf2011

Improve Korean translation  (Explorer Shell).

2022-07-11 12:48 UTC, binarymaster commented on base/shell/explorer/lang/ko-KR.rc
> +    AUTORADIOBUTsTON "시작 메뉴(&S)", IDC_TASKBARPROP_STARTMENU, 7, 135, 105, 10
Misclick here :)
```suggestion
    AUTORADIOBUTTON "시작 메뉴(&S)", IDC_TASKBARPROP_STARTMENU, 7, 135, 105, 10
```

2022-07-11 12:48 UTC, binarymaster commented on base/shell/explorer/lang/ko-KR.rc
> +/* Improved by Luke Luo <njlyf2011@hotmail.com> */
Let's use standard header here:
```c
/*
 * PROJECT:     ReactOS Explorer
 * LICENSE:     LGPL-2.1-or-later (https://spdx.org/licenses/LGPL-2.1-or-later)
 * PURPOSE:     Korean resource file
 * TRANSLATORS: Copyright 2008 Seungju Kim aka manatails007 <admin@manateeshome.com>
 *              Copyright 2022 Luke Luo <njlyf2011@hotmail.com>
 */
```

2022-07-12 02:32 UTC, njlyf2011 commented
Thanks.
I will improve them later.

2022-07-15 02:09 UTC, njlyf2011 commented
@katahiromz Excuse me, could you review my translation?

2022-07-15 02:09 UTC, njlyf2011 commented
@katahiromz Excuse me, could you review my translation?

2022-07-15 03:26 UTC, katahiromz reviewed
I am not Korean so I can't understand Korean language. You might have to translate all text.

2022-07-15 03:31 UTC, katahiromz commented
```txt
2022-07-12T05:01:45.9330326Z    Creating library dll\win32\vbscript\vbscript.lib and object dll\win32\vbscript\vbscript.exp
2022-07-12T05:01:45.9334746Z global.c.obj : error LNK2019: unresolved external symbol round referenced in function Global_Round
2022-07-12T05:01:45.9335541Z dll\win32\vbscript\vbscript.dll : fatal error LNK1120: 1 unresolved externals
```
This compilation error is not relevant to this PR.

2022-07-15 11:14 UTC, njlyf2011 commented
I'm a Korean learner, so I can't translate the entire text.  But I can be sure that the text that has been translated is correct.

2022-07-15 11:17 UTC, njlyf2011 commented
> I am not Korean so I can't understand Korean language. You might have to translate all text.

I'm a Korean learner, so I can't translate the entire text.  But I can be sure that the text that has been translated is correct.

You are an active developer from Eastern Asian, and you have fixed the Korean font problem of ReactOS, so I ask you.

2022-07-15 11:24 UTC, katahiromz commented on dll/win32/shell32/lang/ko-KR.rc
>  FONT 9, "굴림", 0, 0, 0x0
```suggestion
FONT 9, "굴림", 0, 0, 0x1
```
The 5th parameter of `FONT` is a charset.

2022-07-15 11:24 UTC, katahiromz commented on dll/win32/shell32/lang/ko-KR.rc
>  FONT 9, "굴림", 0, 0, 0x0
```suggestion
FONT 9, "굴림", 0, 0, 0x1
```

2022-07-15 11:24 UTC, katahiromz commented on dll/win32/shell32/lang/ko-KR.rc
>  FONT 9, "굴림", 0, 0, 0x0
```suggestion
FONT 9, "굴림", 0, 0, 0x1
```

2022-07-15 11:25 UTC, katahiromz commented on dll/win32/shell32/lang/ko-KR.rc
>  FONT 9, "굴림", 0, 0, 0x0
```suggestion
FONT 9, "굴림", 0, 0, 0x1
```

2022-07-15 11:25 UTC, katahiromz commented on dll/win32/shell32/lang/ko-KR.rc
>  FONT 9, "굴림", 0, 0, 0x0
```suggestion
FONT 9, "굴림", 0, 0, 0x1
```

2022-07-15 11:25 UTC, katahiromz commented on dll/win32/shell32/lang/ko-KR.rc
>  FONT 9, "굴림", 0, 0, 0x0
```suggestion
FONT 9, "굴림", 0, 0, 0x1
```

2022-07-15 11:25 UTC, katahiromz commented on dll/win32/shell32/lang/ko-KR.rc
>  FONT 9, "굴림", 0, 0, 0x0
```suggestion
FONT 9, "굴림", 0, 0, 0x1
```

2022-07-15 12:22 UTC, binarymaster commented
I have performed a grep for Korean translators in ReactOS, so far we have only two:
- Seungju Kim - @manatails on GitHub
- YunSong Hwang - perhaps a Wine translator, does not seem to have GitHub account

@manatails if you are available, please review this translation PR.

2022-07-15 15:53 UTC, manatails requested changes
I fixed some minor problems. It will be good for merge.

2022-07-15 15:53 UTC, manatails commented on dll/win32/shell32/lang/ko-KR.rc
> +    LTEXT "아래 목록에서 아이콘 선:", -1, 7, 36, 179, 10
```suggestion
    LTEXT "아래 목록에서 아이콘 선택:", -1, 7, 36, 179, 10
```

2022-07-15 15:53 UTC, manatails commented on dll/win32/shell32/lang/ko-KR.rc
> +    PUSHBUTTON "중단하다", IDCANCEL, 120, 124, 50, 15, WS_VISIBLE
```suggestion
    PUSHBUTTON "중단", IDCANCEL, 120, 124, 50, 15, WS_VISIBLE
```

2022-07-15 15:53 UTC, manatails commented on dll/win32/shell32/lang/ko-KR.rc
> +    LTEXT "아이콘 변경(&C)...", IDC_SHORTCUT_COMMENT, 8, 154, 68, 10
```suggestion
    LTEXT "설명(&C)...", IDC_SHORTCUT_COMMENT, 8, 154, 68, 10
```

2022-07-20 07:04 UTC, njlyf2011 commented
ok.

2022-07-20 13:21 UTC, binarymaster commented on dll/win32/shell32/lang/ko-KR.rc
> + */
```suggestion
/*
 * PROJECT:     ReactOS Shell32
 * LICENSE:     LGPL-2.1-or-later (https://spdx.org/licenses/LGPL-2.1-or-later)
 * PURPOSE:     Korean resource file
 * TRANSLATORS: Copyright 2022 Luke Luo <njlyf2011@hotmail.com>
 */
```

2022-08-16 10:02 UTC, merged