[IMM32] Adjust layout file name to ReactOS
reactos/reactos pull request #4596
Opened 2022-08-03 02:58 UTC by katahiromz

## Purpose
The layout file names are different from Windows' ones.
JIRA issue: [CORE-11700](https://jira.reactos.org/browse/CORE-11700)

## Proposed changes

- `s/kbdjpn.dll/kbdja.dll/`
- `s/kbdkor.dll/kbdko.dll/`

2022-08-03 03:39 UTC, katahiromz commented
mzimeja (MZ-IME Japanese): The Japanese IME I made.
https://github.com/katahiromz/mzimeja

Installing MZ-IME Japanese into ReactOS...

BEFORE:
![before](https://user-images.githubusercontent.com/2107452/182518879-1cb0ced4-9585-4871-ab13-91ebdee07e46.png)
FAILED. Error occurs.

![after](https://user-images.githubusercontent.com/2107452/182518874-7a006d7a-2a63-41e7-aee8-8965a96c2367.png)
Successful. No error.

2022-08-03 14:10 UTC, HBelusca requested changes
Correct fix is to change the ROS keyboard language dll names so as to match windows ones.

2022-08-04 13:29 UTC, HBelusca commented
While I do agree with the renamings of the CJK keyboard layouts, I will double-check the others (for example I have a doubt on kbdes.dll -> kbdsp.dll change...)

2022-08-05 21:19 UTC, HBelusca approved these changes

2022-08-05 23:03 UTC, merged