[TRANSLATION] Croatian translation of games (Solitare and Spider)
reactos/reactos pull request #4664
Opened 2022-09-04 17:24 UTC by Andrej123456789

## Purpose

Translated Solitare and Spider games to Croatian

JIRA issue: N/A

2022-09-04 17:47 UTC, binarymaster reviewed
Correct headers

2022-09-04 17:47 UTC, binarymaster commented on base/applications/games/solitaire/lang/hr-HR.rc
> + */
```suggestion
/*
 * PROJECT:     ReactOS Solitaire
 * LICENSE:     Freeware, permission to use under Public Domain
 * PURPOSE:     Croatian resource file
 * TRANSLATORS: Copyright 2022 Andrej Bartulin <andrej.bartulinvr@gmail.com>
 */
```

2022-09-04 17:47 UTC, binarymaster commented on base/applications/games/spider/lang/hr-HR.rc
> + */
```suggestion
/*
 * PROJECT:     Spider Solitaire
 * LICENSE:     GPL-2.0-or-later (https://spdx.org/licenses/GPL-2.0-or-later)
 * PURPOSE:     Croatian resource file
 * TRANSLATORS: Copyright 2022 Andrej Bartulin <andrej.bartulinvr@gmail.com>
 */
```

2022-09-04 17:47 UTC, HBelusca requested changes

2022-09-04 17:47 UTC, HBelusca commented on base/applications/games/spider/lang/hr-HR.rc
> +    PUSHBUTTON "Cancel", IDCANCEL, 176, 165, 54, 14
```suggestion
    PUSHBUTTON "Odustani", IDCANCEL, 176, 165, 54, 14
```

2022-09-04 17:47 UTC, HBelusca commented on base/applications/games/solitaire/lang/hr-HR.rc
> +LANGUAGE LANG_ENGLISH, SUBLANG_ENGLISH_US
```suggestion
LANGUAGE LANG_CROATIAN, SUBLANG_CROATIAN_CROATIA
```

2022-09-04 17:47 UTC, HBelusca commented on base/applications/games/spider/lang/hr-HR.rc
> +LANGUAGE LANG_ENGLISH, SUBLANG_ENGLISH_US
```suggestion
LANGUAGE LANG_CROATIAN, SUBLANG_CROATIAN_CROATIA
```

2022-09-04 17:47 UTC, HBelusca commented on base/applications/games/solitaire/lang/hr-HR.rc
> + * TRANSLATOR: Andrej Bartulin
```suggestion
 * FILE:        base/applications/games/solitaire/lang/hr-HR.rc
 * PURPOSE:     Croatian Language File for Solitaire
 * TRANSLATOR:  Andrej Bartulin
```

2022-09-04 17:47 UTC, HBelusca commented on base/applications/games/spider/lang/hr-HR.rc
> + * TRANSLATOR: Andrej Bartulin
```suggestion
 * PROJECT:     Spider Solitaire
 * LICENSE:     See COPYING in top level directory
 * FILE:        base/applications/games/spider/lang/hr-HR.rc
 * PURPOSE:     Croatian Language File for Spider Solitaire
 * TRANSLATOR:  Andrej Bartulin
```

2022-09-04 17:47 UTC, HBelusca commented on base/applications/games/spider/lang/hr-HR.rc
> +CAPTION "Select Card Back"
Missing translation.

2022-09-04 17:47 UTC, HBelusca commented on base/applications/games/spider/lang/hr-HR.rc
> +CAPTION "Difficulty"
Missing translation.

2022-09-04 17:47 UTC, HBelusca commented on base/applications/games/solitaire/lang/hr-HR.rc
> +CAPTION "Options"
Missing translation.

2022-09-04 17:47 UTC, HBelusca commented on base/applications/games/solitaire/lang/hr-HR.rc
> +    GROUPBOX "Rezlutat", -1, 100, 7, 75, 53
```suggestion
    GROUPBOX "Rezultat", -1, 100, 7, 75, 53
```

2022-09-04 17:47 UTC, HBelusca commented on base/applications/games/solitaire/lang/hr-HR.rc
> +CAPTION "Select Card Back"
Missing translation.

2022-09-04 17:47 UTC, HBelusca commented on base/applications/games/solitaire/lang/hr-HR.rc
> +    IDS_SOL_SCORE "Rezluat: %d"
```suggestion
    IDS_SOL_SCORE "Rezultat: %d"
```

2022-09-04 17:47 UTC, HBelusca commented on base/applications/games/spider/lang/hr-HR.rc
> +    AUTORADIOBUTTON "Hard: Č&etiri boje", IDC_DIF_FOURCOLORS, 8, 36, 80, 10
Easy/Medium/Hard : Not translated?

2022-09-04 17:47 UTC, HBelusca commented on base/applications/games/solitaire/lang/hr-HR.rc
> +    AUTOCHECKBOX "&Zadrži rezlutat", IDC_OPT_KEEPSCORE, 100, 66, 65, 10, WS_TABSTOP
```suggestion
    AUTOCHECKBOX "&Zadrži rezultat", IDC_OPT_KEEPSCORE, 100, 66, 65, 10, WS_TABSTOP
```

2022-09-04 17:49 UTC, HBelusca commented on base/applications/games/spider/lang/hr-HR.rc
> +    IDS_SPI_WIN "Česitike, pobijedili ste!"
```suggestion
    IDS_SPI_WIN "Čestitke, pobijedili ste!"
```

2022-09-04 19:04 UTC, HBelusca reviewed
Should be OK after those two other modifications.

2022-09-04 19:04 UTC, HBelusca commented on base/applications/games/solitaire/lang/hr-HR.rc
> +    AUTORADIOBUTTON "Nacraj &tri", IDC_OPT_DRAWTHREE, 14, 32, 70, 10
```suggestion
    AUTORADIOBUTTON "Nacrtaj &tri", IDC_OPT_DRAWTHREE, 14, 32, 70, 10
```

2022-09-04 19:04 UTC, HBelusca commented on base/applications/games/solitaire/lang/hr-HR.rc
> +    AUTORADIOBUTTON "&Standarno", IDC_OPT_STANDARD, 107, 19, 60, 10, WS_GROUP | WS_TABSTOP
```suggestion
    AUTORADIOBUTTON "&Standardno", IDC_OPT_STANDARD, 107, 19, 60, 10, WS_GROUP | WS_TABSTOP
```

2022-09-05 12:46 UTC, HBelusca commented on base/applications/games/solitaire/lang/hr-HR.rc
> +    GROUPBOX "Karice", -1, 7, 7, 90, 40
```suggestion
    GROUPBOX "Kartice", -1, 7, 7, 90, 40
```

2022-09-05 12:58 UTC, merged