msconfig lv-LV.rc (Latvian)
reactos/reactos pull request #4838
Opened 2022-11-02 02:57 UTC by Coool

msconfig lv-LV.rc (Latvian) by Coool (github.com/Coool)

2022-11-02 12:24 UTC, binarymaster requested changes
Hello,
Thanks for your interest in ReactOS!
We ask our contributors [to use their full name when committing](https://github.com/reactos/reactos/blob/master/CONTRIBUTING.md#rules-and-recommendations).
[Please amend your commit with your full name](https://stackoverflow.com/a/3042512), and update this PR.

To change this for future PR's, you can update it for globally (for the system):
```
git config --global user.name "Your Name"
git config --global user.email coool@mail.lv
```

Or just for the current repository:
```
git config user.name "Your Name"
git config user.email coool@mail.lv
```

Also please set up your GitHub account accordingly, so maintainers can use Squash & Merge button without getting the author field modified back to nickname by GitHub, it's done in two steps:

1. Set your full name in [GitHub profile settings](https://github.com/settings/profile) (it should match your `user.name` setting)
1. Uncheck `Keep my email addresses private` in [GitHub email settings](https://github.com/settings/emails)

Regards,

2022-11-02 17:02 UTC, binarymaster commented on base/applications/msconfig/lang/lv-LV.rc
> +/* Latvian language resource file (github.com/Coool, 2022-11-02) */
```suggestion
/*
 * PROJECT:     ReactOS System Configuration Tool
 * LICENSE:     LGPL-2.1-or-later (https://spdx.org/licenses/LGPL-2.1-or-later)
 * PURPOSE:     Latvian resource file
 * TRANSLATOR:  Copyright 2022 Your Name <your@email.com>
 */
```

2022-11-02 20:06 UTC, binarymaster requested changes

2022-11-02 20:06 UTC, binarymaster commented on base/applications/msconfig/lang/lv-LV.rc
> +* TRANSLATOR:  Copyright 2022 Coool (github.com/Coool) <coool@mail.lv>
This has to be your full legal name, see [CONTRIBUTING](https://github.com/reactos/reactos/blob/master/CONTRIBUTING.md#rules-and-recommendations)

2022-11-02 20:09 UTC, Coool commented on base/applications/msconfig/lang/lv-LV.rc
> +* TRANSLATOR:  Copyright 2022 Coool (github.com/Coool) <coool@mail.lv>
Hmm, I don't want to share my real name.

2022-11-02 20:10 UTC, binarymaster commented on base/applications/msconfig/lang/lv-LV.rc
> +* TRANSLATOR:  Copyright 2022 Coool (github.com/Coool) <coool@mail.lv>
Sorry, but your contribution wouldn't be accepted then. As you can see, we all are following the rules: https://git.reactos.org/?p=reactos.git;a=shortlog

2022-11-02 20:15 UTC, Coool commented on base/applications/msconfig/lang/lv-LV.rc
> +* TRANSLATOR:  Copyright 2022 Coool (github.com/Coool) <coool@mail.lv>
Что же делать?

2022-11-02 20:25 UTC, binarymaster commented on base/applications/msconfig/lang/lv-LV.rc
> +* TRANSLATOR:  Copyright 2022 Coool (github.com/Coool) <coool@mail.lv>
You have two options, either use real full name, or close Pull Request.

(also please, we are speaking English here to understand each other, we are international community)

2022-11-03 15:53 UTC, Coool commented
I will think about it. It's up to ReactOS staff to decide to merge.

2022-11-03 17:49 UTC, leandrofriedrich commented
Who's gonna tell him...

2023-03-18 01:06 UTC, closed without merging