[SYSSETUP] Update Polish (pl-PL) translation
reactos/reactos pull request #4859
Opened 2022-11-07 11:03 UTC by pithwz

[SYSSETUP] Update Polish (pl-PL) translation

2022-11-07 11:07 UTC, binarymaster commented
Cc @reactos/lang-polish

2022-11-07 12:24 UTC, Saibamen requested changes

2022-11-07 12:24 UTC, Saibamen commented on dll/win32/syssetup/lang/pl-PL.rc
> +    IDS_LOCALETEXT "Standardy i formaty jest ustawione na %s, a lokalizacja jest ustawiona na %s."
```suggestion
    IDS_LOCALETEXT "Standardy i formaty są ustawione na %s, a lokalizacja jest ustawiona na %s."
```

2022-11-07 12:24 UTC, Saibamen commented on dll/win32/syssetup/lang/pl-PL.rc
> +    IDS_LAYOUTTEXT "Twój język i metodę wprowadzania tekstu określa układ klawiatury: %s"
```suggestion
    IDS_LAYOUTTEXT "Domyślnym językiem i metodą wprowadzania tekstu jest układ klawiatury: %s"
```

2022-11-07 12:24 UTC, Saibamen commented on dll/win32/syssetup/lang/pl-PL.rc
> +    IDS_PROCESSTITLE "Zakończenie instalacji"
Not sure
```suggestion
    IDS_PROCESSTITLE "Kończenie instalacji"
```

2022-11-09 22:47 UTC, Saibamen approved these changes

2022-11-09 23:10 UTC, merged