[KMTESTS:CC] Disable broken CcCopyWrite
reactos/reactos pull request #5039
Opened 2023-02-01 20:00 UTC by learn-more

https://build.reactos.org/#/builders/2/builds/2799
https://build.reactos.org/#/builders/2/builds/2798
https://build.reactos.org/#/builders/2/builds/2797
https://build.reactos.org/#/builders/2/builds/2796

2023-02-01 20:16 UTC, Extravert-ir approved these changes

2023-02-01 20:41 UTC, Extravert-ir requested changes
Ah, btw, let's put a comment there about it failing on Windows

2023-02-01 21:34 UTC, learn-more commented
It works again.....



Magic?

2023-02-02 11:37 UTC, learn-more commented
> Ah, btw, let's put a comment there about it failing on Windows. That will help a lot

added.

2023-02-02 13:59 UTC, tkreuzer approved these changes

2023-02-02 14:10 UTC, merged