[USETUP] Slightly optimize CONSOLE_SetStatusTextXV
reactos/reactos pull request #5086
Opened 2023-02-18 09:42 UTC by katahiromz

## Purpose
Speed up.
JIRA issue: N/A

## Proposed changes

- Optimize for speed.

```txt
(base/setup/usetup/consup.c:88) CONSOLE_SetStatusTextXV: 56082048
(base/setup/usetup/consup.c:100) CONSOLE_SetStatusTextXV_Improved: 47834688
```

## TODO

- [x] Do tests.

## Screenshot

![VirtualBox_ReactOS_18_02_2023_18_23_57](https://user-images.githubusercontent.com/2107452/219853493-8272d7ea-cc2c-4de0-a8a0-cfdaa11368b2.png)

2023-02-18 17:32 UTC, HBelusca reviewed
lgtm, I will give a final approval once code is cleaned.

2023-02-18 17:32 UTC, HBelusca commented on base/setup/usetup/consup.c
> +    memset(Buffer, ' ', xScreen);
Shouldn't there be more tests for buffer overflow?
Like for example,
`memset(Buffer, ' ', min(sizeof(Buffer), xScreen));` here,
and using `_vsnprintf` for the call below?

2023-02-18 17:32 UTC, HBelusca commented on base/setup/usetup/consup.c
> +    /* TODO: Delete this test code later */
ok i think you can remove it now :)

2023-02-18 23:16 UTC, katahiromz commented on base/setup/usetup/consup.c
> +    /* TODO: Delete this test code later */
Removed.

2023-02-18 23:17 UTC, katahiromz commented on base/setup/usetup/consup.c
> +    memset(Buffer, ' ', xScreen);
`_vsnprintf` is slower than `vsprintf`.

2023-02-18 23:33 UTC, HBelusca commented on base/setup/usetup/consup.c
> +    memset(Buffer, ' ', xScreen);
OK yeah since the other functions in this file don't really sanitize the lengths, let's go with that philosophy, for the time being...

2023-02-18 23:41 UTC, HBelusca requested changes

2023-02-18 23:41 UTC, HBelusca commented on base/setup/usetup/consup.c
> +    Buffer[x + nLength] = ' ';
Also, `ASSERT(x + nLength < sizeof(Buffer));`

2023-02-18 23:41 UTC, HBelusca commented on base/setup/usetup/consup.c
> +    memset(Buffer, ' ', xScreen);
Using `min(sizeof(Buffer), xScreen)` here, and in the WriteConsoleOutputCharacterA call below, would be more correct, since it would allow a future hypothetical scenario where xScreen could be larger than what it is currently is.

2023-02-18 23:41 UTC, HBelusca commented on base/setup/usetup/consup.c
> +    INT nLength;
Move that before the coPos declaration.

2023-02-19 01:13 UTC, katahiromz commented on base/setup/usetup/consup.c
> +    Buffer[x + nLength] = ' ';
Fixed.

2023-02-19 01:13 UTC, katahiromz commented on base/setup/usetup/consup.c
> +    INT nLength;
Fixed.

2023-02-20 14:17 UTC, HBelusca commented on base/setup/usetup/consup.c
> +                                 xScreen,
Possibly
```suggestion
                                 min(sizeof(Buffer), xScreen),
```

2023-02-20 14:17 UTC, HBelusca commented on base/setup/usetup/consup.c
> +    ASSERT(xScreen <= sizeof(Buffer));
May now be useless, since `min(sizeof(Buffer), xScreen)` is used.

2023-02-21 00:13 UTC, katahiromz commented
There is no flickering. LGTM.

2023-02-21 00:14 UTC, merged

2023-02-21 01:03 UTC, JoachimHenze commented
https://build.reactos.org/#/builders/3/builds/20406 0.4.15-dev-5718-gf1de615 f1de615b9cdb2e267b97f7e55e8712bfba68bd26 VBox befo Katayamas commit [SYSREG] Stage took: 33.335868 seconds
https://build.reactos.org/#/builders/3/builds/20408 0.4.15-dev-5719-gacd3148 acd3148c1a52dfa1eb870d074d9071bbf2b67f26 VBox with Katayamas commit [SYSREG] Stage took: 33.146574 seconds

https://build.reactos.org/#/builders/6/builds/32937 0.4.15-dev-5718-gf1de615 f1de615b9cdb2e267b97f7e55e8712bfba68bd26 KVM  befo Katayamas commit [SYSREG] Stage took: 47.870212 seconds
https://build.reactos.org/#/builders/6/builds/32939 0.4.15-dev-5719-gacd3148 acd3148c1a52dfa1eb870d074d9071bbf2b67f26 KVM  with Katayamas commit [SYSREG] Stage took: 42.906221 seconds

2023-02-21 18:31 UTC, JoachimHenze commented
Do you work with VBox or with KVM Katayama?

2023-02-21 23:20 UTC, katahiromz commented
It's working.