[MSAFD] Work around regression of CORE-18848 from 0.4.12-dev-693-g2b1f6c8
reactos/reactos pull request #5102
Opened 2023-02-25 05:05 UTC by Doug-Lyons

## Purpose

_Fix crash of winetest ws2_32:sock caused by revision 0.4.12-dev-693-g2b1f6c8._

JIRA issue: [CORE-18848](https://jira.reactos.org/browse/CORE-18848)

## Proposed changes

_Revert some minor return value changes by Pierre Schweitzer for CORE-14966 which affects msafd.dll._

It appears that he attempted to improve Steam installs, but was unsuccessful to make the install run with this commit:
https://github.com/reactos/reactos/commit/2b1f6c8b0d73b80c9aeaf8808c66c0c52eb1f320
This seemed intended to only stub some functions, but the new return values caused the ws2_32:sock test to hang.
Therefore, it should not be too dangerous to revert the return values of his changes.

My intent is to reduce the test errors by reverting to the original return values when the 'sock' test worked.
This way a minimum of the current ws2_32:sock tests can be bypassed to allow successful completion of this test.
Currently it is necessary to bypass three (3) of the sub-tests.
With these changes, it will be necessary to only bypass two (2) of the sub-tests.
This test currently always crashes with no summary output because of the internal crash.
I intend to create another PR after this one is merged to allow the sock tests successful completion.
This will be done by temporarily bypassing two (2) of the sub-tests.

The testbot results are shown in the referenced JIRA issue here:  https://jira.reactos.org/browse/CORE-18848
From what I can tell, they look good. I enabled the ws2_32:sock tests by including an additional patch for it.
This allows us to see that the test runs and completes successfully with the two sub-tests bypassed.

2023-02-25 07:18 UTC, JoachimHenze approved these changes

2023-02-25 15:49 UTC, learn-more requested changes

2023-02-25 15:49 UTC, learn-more commented on dll/win32/msafd/misc/dllmain.c
> +                    Ret = SOCKET_ERROR;
Since this introduces a hack, I'd at least expect to see a DPRINT here, but I much prefer not adding hacks like this.

2023-03-08 19:17 UTC, learn-more approved these changes

2023-03-08 20:47 UTC, merged