[NOTEPAD] Finale!
reactos/reactos pull request #5108
Opened 2023-03-01 12:21 UTC by katahiromz

## Purpose
Final finishing.
JIRA issue: [CORE-18837](https://jira.reactos.org/browse/CORE-18837)

## Proposed changes

- Code formatting.
- Rename `DoCreateEditWindow` as `DoReCreateEditWindow` and add `hMainWnd` parameter.
- Add parameter `hMainWnd` to `DoShowHideStatusBar`.
- Improve generic text mapping.
- Reduce lines.

## TODO

- [x] Do tests.

2023-03-01 17:12 UTC, HBelusca requested changes
Please check whether there are no warnings left in x64 builds (both GCC/Clang and MSVC).

2023-03-01 17:12 UTC, HBelusca commented on base/applications/notepad/main.c
>  VOID NOTEPAD_EnableSearchMenu()
```suggestion
VOID NOTEPAD_EnableSearchMenu(VOID)
```

2023-03-01 17:12 UTC, HBelusca commented on base/applications/notepad/main.c
> +    /* Repeat replacing. Show alert at first */
```suggestion
    /* Repeat replacing, only showing alert at first */
```

2023-03-01 17:12 UTC, HBelusca commented on base/applications/notepad/main.c
>      static const TCHAR winName[] = _T("Notepad");
These could be made globals.

2023-03-01 17:12 UTC, HBelusca commented on base/applications/notepad/main.c
>      case WM_CREATE:
```suggestion
    case WM_CREATE:
    {
```

2023-03-01 17:12 UTC, HBelusca commented on base/applications/notepad/main.c
>          break;
```suggestion
        break;
    }
```

2023-03-01 21:59 UTC, katahiromz commented on base/applications/notepad/text.c
> +    hMapping = CreateFileMapping(hFile, NULL, PAGE_READONLY, 0, 0, NULL);
It is considering also ANSI version.

2023-03-01 22:00 UTC, katahiromz commented on base/applications/notepad/text.c
> +ReplaceNewLines(LPTSTR pszNew, SIZE_T cchNew, LPCTSTR pszOld, SIZE_T cchOld)
It is considering also ANSI version.

2023-03-01 22:01 UTC, HBelusca commented on base/applications/notepad/text.c
> +ReplaceNewLines(LPTSTR pszNew, SIZE_T cchNew, LPCTSTR pszOld, SIZE_T cchOld)
Yes that's why I was asking for. It doesn't make sense to want to compile notepad also in ANSI mode.

2023-03-01 22:05 UTC, katahiromz commented on base/applications/notepad/main.c
>  VOID NOTEPAD_EnableSearchMenu()
Fixed.

2023-03-01 22:05 UTC, katahiromz commented on base/applications/notepad/main.c
> +    UINT uEnable = (bEmpty ? MF_GRAYED : MF_ENABLED);
Fixed.

2023-03-01 22:05 UTC, katahiromz commented on base/applications/notepad/main.c
> +    /* Repeat replacing. Show alert at first */
Fixed.

2023-03-01 22:06 UTC, katahiromz commented on base/applications/notepad/main.c
>      static const TCHAR winName[] = _T("Notepad");
Made them global.

2023-03-01 22:08 UTC, katahiromz commented on base/applications/notepad/main.c
>      case WM_CREATE:
Fixed.

2023-03-01 22:08 UTC, katahiromz commented on base/applications/notepad/main.c
>          break;
Fixed.

2023-03-01 22:09 UTC, katahiromz commented on base/applications/notepad/main.c
>      case WM_DESTROY:
Fixed.

2023-03-01 22:23 UTC, katahiromz commented
clang amd64 has the following warnings:
```txt
2023-03-01T21:05:04.0037656Z In file included from ../src/base/applications/notepad/main.c:26:
2023-03-01T21:05:04.0038428Z In file included from ../src/base/applications/notepad/notepad.h:28:
2023-03-01T21:05:04.0038951Z In file included from ../src/sdk/include/psdk/windef.h:202:
2023-03-01T21:05:04.0039632Z In file included from sdk/include/psdk/winnt.h:48:
2023-03-01T21:05:04.0040106Z In file included from ../src/sdk/include/crt/intrin.h:8:
2023-03-01T21:05:04.0041217Z ../src/sdk/include/crt/setjmp.h:200:31: warning: incompatible redeclaration of library function '_setjmp' [-Wincompatible-library-redeclaration]
2023-03-01T21:05:04.0041861Z   int __MINGW_NOTHROW __cdecl _setjmp(jmp_buf _Buf,void *_Ctx);
2023-03-01T21:05:04.0042482Z                               ^
2023-03-01T21:05:04.0043181Z ../src/sdk/include/crt/setjmp.h:200:31: note: '_setjmp' is a builtin with type 'int (_JBTYPE *)' (aka 'int (struct _SETJMP_FLOAT128 *)')
```

2023-03-01 22:51 UTC, HBelusca commented
> > Please check whether there are no warnings left
> 
> The clang amd64 log has the following warnings:
> 
> ```
> 2023-03-01T21:05:04.0037656Z In file included from ../src/base/applications/notepad/main.c:26:
> 2023-03-01T21:05:04.0038428Z In file included from ../src/base/applications/notepad/notepad.h:28:
> 2023-03-01T21:05:04.0038951Z In file included from ../src/sdk/include/psdk/windef.h:202:
> 2023-03-01T21:05:04.0039632Z In file included from sdk/include/psdk/winnt.h:48:
> 2023-03-01T21:05:04.0040106Z In file included from ../src/sdk/include/crt/intrin.h:8:
> 2023-03-01T21:05:04.0041217Z ../src/sdk/include/crt/setjmp.h:200:31: warning: incompatible redeclaration of library function '_setjmp' [-Wincompatible-library-redeclaration]
> 2023-03-01T21:05:04.0041861Z   int __MINGW_NOTHROW __cdecl _setjmp(jmp_buf _Buf,void *_Ctx);
> 2023-03-01T21:05:04.0042482Z                               ^
> 2023-03-01T21:05:04.0043181Z ../src/sdk/include/crt/setjmp.h:200:31: note: '_setjmp' is a builtin with type 'int (_JBTYPE *)' (aka 'int (struct _SETJMP_FLOAT128 *)')
> ```

OK those are completely unrelated to notepad, so you don't need to address those. If you still are interested to fix it, please do that in a separate PR.

2023-03-02 01:40 UTC, TAN-Gaming commented on base/applications/notepad/dialog.c
> +    OPENFILENAME openfilename = { sizeof(openfilename), Globals.hMainWnd };
I think the old style is more readable.

2023-03-02 01:41 UTC, TAN-Gaming commented on base/applications/notepad/dialog.c
> +    OPENFILENAME saveas = { sizeof(saveas), Globals.hMainWnd };
I think the old style is more readable.

2023-03-02 01:45 UTC, TAN-Gaming commented on base/applications/notepad/dialog.c
> +    PRINTDLG printer = { sizeof(printer), Globals.hMainWnd };
Same as the comment above.

2023-03-02 01:47 UTC, TAN-Gaming commented on base/applications/notepad/dialog.c
> +    PAGESETUPDLG page = { sizeof(page), Globals.hMainWnd, Globals.hDevMode, Globals.hDevNames };
Same as the comment above.

2023-03-02 01:57 UTC, katahiromz commented on base/applications/notepad/dialog.c
> +    OPENFILENAME openfilename = { sizeof(openfilename), Globals.hMainWnd };
Reverted.

2023-03-02 01:57 UTC, katahiromz commented on base/applications/notepad/dialog.c
> +    OPENFILENAME saveas = { sizeof(saveas), Globals.hMainWnd };
Reverted.

2023-03-02 01:57 UTC, katahiromz commented on base/applications/notepad/dialog.c
> +    PRINTDLG printer = { sizeof(printer), Globals.hMainWnd };
Reverted.

2023-03-02 01:57 UTC, katahiromz commented on base/applications/notepad/dialog.c
> +    DOCINFO di = { sizeof(di), Globals.szFileTitle };
Reverted.

2023-03-02 01:57 UTC, katahiromz commented on base/applications/notepad/dialog.c
> +    PAGESETUPDLG page = { sizeof(page), Globals.hMainWnd, Globals.hDevMode, Globals.hDevNames };
Reverted.

2023-03-07 12:16 UTC, katahiromz commented on base/applications/notepad/text.c
> +ReplaceNewLines(LPTSTR pszNew, SIZE_T cchNew, LPCTSTR pszOld, SIZE_T cchOld)
The other major code are using generic text mapping...
Some want to compile Notepad in ANSI version...

2023-03-07 13:51 UTC, HBelusca commented on base/applications/notepad/text.c
> +ReplaceNewLines(LPTSTR pszNew, SIZE_T cchNew, LPCTSTR pszOld, SIZE_T cchOld)
>  Some want to compile Notepad in ANSI version...

But whom? You? Your friends? Someone else who told you so? And why would they want to do that only for notepad? Not e.g. mspaint or something else?

2023-03-07 14:00 UTC, katahiromz commented on base/applications/notepad/text.c
> +ReplaceNewLines(LPTSTR pszNew, SIZE_T cchNew, LPCTSTR pszOld, SIZE_T cchOld)
We can provide a way of porting Notepad for unknown Win9x-like OSes.

2023-03-07 14:07 UTC, HBelusca commented on base/applications/notepad/text.c
> +ReplaceNewLines(LPTSTR pszNew, SIZE_T cchNew, LPCTSTR pszOld, SIZE_T cchOld)
This could be the same pseudo-excuse one could make for wanting to get mspaint and others on Win9x, but this doesn't make sense as well.

2023-03-07 14:11 UTC, katahiromz commented on base/applications/notepad/text.c
> +ReplaceNewLines(LPTSTR pszNew, SIZE_T cchNew, LPCTSTR pszOld, SIZE_T cchOld)
Ok, I will revert some parts of generic text mapping. That will be okay.

2023-03-08 01:59 UTC, katahiromz commented
Split this PR into #5129, #5130, #5131, #5132, #5134, and #5135.
Closed.

2023-03-08 01:59 UTC, closed without merging