[MSPAINT] Treat as a file even if the bitmap is empty
reactos/reactos pull request #5109
Opened 2023-03-01 16:47 UTC by atharva1910

JIRA issue: [CORE-18508](https://jira.reactos.org/browse/CORE-18508)

Currently if a file is empty, while loading the file the global variable isAFile is set as FALSE.
This leads to a save as dialogue while saving thinking that no file is loaded

2023-03-01 21:53 UTC, katahiromz approved these changes

2023-03-02 10:28 UTC, katahiromz requested changes
Can you add a filename check please?

2023-03-02 10:31 UTC, katahiromz commented
You can use `PathFileExists` function.

2023-03-02 14:31 UTC, learn-more commented
> Can you add a filename check please?

Can you please elaborate what you expect the author to do when a file is found or not found?

2023-03-02 14:43 UTC, atharva1910 commented
> Can you add a filename check please?

That information is already passed to the function
HBITMAP SetBitmapAndInfo(HBITMAP hBitmap, LPCTSTR name, DWORD dwFileSize, BOOL isFile)
The last paramter indicates the same

2023-03-02 20:10 UTC, katahiromz commented
```
if (!PathFileExists(name))
    isFile = FALSE;
```

2023-03-02 21:28 UTC, roybaer commented
The two-liner suggested by @katahiromz does indeed look like a somewhat better solution, because it only catches the exact problem described.
Off the top of my head I would say that simply omitting `isFile = FALSE;` could potentially cause problems with newly created pictures and the list of recently used files.

2023-03-03 14:18 UTC, atharva1910 commented
The application already checks if a file is being loaded , opens it, checks if the HANDLE is valid and then passes a true value to the function in the last parameter. Why do we wish to do that again. It seems pointless to add the check again

> Off the top of my head I would say that simply omitting isFile = FALSE; could potentially cause problems with newly created pictures and the list of recently used files.
I have ran multiple scenarios using the fix and it works fine in the new file case as well as opening files

2023-03-05 02:39 UTC, katahiromz approved these changes
I did test actually, it is successful. Approved.

2023-03-05 11:53 UTC, merged