[NOTEPAD] Use Globals.hMainWnd in ShowLastError
reactos/reactos pull request #5132
Opened 2023-03-08 01:26 UTC by katahiromz

## Purpose
Improve UI/UX.
JIRA issue: [CORE-18837](https://jira.reactos.org/browse/CORE-18837)

## Proposed changes

- Use `Globals.hMainWnd` variable in `ShowLastError` function.

2023-03-08 07:52 UTC, katahiromz commented
Wrong implementation. Closed.

2023-03-08 18:13 UTC, JoachimHenze requested changes
No this change is not correct.
We do have code in main.c of the kind:

    if (!Globals.hMainWnd)
    {
        ShowLastError();
        ExitProcess(1);
    }

2023-03-08 18:18 UTC, katahiromz commented
We can specify NULL to the 1st parameter of `MessageBox`. Nothing wrong.

2023-03-08 19:16 UTC, learn-more commented
> No this change is not correct. We do have code in main.c of the kind:
> 
> ```
> if (!Globals.hMainWnd)
> {
>     ShowLastError();
>     ExitProcess(1);
> }
> ```

So you are saying that `MessageBox(NULL, ...` is fine,
but 
```
Globals.hMainWnd = NULL;
MessageBox(Globals.hMainWnd, ...
```
is not fine?

2023-03-09 17:14 UTC, HBelusca approved these changes

2023-03-09 22:25 UTC, merged