[NOTEPAD] Russian (ru-RU) translation update
reactos/reactos pull request #5181
Opened 2023-03-21 22:07 UTC by Artem13327

Google Translate helped me to translate some lines

2023-03-22 10:29 UTC, JoachimHenze commented
cc from chat:
@Artem13327 hi, there are two problems with PR #5181 (notepad)
    line 28 - reusing mnemonic key "&о" which is already used in CMD_OPEN
    line 179 - STRING_NOWPRINTING translation is not correct

2023-03-22 11:01 UTC, SigmaTel71 commented on base/applications/notepad/lang/ru-RU.rc
> +    STRING_NOWPRINTING "Печетаемая страница..."
```suggestion
    STRING_NOWPRINTING "Идёт печать страницы..."
```

2023-03-22 11:49 UTC, katahiromz commented
![20230322_204859](https://user-images.githubusercontent.com/2107452/226895468-d578c4cf-e9a1-4988-b5b6-985c485f9143.jpg)

2023-03-22 11:52 UTC, SigmaTel71 commented on base/applications/notepad/lang/ru-RU.rc
> +    STRING_LINE_NUMBER_OUT_OF_RANGE "Указанный номер строки находится вне допустимого диапазона."
```suggestion
    STRING_LINE_NUMBER_OUT_OF_RANGE "Указанный номер строки превышает число строк в файле."
```

2023-03-22 12:03 UTC, katahiromz commented on base/applications/notepad/lang/ru-RU.rc
> +    STRING_LINE_NUMBER_OUT_OF_RANGE "Указанный номер строки находится вне допустимого диапазона."
The negative or zero line number is not acceptable.

2023-03-22 12:32 UTC, katahiromz requested changes

2023-03-22 12:32 UTC, katahiromz commented on base/applications/notepad/lang/ru-RU.rc
> +    STRING_LINE_NUMBER_OUT_OF_RANGE "Указанный номер строки превышает число строк в файле."
The negative or zero line number is not acceptable. Forget Windows.

2023-03-22 12:59 UTC, katahiromz commented on base/applications/notepad/lang/ru-RU.rc
> +    STRING_LINE_NUMBER_OUT_OF_RANGE "Указанный номер строки находится вне допустимого диапазона."
Could you think the best translation?

2023-03-22 13:18 UTC, katahiromz commented on base/applications/notepad/lang/ru-RU.rc
> +    STRING_LINE_NUMBER_OUT_OF_RANGE "Указанный номер строки находится вне допустимого диапазона."
The user might wrongly input the line number of zero, negative, or beyond the maximum line number.

2023-03-22 15:37 UTC, SigmaTel71 commented on base/applications/notepad/lang/ru-RU.rc
> +    STRING_LINE_NUMBER_OUT_OF_RANGE "Указанный номер строки находится вне допустимого диапазона."
> What do you think about this?

Looks acceptable enough to me.

2023-03-22 19:09 UTC, SigmaTel71 commented on base/applications/notepad/lang/ru-RU.rc
> +    STRING_LINE_NUMBER_OUT_OF_RANGE "Указанный номер строки находится вне допустимого диапазона."
> Указанный номер строки находится вне допустимого диапазона.

It looks long to me, that's why I put a suggestion, and Katayama evolved it into «Указанный номер строки вне допустимого диапазона», without «находится» which is easily caught in context of what user is doing.
> Указанная строка находится вне допустимого диапазона.

Doesn't make any sense regarding the context (you input the line number, but not the line).

2023-03-22 22:35 UTC, SigmaTel71 commented on base/applications/notepad/lang/ru-RU.rc
> +    STRING_LINE_NUMBER_OUT_OF_RANGE "Указанный номер строки превышает число строк в файле."
```suggestion
    STRING_LINE_NUMBER_OUT_OF_RANGE "Указанный номер строки вне допустимого диапазона."
```
> Please submit this as Suggested change

Is that your final answer? ©

2023-03-23 05:25 UTC, katahiromz approved these changes
Go.

2023-03-23 05:31 UTC, SigmaTel71 approved these changes

2023-03-23 05:33 UTC, merged