[WinMM] Add default timer resolution compatibility shim
reactos/reactos pull request #5241
Opened 2023-04-15 00:19 UTC by I-Tom-I

## Purpose

Windows 95/98/ME timeGetTime has a default resolution of 1 ms and on Windows NT/2000/XP this same function has a resolution of 10 ms. Add a compatibility shim to the "Windows 95" and "Windows 98 / ME" profiles that changes the default timer resolution to 1ms.

JIRA issue: [CORE-18937](https://jira.reactos.org/browse/CORE-18937)

## Proposed changes

- Add compatibility shim "DefaultTimerResolution1ms" which sets the default timeGetTime resolution to 1ms.
- Assign "DefaultTimerResolution1ms" to the "Windows 95" and "Windows 98 / ME" compatibility profiles.

2023-04-15 10:38 UTC, learn-more requested changes
Absolutely awesome that you took the time to write a shim!

However, I am hesitant to add a bunch of shims that do not provide fixes for real-world applications.
Can you please provide an application that would be fixed by this?

Additionally, there are some bugs in the implementation / improvements that could be made,
but please only address those after we agreed upon moving forward. (Which, for me would be either a really good argument to include this, or real-world applications fixed by this).

2023-04-15 10:38 UTC, learn-more commented on dll/appcompat/shims/genral/timeapi.c
> + * COPYRIGHT:   Copyright 2016,2017 Mark Jansen (mark.jansen@reactos.org)
Pretty sure I did not write this ;)

2023-04-15 10:38 UTC, learn-more commented on dll/appcompat/shims/genral/timeapi.c
> +#include <strsafe.h>
I doubt you need all these includes?

2023-04-15 10:38 UTC, learn-more commented on dll/appcompat/shims/genral/timeapi.c
> +            if (ftimeEndPeriod != NULL && InterlockedAnd(&isResolutionSet, TRUE))
You also 'end' it here when you did not set it yourself (`APIHook_timeBeginPeriod` sets the same thing)

2023-04-15 10:38 UTC, learn-more commented on dll/appcompat/shims/genral/timeapi.c
> +    return CALL_SHIM(0, TIMEBEGINPERIODPROC)(uPeriod);
You actually call `timeGetTime` here (the `0` is the index)

2023-04-15 10:38 UTC, learn-more commented on dll/appcompat/shims/genral/timeapi.c
> +#define SHIM_NUM_HOOKS  1
Only 1 hook will be added, you provided 2

2023-05-03 21:40 UTC, I-Tom-I commented
Closing until an application is found that is improved by the shim

2023-05-03 21:40 UTC, closed without merging