[GETUNAME] Update Romanian translation (2nd attempt)
reactos/reactos pull request #5313
Opened 2023-06-02 17:18 UTC by AndreiMiloiu

This is the second attempt to split the file in chunks. I stopped to line 9400.

2023-06-03 11:30 UTC, HBelusca commented
Comment from @binarymaster:

> My general comment for this PR would be... why there are more added lines than removed?
> Is there something you added from yourself? I'm not sure this is how translations should be done

2023-06-03 12:30 UTC, AndreiMiloiu commented
The file was incomplete. More lines that are available in the English file were not available in the Romanian one, so I had to add them before making the translation of the file. The English, French, Spanish, Hungarian files (and maybe other files, too) are complete, but not the Romanian one.

2023-06-04 00:39 UTC, reactos-contributor requested changes
I made some comments, on what I reviewed so far. I haven't finished, so I'll probably come back later with more.

2023-06-04 00:39 UTC, reactos-contributor commented on dll/win32/getuname/lang/ro-RO.rc
> +    8696 "Săgeată spre dreapta tăiată verticală"
To me, this change looks a bit hard to understand, especially when you preferred „cu tăietură” before (see resource № 2098 & 7661). Please take care of consistency.

2023-06-04 00:39 UTC, reactos-contributor commented on dll/win32/getuname/lang/ro-RO.rc
> +    9955 "Cerc îngroșat cu contur și două puncte deasupra"
I think you want to reconsider „contur” as translation for „stroke”. In many other instances you've used „tăiat” or „cu tăietură”.

2023-06-04 00:39 UTC, reactos-contributor commented on dll/win32/getuname/lang/ro-RO.rc
> -    42861
Here you start using „ruptură” as another translation for „with stroke”. Before you've used „tăiat”/„cu tăietură”. Please take care of consistency.

2023-06-04 00:39 UTC, reactos-contributor commented on dll/win32/getuname/lang/ro-RO.rc
> -    42861
This must be a typo. You most likely meant „curbată” (as „curvată” means something else).

2023-06-04 00:39 UTC, reactos-contributor commented on dll/win32/getuname/lang/ro-RO.rc
> -    42861
I am all for translating as much as possible, but I am not sure „Tiny” and „Miny” (as mathematical operators used in combinatorial game theory) should. See [Tiny and miny on Wikipedia](https://en.wikipedia.org/wiki/Tiny_and_miny)

2023-06-04 10:39 UTC, AndreiMiloiu commented on dll/win32/getuname/lang/ro-RO.rc
> +    1422 "stânga-Facing Armenian Eternity Sign"
Sorry, I will correct it. Thank you for telling me this.

2023-06-04 11:33 UTC, AndreiMiloiu commented
I hope I solved all the mistakes you mentioned until now. I uploaded more translated words, so look at the last version.

2023-06-04 19:21 UTC, AndreiMiloiu commented
Sorry for commit [Lines 55246-64217](https://github.com/reactos/reactos/pull/5313/commits/9b0c8d4c290a94836b74ca2064ef304141eaee49).
I mistakenly made a too big chunk. However, if I remember well everything, it's only my contribution. Everything was in English before. I promise that the next chunks will be smaller than this one.

2023-06-04 20:06 UTC, reactos-contributor commented
> _"I promise that the next chunks will be smaller than this one."_

Well, as of now, the ability to see your work on the file (and add any comments) is not available here until you reduce it to whatever limit GitHub has.

2023-06-04 20:38 UTC, AndreiMiloiu commented
So, do I have to create a new PR again?

2023-06-04 22:08 UTC, reactos-contributor commented
> So, do I have to create a new PR, again? I just wanted to make your work easier, not harder.

Not necessarily. The simplest solution for you would be to have two branches. The current branch to have this file with changes limited to resources up to around what I last commented on, and the newly created branch to contain the rest. Then you go on working carefully on each version separately (only review fixes on this one, active translation on the other).
Do not forget update this PR afterwards, so that review could continue.

2023-06-04 22:42 UTC, AndreiMiloiu commented
I don't know how to do two branches. I corrected some mistakes I discovered afterwards in my file and I made some changes according to your suggestion. I will create a new PR.

2023-06-05 02:16 UTC, reactos-contributor commented
> I don't know how to do two branches.

Yes, tooling may be challenging at times (and especially in the beginning) to understand and use. Use whatever you can, for now.
Whenever you'll have enough patience for getting acquainted with branches, [here is how GitHub explains how to work with them](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository).

2023-06-05 09:27 UTC, AndreiMiloiu commented
Thank you for the information. I will have a look to the link you sent me.

2023-06-05 11:40 UTC, closed without merging