[WINMINE] Rename WineMine to Minesweeper
reactos/reactos pull request #5325
Opened 2023-06-09 15:57 UTC by Artem13327

I also made a translation somewhere right away, as I was able to take it from the shortcuts.inf file and check it for correctness. I will also have to ask for help with line 327 in the shortcuts.inf file from those who know Czech, and with line 844 from those who know Indonesian

2023-06-18 10:58 UTC, ThFabba commented
Does this fix something? If not, I'd rather leave it as WineMine, because that's what it is...

2023-06-21 11:26 UTC, Matriks404 commented
I agree with @Artem13327 name change, since it makes it more clear what game is about, although it definitely doesn't make that much of difference.

2023-07-02 11:12 UTC, GeoB99 requested changes
I'm definitely against this change because WineMine isn't ours (it is literally in the name) and I don't think the license explicitly allows it. Well, even though if it may allow it I don't think we're giving good impressions to Wine with this move.

2023-07-02 12:01 UTC, binarymaster commented on boot/bootdata/CMakeLists.txt
> +add_livecd_shortcut("Minesweeper" winmine.exe "Profiles/All Users/Start Menu/Programs/Games")
If you limit the changes to only renaming the shortcuts, I think this could be acceptable.

2023-07-02 21:34 UTC, MesaBlack commented
https://www.youtube.com/watch?v=NIgfiSzCy1o

2023-07-12 10:30 UTC, closed without merging