[COMCTL32][MSHTML][QCAP][MSGINA][UXTHEME][MSHTML_WINETEST][NTGDI][NTUSER] DeleteObject(hdc...) are wrong!
reactos/reactos pull request #5344
Opened 2023-06-15 13:22 UTC by katahiromz

## Purpose

Using `DeleteObject` against a DC is totally wrong. Use `DeleteDC` instead to delete a DC.

JIRA issue: N/A

## Proposed changes

- Use `DeleteDC` instead of `DeleteObject` against DCs.

## TODO

- [x] Build.
- [ ] Big tests.

2023-06-15 13:25 UTC, HBelusca requested changes

2023-06-15 13:25 UTC, HBelusca commented on win32ss/gdi/ntgdi/dclife.c
> +        if (!IntGdiDeleteDC(hDC, FALSE))
hm you're doing a recursive call there.

2023-06-15 13:32 UTC, katahiromz commented on win32ss/gdi/ntgdi/dclife.c
> +        if (!IntGdiDeleteDC(hDC, FALSE))
Reverted.

2023-06-17 08:10 UTC, tkreuzer commented
No, it's not "totally wrong". While it's not documented, you can call DeleteObject with a DC just fine on Windows. A quick look at our implementation of DeleteObject also reveals that.
I'm fine with changing this in our own code, but not in wine, since it fixes nothing and only causes useless deviation from the original code.

2023-06-17 08:17 UTC, tkreuzer requested changes
Don't change wine code, since the "fix" doesn't actually fix anything.

2023-06-17 08:18 UTC, katahiromz commented
Sorry my half-rotten brain. My brain is weak in undocumented things. Closed.

2023-06-17 08:18 UTC, closed without merging