[GETUNAME] Update Polish (pl-PL) translation
reactos/reactos pull request #5370
Opened 2023-06-26 18:09 UTC by pithwz

[GETUNAME] Update Polish (pl-PL) translation

2023-06-28 09:42 UTC, binarymaster commented
Cc @reactos/lang-polish for review

2023-06-28 09:51 UTC, archeYR requested changes
Please revert the line ending changes.

2023-06-28 10:00 UTC, binarymaster commented
> Please revert the line ending changes.

Fixed it. Perhaps the file was edited under Linux...

2023-06-28 10:49 UTC, archeYR requested changes

2023-06-28 10:49 UTC, archeYR commented on dll/win32/getuname/lang/pl-PL.rc
> +    176 "Zmak stopnia"
```suggestion
    176 "Znak stopnia"
```

2023-06-28 10:49 UTC, archeYR commented on dll/win32/getuname/lang/pl-PL.rc
> +    8743 "Koniunkcja And"
```suggestion
    8743 "Koniunkcja"
```

2023-06-28 10:49 UTC, archeYR commented on dll/win32/getuname/lang/pl-PL.rc
> +    8744 "Alternatywa Or"
```suggestion
    8744 "Alternatywa"
```

2023-06-28 10:49 UTC, archeYR commented on dll/win32/getuname/lang/pl-PL.rc
> +    8746 "Składająca"
```suggestion
    8746 "Suma zbiorów"
```

2023-07-04 16:43 UTC, archeYR approved these changes

2023-07-07 23:22 UTC, merged