[APPWIZ] Update Romanian (ro-RO) translation
reactos/reactos pull request #5464
Opened 2023-07-20 20:01 UTC by AndreiMiloiu

2023-07-20 20:02 UTC, AndreiMiloiu commented
Cc @reactos/lang-romanian

2023-07-23 17:07 UTC, HBelusca approved these changes

2023-07-25 10:28 UTC, reactos-contributor requested changes

2023-07-25 10:28 UTC, reactos-contributor commented on dll/cpl/appwiz/lang/ro-RO.rc
> +    IDS_BROWSE_FOR_TARGET "Vă rugăm să selectați ținta comenzii rapide de mai jos:"
This is the textbook example of excessive politeness, which should be avoided ([see rule №7 from Romanian translation notes](https://github.com/reactos/reactos/blob/master/media/doc/Romanian%20translation%20notes.txt#L19)).
This principle was taken from the (Romanian) software translator's guide, that although is referenced, in the end-note list of that file, the original link is no longer valid (and should be updated). A copy of that original (rule in that) guide can be found here: [https://diacritice.sourceforge.io/ghid.html](https://diacritice.sourceforge.io/ghid.html#Polite.C8.9Bea_excesiv.C4.83)

2023-07-25 22:51 UTC, reactos-contributor approved these changes

2023-07-26 13:02 UTC, merged