[MISC] Fix typos in comments
reactos/reactos pull request #5591
Opened 2023-08-19 15:36 UTC by nfxpnk

## Purpose

Fixing typos in code comments enhances code readability and comprehension for developers and collaborators.

JIRA issue: No Jira access and no issue

## Proposed changes

Fix misc typos in comments

2023-08-19 16:10 UTC, HBelusca commented on win32ss/user/user32/controls/ghost.c
> +    // do the default behavior
```suggestion
    // do the default behaviour
```

2023-08-19 16:10 UTC, HBelusca commented on win32ss/reactx/dxg/historic.c
> +* The functions we want redirect
```suggestion
* The functions we want to redirect
```

2023-08-19 16:10 UTC, HBelusca commented on sdk/tools/mkisofs/schilytools/mkisofs/write.c
> +	/* allocate memory as a "Table" file */
3rd-party code, don't change.

2023-08-19 16:10 UTC, HBelusca commented on dll/opengl/glu32/src/libnurbs/interface/insurfeval.cc
> +  temp_em->uprime = -1;//initialized
3rd-party code, don't change.

2023-08-19 16:17 UTC, binarymaster commented on win32ss/user/user32/controls/ghost.c
> +    // do the default behavior
heh I see en-US vs. en-GB here (both are correct)

2023-08-19 16:24 UTC, binarymaster commented on win32ss/user/user32/misc/ddeclient.c
> +	 * 2/ the pConv conversation had really been disconnected
3rd party code: https://github.com/reactos/reactos/blob/56d95154eeaf2e96d5f3c6cd47baa03e50435235/media/doc/WINESYNC.txt#L338C46-L338C74

2023-08-19 19:36 UTC, JoachimHenze approved these changes
Approved. But we have to make sure, that we will not touch any 3rd party code.
@binarymaster can you check whether any of that code is 3rd party?

2023-08-19 20:18 UTC, binarymaster requested changes
Hello,
Thanks for your interest in ReactOS!
Since you have modified the files containing code, we ask our contributors [to use their full name when committing](https://github.com/reactos/reactos/blob/master/CONTRIBUTING.md#rules-and-recommendations).
[Please amend your commit with your full name](https://stackoverflow.com/a/3042512), and update this PR.

To change this for future PR's, you can update it for globally (for the system):
```
git config --global user.name "Your Name"
git config --global user.email you@example.com
```

Or just for the current repository:
```
git config user.name "Your Name"
git config user.email you@example.com
```

Also please set up your GitHub account accordingly, so maintainers can use Squash & Merge button without getting the author field modified back to nickname by GitHub - set your full name in [GitHub profile settings](https://github.com/settings/profile) (it should match your `user.name` setting).

Regards,

2023-08-20 09:12 UTC, binarymaster approved these changes

2023-08-20 09:54 UTC, learn-more approved these changes

2023-08-22 13:20 UTC, merged