[I8042prt] do not try to flush controller's input buffer.
reactos/reactos pull request #5637
Opened 2023-08-31 14:20 UTC by serrox

Do not try to flush controller's input buffer - in fact, current code will try to flush very same controller's output port that above in code, but looking to wrong status flag

As I googled about i8042 - it seems that OS has no way flush controller's input buffer. And I found that linux happy with just flushing controller's output buffer: 
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/input/serio/i8042.c?h=v6.4.13#n263

2023-08-31 14:22 UTC, HBelusca commented
Is this fixing an actual bug on virtual machines or hardware?

2023-08-31 15:25 UTC, JoachimHenze approved these changes
Deleting code gets my approval by default, unless the deletion can be proven to be wrong ofc. ;-)

2023-08-31 15:59 UTC, serrox commented
> Is this fixing an actual bug on virtual machines or hardware?

No, I found it while just looking around code. Reading from port using a wrong flag as data ready flag looks strange

2023-08-31 16:50 UTC, binarymaster requested changes
Hi, just a few things to be corrected regarding commit author field:

![image](https://github.com/reactos/reactos/assets/578406/377d5a31-a937-40ba-9920-c19f7f93d59f)

1. [ ] Make sure your first name comes first (currently it seems you specified last name as first)
1. [x] Set your full name in [GitHub profile settings](https://github.com/settings/profile) (it should match your author name from commit)

Regards,

2023-08-31 18:17 UTC, HBelusca commented
> in fact, current code will try to flush very same controller's output port that above in code, but looking to wrong status flag

Where do you see in the code, that it's going to actually flush the controller output port?

2023-09-01 12:25 UTC, serrox commented
> Hi, just a few things to be corrected regarding commit author field:
> 
> ![image](https://user-images.githubusercontent.com/578406/264716828-377d5a31-a937-40ba-9920-c19f7f93d59f.png)
> 
> 1. [ ]  Make sure your first name comes first (currently it seems you specified last name as first)
> 2. [x]  Set your full name in [GitHub profile settings](https://github.com/settings/profile) (it should match your author name from commit)
> 
> Regards,

done

2023-09-01 16:27 UTC, binarymaster commented
Reportedly there was a problem with PS/2 mouse on 86Box emulator, I wonder if this improves that somehow.

2023-09-19 14:01 UTC, tkreuzer commented
This should be tested by the "official ReactOS laptos" and other hardware before merge.

2024-02-02 01:04 UTC, closed without merging