[NTUSER] On Programmatic Move, Then Resize, Clear Normal Rectangle
reactos/reactos pull request #5685
Opened 2023-09-11 23:02 UTC by Doug-Lyons

## Purpose

_Fix Programmatic Move, then Resize followed by Move remembering old position._

JIRA issue: [CORE-19160](https://jira.reactos.org/browse/CORE-19160)

## Proposed changes

_Clear Normal Rectangle when Window opened with programmatic size followed by resize and move._

2023-09-14 19:50 UTC, whindsaks commented
Does this affect Window Snap in any way? It also uses NormalRect...

2023-09-14 20:29 UTC, Doug-Lyons commented
> Does this affect Window Snap in any way? It also uses NormalRect...

Not according to my tests, but you should test yourself and let us know your results here. Thanks.

2023-09-16 07:06 UTC, JoachimHenze approved these changes

2023-09-20 11:06 UTC, HBelusca commented
@whindsaks Since you are working on fixing Snap in your PR, have you seen any improvement in behaviour with this present PR added?

2023-09-21 16:50 UTC, whindsaks commented
@HBelusca  No but I was never able to reproduce the issue in the first place (I did not try TC). The description in the Jira issue says "right click title bar" but in the video it looks like a left click so I don't know...

2023-09-21 22:25 UTC, Doug-Lyons commented
> @HBelusca No but I was never able to reproduce the issue in the first place (I did not try TC). The description in the Jira issue says "right click title bar" but in the video it looks like a left click so I don't know...

@whindsaks, You are correct that my description was wrong in saying "right click", so I have fixed it now by saying "left click and hold on its title bar". Using Total Commander is necessary, because it is what executes the programmatic 'move and resize' which triggers the bad behavior. Thanks.

2023-10-16 15:42 UTC, binarymaster commented
Are there any fixed tests? If not, would be nice to add an API test for this.

2024-02-14 06:40 UTC, Doug-Lyons commented
> Are there any fixed tests? If not, would be nice to add an API test for this.

@binarymaster, Unfortunately, there are not any fixed tests after applying this PR. Adding an API test for this is beyond my capabilities at this time. From what I see, it would require creating a minimal application EXE that performed the resize on start up and embedding this inside the test. The API test must them execute this EXE and then very specific mouse commands and maybe then check the window's height and width. Both @julenuri and @JoachimHenze have successfully tested this PR's benefits and I have included the instructions to test it in the Jira ticket and also included a video showing the problem.. It has one approval and has been over two weeks, so by the Pull Request Management guidelines, it should be ready for committing. Thanks.

2024-03-29 17:56 UTC, JoachimHenze commented
This PR is unfortunately not fully solving the regression that it intends to fix. Here is a very simple testcase that is still not handled properly, and that is with 99.9999999% caused by the same guilty revision, which @Doug-Lyons s PR actually intends to appease: Please see this video, where you can still see with a very simple testcase (using only notepad) that we still have cases where it misbehaves:
[video-2024-03-29T17-49-40-812500000Z.webm](https://github.com/reactos/reactos/assets/33393466/63128520-a6a2-4fc4-8e67-459b68b05452)
It misbehaves with Dougs PR (that is what I tested here), **but it also misbehaves in the same way without Dougs PR**.

My favored solution is still to revert the guilty-revision which intended to "improve the Window-snapping during 0.4.15-dev'ing" entirely and just return to the state that I do currently have implemented within releases/0.4.14.

This bug is affected the usability of ros to such an extend, that I find it breathtaking that others here seem to not be aware of reproduction-steps. This bug is absolutely omnipresent when dealing with Windows in master head. It is a mysery.
See another video where it hit me unintentionally, (that was without Dougs patch though):
https://jira.reactos.org/secure/attachment/67671/67671_0.4.15-dev-7842-g558ab78_drawingDirtInStatusbar.webm
Just mentioning that here because it is an additional testcase. (see me in the video how I am pissed off when I try to restore the window from maximized state)

Unless Doug can improve the PR further to cover all those cases, I do vote for reverting the guilty:
https://github.com/reactos/reactos/commit/669b2f4465f0f5e3dac177e46865058fae0b1179
instead.

2024-03-29 17:59 UTC, JoachimHenze requested changes
Still favoring the plain revert instead of this PR. PR would need to be improved to cover the regression to 100%.
Still thank you very much for your perseverance in cleaning up the mess others did introduce. I do appreciate your amount of personal engagement.

2024-08-11 01:26 UTC, closed without merging

2024-08-11 19:59 UTC, Doug-Lyons commented
Superseded by https://github.com/reactos/reactos/pull/5705 .