[SDK] Improve IsReactOS function
reactos/reactos pull request #5733
Opened 2023-09-26 12:34 UTC by katahiromz

## Purpose

Implement a accurate version check helper.
JIRA issue: N/A

## Proposed changes

- Use registry to check the OS.

## TODO

- [ ] Do build.

2023-09-26 14:34 UTC, HBelusca requested changes
This won't work because this relies on an optional binary we include only if the rosapps subdir is compiled (which it is not by default, e.g. in the test builds).

2023-09-27 01:05 UTC, whindsaks commented
For the moment, checking if system32\kernel32_vista.dll exists on disk is probably enough?

Checking the company name in the version info of kernel32.dll is probably better. If that is too slow, an exported custom function could be added to kernel32.dll? 

Wine has `wine_get_version` in ntdll...

2023-09-27 09:57 UTC, HBelusca commented
> For the moment, checking if system32\kernel32_vista.dll exists on disk is probably enough?
> 
> Checking the company name in the version info of kernel32.dll is probably better. If that is too slow, an exported custom function could be added to kernel32.dll?
> 
> Wine has `wine_get_version` in ntdll...

Please see the review comments in this PR first: https://github.com/reactos/reactos/pull/4411

2023-09-27 10:35 UTC, katahiromz commented
Used `SHGetValueW`.

2023-09-27 17:17 UTC, whindsaks commented on sdk/include/psdk/versionhelpers.h
> +typedef DWORD (WINAPI FN_SHGetValueW(HKEY hKey, LPCWSTR lpszSubKey, LPCWSTR lpszValue,
This "leaks" the function type to global scope. Declare it inside the function...

2023-09-27 22:06 UTC, closed without merging