[DEVMGR] Added copy popup menu
reactos/reactos pull request #5775
Opened 2023-10-08 17:03 UTC by Oplkill

In driver properties, in details tab - added popup menu with "copy" element for listview

## Purpose

This will allow to copy driver's information to buffer.

2023-10-09 14:15 UTC, HBelusca submitted a review, later dismissed
Can you show us a picture how this new menu appears?

2023-10-09 14:15 UTC, HBelusca commented on dll/win32/devmgr/properties/advprop.cpp
> +                    if (LoadString(hDllInstance, IDS_COPY, szColName, sizeof(szColName) / sizeof(szColName[0])))
```suggestion
                    if (LoadStringW(hDllInstance, IDS_COPY, szColName, _countof(szColName)))
```

2023-10-09 14:15 UTC, HBelusca commented on dll/win32/devmgr/properties/advprop.cpp
> +                    DestroyMenu(hPopup);
You create the menu above, but then do the track-menu thing only if the LoadString call succeeded.
Wouldn't it be better to create/track/destroy it  instead _only_ if the LoadString call succeeded?
Alternatively, what would happen instead if you keep the code as it currently is, except that you call the TrackPopupMenu _outside_ of the `if (LoadString(...))` block (and just before calling DestroyMenu)?

2023-10-09 14:15 UTC, HBelusca commented on dll/win32/devmgr/properties/advprop.cpp
> +                }
There is a `break;` missing in there.

2023-10-09 14:15 UTC, HBelusca commented on dll/win32/devmgr/properties/advprop.cpp
> +                    break;
```suggestion
                        break;
                    }
```

2023-10-09 14:36 UTC, Oplkill commented
> Can you show us a picture how this new menu appears?

![image](https://github.com/reactos/reactos/assets/7405630/f5c9749d-4947-4747-aea7-ad9e60cad596)

Just simple popup menu(or how it calls too - context menu) with only one element - "Copy". That menu will appears on right click mouse button in listview

2023-10-09 14:39 UTC, HBelusca commented
> > Can you show us a picture how this new menu appears?
> 
> ![image](https://user-images.githubusercontent.com/7405630/273617315-f5c9749d-4947-4747-aea7-ad9e60cad596.png)
> 
> Just simple popup menu(or how it calls too - context menu) with only one element - "Copy". That menu will appears on right click mouse button in listview

Ah great, OK, so if that menu just have one and only one item "Copy", then I guess, regarding my comment about LoadString + menu creation, that you could create the menu only if the LoadString call succeeds, otherwise not doing anything.

2023-10-09 15:00 UTC, Oplkill commented
> > Just simple popup menu(or how it calls too - context menu) with only one element - "Copy". That menu will appears on right click mouse button in listview
> 
> Ah great, OK, so if that menu just have one and only one item "Copy", then I guess, regarding my comment about LoadString + menu creation, that you could create the menu only if the LoadString call succeeds, otherwise not doing anything.

Fixed it

2023-10-09 15:33 UTC, HBelusca commented on dll/win32/devmgr/properties/advprop.cpp
> +                        GetCursorPos(&pt);
Normally the coordinates are passed via the lParam, retrieved via e.g.
```
xPos = GET_X_LPARAM(lParam); 
yPos = GET_Y_LPARAM(lParam); 
```

2023-10-09 15:35 UTC, HBelusca commented on dll/win32/devmgr/properties/advprop.cpp
> +                    if (LoadStringW(hDllInstance, IDS_COPY, szColName, _countof(szColName)))
Note (optional): you could reduce the indentation level by doing:
```c
                    if (!LoadStringW(hDllInstance, IDS_COPY, szColName, _countof(szColName)))
                        break;
```
then continue with the original code as done below.

2023-10-09 15:36 UTC, HBelusca commented on dll/win32/devmgr/properties/advprop.cpp
> +                        if (nSelectedId >= 0 && nSelectedItems > 0)
Same comment regarding the indentation here too.

2023-10-09 15:37 UTC, HBelusca commented on dll/win32/devmgr/properties/advprop.cpp
> +                            wsprintfW(pszBuffer, L"%s", szItemName);
```suggestion
                            wsprintf(pszBuffer, L"%s", szItemName);
```
or use a StringSafe function instead.

2023-10-09 15:38 UTC, HBelusca commented on dll/win32/devmgr/properties/advprop.cpp
> +                            if (pszBuffer == NULL)
```suggestion
                            if (!pszBuffer)
```

2023-10-09 15:42 UTC, HBelusca commented on dll/win32/devmgr/properties/advprop.cpp
> +                            hGlobal = GlobalAlloc(GHND, MAX_PATH);
```suggestion
                            hGlobal = GlobalAlloc(GHND, MAX_PATH);
                            if (!hGlobal)
                                return Ret;
```

2023-10-09 16:55 UTC, binarymaster commented
> Just simple popup menu (or how it calls too - context menu) with only one element - "Copy"

On Windows there's a second menu entry "Select all", so the copy operation should be able to work on multiline selection.

2023-10-09 17:24 UTC, JoachimHenze approved these changes
A useful feature. Approved.
It could be made simpler (without requiring any rc changes or LoadString-calls) if we invoked the copy by the pure right-click already, but that would be a bit less self-explanationary, I guess. And people might miss then that we do actually support such a thing.
So I do assume that the cost-benefit-ratio is still ok, in the way that you did.

2023-10-10 11:30 UTC, HBelusca approved these changes

2023-10-10 11:33 UTC, HBelusca commented
Oh, by the way @Oplkill , please read that first: https://github.com/reactos/reactos/blob/master/CONTRIBUTING.md#rules-and-recommendations

2023-10-10 13:30 UTC, binarymaster requested changes
Hello,
Thanks for your interest in ReactOS!
We ask our contributors [to use their full name when committing](https://github.com/reactos/reactos/blob/master/CONTRIBUTING.md#rules-and-recommendations).
[Please amend your commit with your full name](https://stackoverflow.com/a/3042512), and update this PR.

To change this for future PR's, you can update it for globally (for the system):
```
git config --global user.name "Your Name"
git config --global user.email you@example.com
```

Or just for the current repository:
```
git config user.name "Your Name"
git config user.email you@example.com
```

Also please set up your GitHub account accordingly, so maintainers can use Squash & Merge button without getting the author field modified back to nickname by GitHub:

- Set your full name in [GitHub profile settings](https://github.com/settings/profile) (it should match your `user.name` setting)

Regards,

2023-10-10 15:09 UTC, binarymaster commented on dll/win32/devmgr/lang/de-DE.rc
> +    IDS_COPY "Kopieren"
Some menu items have mnemonic keys (&) assigned, but some don't.

2023-10-10 15:20 UTC, binarymaster commented on dll/win32/devmgr/lang/de-DE.rc
> +    IDS_COPY "Kopieren"
You can copy from notepad's `CMD_COPY`: https://git.reactos.org/?p=reactos.git&a=search&h=HEAD&st=grep&s=CMD_COPY

2023-10-10 15:37 UTC, JoachimHenze approved these changes

2023-10-10 15:47 UTC, binarymaster approved these changes

2023-10-10 16:16 UTC, HBelusca approved these changes

2023-10-10 19:22 UTC, merged

2023-10-12 13:05 UTC, ThFabba commented
@HBelusca @binarymaster can you please be a little more diligent with your code review? This should not have been merged.
Brand new code that
* uses TCHARs in a completely broken way
* has an obvious heap buffer overflow
* uses an unsafe string function
is not the standard we want to set.

2023-10-12 13:23 UTC, HBelusca commented
I'm going to submit a fix PR for this @ThFabba

2023-10-12 13:25 UTC, ThFabba commented
Thanks @HBelusca! Here's what I was going to propose, but I haven't had a chance to test it yet or anything: https://github.com/ThFabba/reactos/commit/e9a8a4b470f58b6ab7d35ef8758e3838b30b1358

2023-10-12 13:38 UTC, HBelusca commented
@ThFabba See PR #5790