** WIP ** [PSDK] Add PathCch* functions from Wine.
reactos/reactos pull request #5842
Opened 2023-10-27 13:51 UTC by HBelusca

## Purpose

JIRA issue: [CORE-12686](https://jira.reactos.org/browse/CORE-12686)

Better header than Wine's own (supersedes PR #5287)

## TODO

- [ ] These must be compiled into a pathcch.lib library as it is in the official PSDK (with the exception that here, the actual implementation of these functions would be linked, instead of a link to an apiset DLL).
- [ ] Fix build?

2023-10-27 14:01 UTC, katahiromz commented
```txt
// CMakeLists.txt
list(APPEND SOURCE
    ...
    )

add_library(pathcch STATIC ${SOURCE})
target_include_directories(pathcch PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})

add_dependencies(pathcch psdk)
add_pch(pathcch precomp.h SOURCE)
```

2023-10-30 14:55 UTC, HBelusca commented on sdk/lib/pathcch/pathcch.c
> +    #define wcsnicmp _wcsnicmp
This should be solved by linking with `oldnames` library.

2023-10-30 14:55 UTC, HBelusca commented on sdk/lib/pathcch/pathcch.c
> +    _In_ SIZE_T size)
Please revert, those are `size_t` in small case (and since this is inside the `#ifdef __REACTOS__` part, let's keep it correct).

2023-10-30 14:55 UTC, HBelusca commented on sdk/lib/pathcch/pathcch.h
> +#endif // __cplusplus
Why has this file been completely rewritten? Please fix it

2023-10-30 14:57 UTC, HBelusca commented
OK I will take this PR back.

2023-10-30 16:17 UTC, HBelusca commented
Changes:
- CMakeFiles.txt has been dramatically simplified (follows those of other win32 libs we have);
- The "Delete unneeded (deprecated) code" commit has been kept;
- I've reverted the "Delete some semicolons for #define" and "Improve deprecated redirection name".

The reasons are: 1. keep compatibility with MS PSDK header, and 2. the deprecated redirection names use the same naming scheme as in the (nt)strsafe.h headers, so we don't need more unrelated changes.

2023-10-30 22:03 UTC, katahiromz approved these changes

2023-10-30 22:05 UTC, HBelusca commented
@katahiromz thanks; as I've asked in the corresponding JIRA report, could you try using these pathcch functions in a test program (compiled within ReactOS source tree) to see whether the library correctly links and the header is OK?

2023-10-31 06:15 UTC, katahiromz commented
See  https://jira.reactos.org/browse/CORE-12686

2023-10-31 11:51 UTC, HBelusca commented
OK so:
- code uses NT6+ non-exported `wcsnlen` function (work-around: `StringCchLengthW`);
- wine also uses lstrlenW on other such similar buffers (that are in principle null-terminated but specified by their size...): wine code "kwality"

2023-10-31 13:54 UTC, katahiromz requested changes
I request a workaround on `wcsnlen`.

2023-10-31 18:17 UTC, HBelusca commented
> I request a workaround on `wcsnlen`.

Yep! I'm going to fix that tomorrow.

2023-11-25 09:47 UTC, katahiromz commented
```c
#ifdef __REACTOS__
    /* The PathCch functions use size_t, but Wine's implementation uses SIZE_T,
     * so temporarily change the define'd SIZE_T type to the compatible one... */
    #undef SIZE_T
    #define SIZE_T size_t

    /* wcsnlen is NT6+ non-exported function. We need a HACK. */
    static inline size_t hacked_wcsnlen(LPCWSTR str, SIZE_T size)
    {
        StringCchLengthW(str, size, &size);
        return size;
    }
    #define wcsnlen hacked_wcsnlen
#endif
```
Let's go with this.

2023-11-25 10:42 UTC, HBelusca commented
> Let's go with this.

OK I'm going to add this and rerun the buildbots on the PR.

2023-11-25 14:09 UTC, HBelusca commented
@katahiromz Can you confirm that the wcsnlen was the only function that required an extra "hack"? (and so that, now, your test-example from the JIRA report correctly compiles fine?)

2023-11-25 22:41 UTC, katahiromz approved these changes
Tested with `shell32-quick-test-1.patch`.
It's successful. Let's go.

2023-11-26 12:44 UTC, merged