[MSPAINT] Update Romanian (ro-RO) translation
reactos/reactos pull request #5913
Opened 2023-11-07 22:33 UTC by AndreiMiloiu

Attendum to PR https://github.com/reactos/reactos/pull/5908

2023-11-07 22:33 UTC, AndreiMiloiu commented
Cc @reactos/lang-romanian for review

2023-11-08 10:30 UTC, JoachimHenze requested changes

2023-11-08 10:30 UTC, JoachimHenze commented on base/applications/mspaint/lang/ro-RO.rc
> +        MENUITEM "Sal&vează ca...", IDM_FILESAVEAS
Accelerator &v collides with
 MENUITEM "Pre&vizionează pagina", IDM_FILEPAGEVIEW
in the same menu.

2023-11-08 10:30 UTC, JoachimHenze commented on base/applications/mspaint/lang/ro-RO.rc
> +        MENUITEM "S&alvează\tCtrl+S", IDM_FILESAVE
Accelerator &a collides with
 MENUITEM "Decor de birou (în c&arou)", IDM_FILEASWALLPAPERPLANE
in the same menu.

2023-11-08 19:01 UTC, merged