[SETUPAPI] cfgmgr.c: Use WideCharToMultiByte(WideCharCount=-1)
reactos/reactos pull request #6028
Opened 2023-11-22 05:33 UTC by SergeGautherie

when actual string length is unknown, not the full buffer length.

## Purpose

Consistency.

Follow-up to #5943.

## Proposed changes

- Use WideCharToMultiByte(WideCharCount=-1)

2023-11-22 07:17 UTC, SergeGautherie commented
"Usual"
`fatal error C1051: program database file, 'D:\a\reactos\reactos\build\modules\rostests\apitests\user32\CMakeFiles\user32_apitest.dir\vc140.pdb', has an obsolete format, delete it and recompile`

2024-03-25 12:02 UTC, HBelusca approved these changes

2024-03-25 14:31 UTC, TAN-Gaming requested changes

2024-03-25 14:31 UTC, TAN-Gaming commented on dll/win32/setupapi/cfgmgr.c
> +                            -1,
The same as `CM_Get_Device_ID_List_ExA`.

2024-03-27 01:35 UTC, TAN-Gaming commented on dll/win32/setupapi/cfgmgr.c
> +                                             ulLengthW,
```suggestion
                                             ulLengthW / sizeof(WCHAR),
```

2024-03-27 01:35 UTC, TAN-Gaming commented on dll/win32/setupapi/cfgmgr.c
> +                                             LengthW,
```suggestion
                                             LengthW / sizeof(WCHAR),
```

2024-08-09 01:05 UTC, closed without merging