[COMCTL32] Ignore next mouse move after double-click in edit control
reactos/reactos pull request #6368
Opened 2024-01-15 00:50 UTC by Doug-Lyons

## Purpose
_Patch from @KRosUser based on a patch by me._
_In comctl32 edit box fix word selection when mouse double-click is used ._

JIRA issue: [CORE-19422](https://jira.reactos.org/browse/CORE-19422)
and
JIRA issue: [CORE-19423](https://jira.reactos.org/browse/CORE-19423)

## Proposed changes

_When using the edit control in comctl32 when mouse single-click or double-click is used,_
_ignore the next mouse move event to fix word selection._

2024-01-17 15:34 UTC, HBelusca approved these changes
adding "HACK:" tags so that we know what these really are.

2024-01-17 15:34 UTC, HBelusca commented on dll/win32/comctl32/edit.c
> +    /* set flags indicating WM_MOUSEMOVE to be ignored due to CORE-8394 */
```suggestion
    /* HACK: set flags indicating WM_MOUSEMOVE to be ignored due to CORE-8394 */
```

2024-01-17 15:34 UTC, HBelusca commented on dll/win32/comctl32/edit.c
> +    /* set flags indicating WM_MOUSEMOVE to be ignored due to CORE-8394 */
```suggestion
    /* HACK: set flags indicating WM_MOUSEMOVE to be ignored due to CORE-8394 */
```

2024-01-17 15:34 UTC, HBelusca commented on dll/win32/comctl32/edit.c
> +            /* clear flags indicating WM_MOUSEMOVE to be ignored due to CORE-8394 */
```suggestion
            /* HACK: clear flags indicating WM_MOUSEMOVE to be ignored due to CORE-8394 */
```

2024-01-17 16:01 UTC, Doug-Lyons commented on dll/win32/comctl32/edit.c
> +    /* set flags indicating WM_MOUSEMOVE to be ignored due to CORE-8394 */
Fixed. Thanks.

2024-01-17 16:01 UTC, Doug-Lyons commented on dll/win32/comctl32/edit.c
> +            /* clear flags indicating WM_MOUSEMOVE to be ignored due to CORE-8394 */
Fixed. Thanks.

2024-01-18 21:39 UTC, learn-more commented
Why are we adding hacks for this?
As long as this does not cause major breakage I'd actually prefer to leave it in broken state, otherwise we have to hunt our codebase for all hacks after each ticket that is fixed.

2024-04-30 16:21 UTC, DarkFire01 requested changes
At the very least let's wait to see how syncing comctl32 to wine 9.7 effects things, 
not a big fan of adding hacks while we're not update to date in master

2025-01-14 06:19 UTC, Doug-Lyons commented
Superseded by PR #6397.

2025-01-14 06:19 UTC, closed without merging