[CMAKE] Clang*: Add '-Werror=unknown-warning-option' for C/CXX
reactos/reactos pull request #6383
Opened 2024-01-18 00:19 UTC by SergeGautherie

## Purpose

Cleaner Clang* builds: Reduce warning number, prevent new cases.

## Proposed changes

- Fix the 4 cases.
- Add '-Werror=unknown-warning-option' for C/CXX

2024-01-18 10:59 UTC, HBelusca requested changes

2024-01-18 10:59 UTC, HBelusca commented on sdk/cmake/msvc.cmake
> +    if((TYPE STREQUAL "win32dll") OR (TYPE STREQUAL "win32ocx") OR (TYPE STREQUAL "cpl"))
These changes are not necessary.

2024-01-18 22:37 UTC, SergeGautherie commented on sdk/cmake/msvc.cmake
> +    if((TYPE STREQUAL "win32dll") OR (TYPE STREQUAL "win32ocx") OR (TYPE STREQUAL "cpl"))
Reverted.

2024-01-20 13:58 UTC, HBelusca approved these changes

2024-05-20 14:24 UTC, SergeGautherie commented
Approved 4 months ago. Ready to commit?

2024-05-30 22:58 UTC, cbialorucki approved these changes

2024-05-31 14:26 UTC, merged