[MMSYS] Update Romanian (ro-RO) translation
reactos/reactos pull request #6510
Opened 2024-02-20 23:24 UTC by AndreiMiloiu

2024-02-20 23:24 UTC, AndreiMiloiu commented
Cc @reactos/lang-romanian

2024-02-28 22:14 UTC, JoachimHenze requested changes

2024-02-28 22:14 UTC, JoachimHenze commented on dll/cpl/mmsys/lang/ro-RO.rc
> +    LTEXT "Configurarea difuzoarelor:", 8502, 53, 169, 55, 10
This text is way too long to fit the control of 55 units width. Do a screenshot to see it yourself!

2024-06-23 08:05 UTC, AndreiMiloiu commented
Any news?

2024-07-16 18:11 UTC, merged