[RASDLG] Update Romanian (ro-RO) translation
reactos/reactos pull request #6537
Opened 2024-02-25 10:51 UTC by AndreiMiloiu

Attendum to https://github.com/reactos/reactos/pull/6517

2024-02-25 10:51 UTC, AndreiMiloiu commented
Cc @reactos/lang-romanian

2024-02-25 13:35 UTC, JoachimHenze requested changes
Do not merge that PR, it breaks much more regarding the accelerators than it improves things with the translations.

2024-02-25 13:35 UTC, JoachimHenze commented on dll/win32/rasdlg/lang/ro-RO.rc
> +    DEFPUSHBUTTON "&OK", 1, 127, 232, 60, 14
This change introduces an accelerator collision with the line
 AUTOCHECKBOX "Micr&osoft CHAP versiunea 2 (MS-CHAP v2)", 1492, 28, 176, 200, 10, BS_TOP | BS_MULTILINE
Please check your romanian Windows to find out which of both lines need to be changed.

2024-02-25 13:35 UTC, JoachimHenze commented on dll/win32/rasdlg/lang/ro-RO.rc
> +    PUSHBUTTON "&Revocare", 2, 192, 232, 60, 14
This change introduces an accelerator collision with the line
  PUSHBUTTON "P&roprietăți", 1035, 184, 77, 60, 14
Please check your romanian Windows to find out which of both lines need to be changed.

2024-02-25 13:35 UTC, JoachimHenze commented on dll/win32/rasdlg/lang/ro-RO.rc
> +    PUSHBUTTON "&Revocare", 2, 191, 147, 60, 14
This change introduces an accelerator collision with the line
 LTEXT "Codul &regiunii:", 1055, 18, 17, 54, 8
Please check your romanian Windows to find out which of both lines need to be changed.

2024-02-25 13:35 UTC, JoachimHenze commented on dll/win32/rasdlg/lang/ro-RO.rc
> +    PUSHBUTTON "&Revocare", 2, 164, 85, 60, 14
This change introduces an accelerator collision with the line
 LTEXT "Int&roduceți numărul de telefon al modemului dumneavoastră:", 1067, 5, 46, 222, 8, NOT WS_GROUP
Please check your romanian Windows to find out which of both lines need to be changed.

2024-02-25 13:35 UTC, JoachimHenze commented on dll/win32/rasdlg/lang/ro-RO.rc
> +    PUSHBUTTON "&Revocare", 1591, 70, 103, 60, 14
This change introduces an accelerator collision with the line
 PUSHBUTTON "&Reguli de apel", 1108, 181, 75, 72, 14
Please check your romanian Windows to find out which of both lines need to be changed.

2024-02-25 13:35 UTC, JoachimHenze commented on dll/win32/rasdlg/lang/ro-RO.rc
> +    PUSHBUTTON "&Revocare", 1591, 71, 173, 60, 14
This change introduces an accelerator collision with the line below
 PUSHBUTTON "P&roprietăți", 1107, 133, 173, 60, 14
Please check your romanian Windows to find out which of both lines need to be changed.

2024-02-25 13:35 UTC, JoachimHenze commented on dll/win32/rasdlg/lang/ro-RO.rc
> +    PUSHBUTTON "&Revocare", 1591, 72, 199, 60, 14
This change introduces an accelerator collision with the line below
PUSHBUTTON "P&roprietăți", 1107, 134, 199, 60, 14
Please check your romanian Windows to find out which of both lines need to be changed.

2024-02-25 13:35 UTC, JoachimHenze commented on dll/win32/rasdlg/lang/ro-RO.rc
> +    PUSHBUTTON "&Revocare", 1591, 72, 180, 60, 14
This change introduces an accelerator collision with the line below
PUSHBUTTON "P&roprietăți", 1107, 134, 180, 60, 14
Please check your romanian Windows to find out which of both lines need to be changed.

2024-02-25 13:35 UTC, JoachimHenze commented on dll/win32/rasdlg/lang/ro-RO.rc
> +    PUSHBUTTON "&Revocare", 2, 164, 189, 60, 14
This change introduces an accelerator collision with the line
 LTEXT "&Rețea:", 1410, 9, 35, 213, 8, NOT WS_GROUP
Please check your romanian Windows to find out which of both lines need to be changed.

2024-02-25 13:35 UTC, JoachimHenze commented on dll/win32/rasdlg/lang/ro-RO.rc
> +    PUSHBUTTON "&Revocare", 1591, 69, 136, 60, 14
This change does introduce an accelerator collision with the line
PUSHBUTTON "&Reguli de apel", 1108, 193, 110, 64, 14
Check your Romanian Windows to find out which one needs to be changed.

2024-02-25 13:35 UTC, JoachimHenze commented on dll/win32/rasdlg/lang/ro-RO.rc
> +    PUSHBUTTON "&Revocare", 1591, 71, 221, 60, 14
Accelerator collision vs.
PUSHBUTTON "P&roprietăți", 1107, 134, 221, 60, 14
Check your Romanian Windows to find out which to change.

2024-02-25 13:35 UTC, JoachimHenze commented on dll/win32/rasdlg/lang/ro-RO.rc
> +    PUSHBUTTON "&Revocare", 2, 197, 169, 60, 14
Accelerator collision &R vs.
 AUTOCHECKBOX "Pe&rmite calculatorului apelator specificarea unei adrese IP proprii", 7022, 20, 144, 231, 10, BS_TOP | BS_MULTILINE | WS_GROUP
Check your Romanian Windows to find out which to change.

2024-02-25 13:47 UTC, AndreiMiloiu commented
I fixed them! I hope it's good now.

2024-02-28 21:56 UTC, JoachimHenze commented on dll/win32/rasdlg/lang/ro-RO.rc
> +    7354 "Un utilizator șters va fi eliminat definitiv din sistem, chiar dacă va fi apăsat Revocare. Sigur doriți eliminarea irevocabilă a utilizatorului %s? \0"
```suggestion
    7354 "Un utilizator șters va fi eliminat definitiv din sistem, chiar dacă va fi apăsat Revocare. Sigur doriți eliminarea irevocabilă a utilizatorului %s?\0"
```

2024-03-09 21:18 UTC, AndreiMiloiu commented
I'm ready. I corrected every mistake I discovered. Now everything is like in MSDN, except the three dot which are only on character long. However, I don't understand why do I have errors? However, at 102, 155, 554 the text cannot fit in the buttons. Shouldn't it be fixed by a new PR? I can open a ticket for it. The problem persists in XP, as I attached some screnshots.

![2024-03-09 23_17_43-Resource Hacker - rasdlg dll mui](https://github.com/reactos/reactos/assets/113553683/3f90a9bf-3218-4044-b153-ef755b63879a)

![2024-03-09 23_17_58-Resource Hacker - rasdlg dll mui](https://github.com/reactos/reactos/assets/113553683/2efe3fbb-b15b-4c17-9393-8b0325321267)

![2024-03-09 23_17_16-](https://github.com/reactos/reactos/assets/113553683/76bf7dfd-7b68-4348-beae-cdb888140df4)

2024-03-12 13:16 UTC, binarymaster commented on dll/win32/rasdlg/lang/ro-RO.rc
> +    198 "Imposibil de încărcat DLL-ul de configurare pentru autorizare particularizată. Asiguraţi-vă că pachetul de autorizare particularizată este corect instalat.\00"
```suggestion
    198 "Imposibil de încărcat DLL-ul de configurare pentru autorizare particularizată. Asiguraţi-vă că pachetul de autorizare particularizată este corect instalat.\0"
```

2024-03-12 13:16 UTC, binarymaster commented on dll/win32/rasdlg/lang/ro-RO.rc
> +    203 "IPX neinstalat sau dezactivat pentru Distribuire şi acces la distanţă. Instalaţi/activaţi IPX vizualizând proprietăţile fiecărei conexiuni din folderul \"Conexiuni\".\0"
```suggestion
    203 "IPX neinstalat sau dezactivat pentru Distribuire şi acces la distanţă. Instalaţi/activaţi IPX vizualizând proprietăţile fiecărei conexiuni din folderul ""Conexiuni"".\0"
```

2024-03-12 13:16 UTC, binarymaster commented on dll/win32/rasdlg/lang/ro-RO.rc
> +    199 "Conexiunea selectată a fost stabilită de distribuitorul multi-protocol.\nUtilizaţi instrumentul 'Administrare distribuire şi RAS' pentru a suspenda conexiunea.\0"
```suggestion
    199 "Conexiunea selectată a fost stabilită de distribuitorul multi-protocol.\nUtilizaţi instrumentul ""Administrare distribuire şi RAS"" pentru a suspenda conexiunea.\0"
```

2024-03-12 13:16 UTC, binarymaster commented on dll/win32/rasdlg/lang/ro-RO.rc
> +    408 "Aţi ales să dezactivaţi unul sau mai multe transporturi. Pentru aceasta se cere ca managerii de distribuire şi protocoalele de distribuire pentru transporturile dezactivate să fie eliminate
Please double check, something odd here with "\n\n\n\n ..."

2024-03-12 13:16 UTC, binarymaster commented on dll/win32/rasdlg/lang/ro-RO.rc
> +    411 "Este necesar să stabiliţi acreditările pentru apeluri dinspre interior pe care le va utiliza interfaţa '%1' când se conectează la distribuitorul la distanţă. Aceste acreditări trebuie să se
Same here.

2024-03-12 13:16 UTC, binarymaster commented on dll/win32/rasdlg/lang/ro-RO.rc
> +    588 "Numele de intrare începe cu un punct sau conţine caractere incorecte. \nAlegeţi alt nume.\0"
```suggestion
    588 "Numele de intrare începe cu un punct sau conţine caractere incorecte.\nAlegeţi alt nume.\0"
```

2024-03-12 13:16 UTC, binarymaster commented on dll/win32/rasdlg/lang/ro-RO.rc
> +    1612 "Aţi selectat utilizarea unei chei pre-distribuite dar nu aţi introdus nici una. \nIntroduceţi cheia pre-distribuită.\0"
```suggestion
    1612 "Aţi selectat utilizarea unei chei pre-distribuite dar nu aţi introdus nici una.\nIntroduceţi cheia pre-distribuită.\0"
```

2024-06-01 10:35 UTC, AndreiMiloiu commented
Any news?

2024-07-16 18:20 UTC, merged