Some fixes for "The Laste Knovvne Goode" LKG configuration support
reactos/reactos pull request #6565
Opened 2024-03-01 21:26 UTC by HBelusca

## Purpose

Enhance little aspects of Last-Known-Good configuration support.

In particular:
- Winlogon, via msgina.dll, [notifies with `NotifyBootConfigStatus()` the Services Control Manager (SCM)](https://learn.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-notifybootconfigstatus) that the current boot configuration should be good, when the first user logs in.
- The SCM notification function should check that the caller has the correct rights.
- Once the SCM successfully deals with the `HKLM\SYSTEM` Control Sets, it calls `NtInitializeRegistry()` with the (offset) index of the good control set. It is the SCM that does that call, not Winlogon.
- Note that currently, the control-set specific handler called by `NtInitializeRegistry()` is not yet implemented in ReactOS.
- The SCM should correctly delete the old control set keys, besides deleting their values and subkeys.

2024-05-18 00:39 UTC, wjk requested changes

2024-05-18 00:39 UTC, wjk commented on base/system/services/controlset.c
> +__debugbreak();
If this PR is not a draft, shouldn’t this be removed?

2024-05-18 00:39 UTC, wjk commented on base/system/services/controlset.c
> +__debugbreak();
Ditto.

2024-05-18 00:39 UTC, wjk commented on base/system/services/controlset.c
> +__debugbreak();
Ditto.

2025-03-24 15:04 UTC, DarkFire01 commented
This PR is clearly still WIP, and seeing as its seemingly abandoned i will close for now. Please Reopen when you wish to continue this :)

2025-03-24 15:04 UTC, closed without merging