[SHELL32] pl-PL.rc: Fix IDD_FILE_PROPERTIES & IDD_FOLDER_PROPERTIES
reactos/reactos pull request #6678
Opened 2024-03-27 15:56 UTC by JoachimHenze

- This removes an ancient polish-only workaround/extrawurst which made the dialog bigger than allowed in y, and which reduced its usability on small monitor resolution.
- Sync the dialogs dimensions back to en-US and all other localizations.
- Maximizes the available space for the dynamic parts of the dialog on the right side. Historically even 160 turned out to be too short for that, e.g. EDITTEXT 14009, the dynamic part of "Lokalizacja:". Therefore we used 170 everywhere for those widths in all other languages. But due to the polish workaround it was crippled to 155 here. Not good!
- Notice also how now the leftmost checkboxes position of the Attributes is perfectly aligned with the other dynamic content of that column above. This will be important in the future when we will restore the vertical layout of Attribute-checkboxes in IDD_FOLDER_PROPERTIES

JIRA issue: none

The dialog 8 before the fix:
![old_dlg8](https://github.com/reactos/reactos/assets/33393466/159dd4af-c626-4727-b122-473c71cd66f8)

The dialog 9 before the fix:
![old_dlg9](https://github.com/reactos/reactos/assets/33393466/6ab41c61-22fc-4c8b-a4b6-f79341633ca4)

The dialog 8 before after the fix:
![new_dlg8](https://github.com/reactos/reactos/assets/33393466/cd768ee2-3b00-44e8-97c7-7d2e31a81029)

The dialog 9 before after the fix:
![new_dlg9](https://github.com/reactos/reactos/assets/33393466/d04eb5d9-28f3-408b-916e-df04d2fbc181)

2024-03-27 16:01 UTC, JoachimHenze commented
Let me know if you know any native polish speaker in github for review.

2024-03-27 16:13 UTC, binarymaster commented
Cc @reactos/lang-polish

2024-03-27 17:42 UTC, archeYR requested changes

2024-03-27 17:42 UTC, archeYR commented on dll/win32/shell32/lang/pl-PL.rc
> +    LTEXT "Programy:", 14006, 8, 53, 50, 10
```suggestion
    LTEXT "Program:", 14006, 8, 53, 50, 10
```
Singular form.

2024-03-27 17:42 UTC, archeYR commented on dll/win32/shell32/lang/pl-PL.rc
> +    LTEXT "Zmieniono:", 14016, 8, 147, 45, 10
```suggestion
    LTEXT "Zmieniony:", 14016, 8, 147, 45, 10
```
For consistency with other fields.

2024-03-27 17:44 UTC, JoachimHenze commented on dll/win32/shell32/lang/pl-PL.rc
> +    LTEXT "Zmieniono:", 14016, 8, 147, 45, 10
Agreed, and applied. Resolved.

2024-03-27 17:45 UTC, JoachimHenze commented on dll/win32/shell32/lang/pl-PL.rc
> +    LTEXT "Programy:", 14006, 8, 53, 50, 10
Agreed, and applied.

2024-03-27 18:05 UTC, JoachimHenze commented on dll/win32/shell32/lang/pl-PL.rc
> +    LTEXT "Typ:", 14004, 8, 35, 50, 10
```suggestion
    LTEXT "Typ:", 14004, 8, 35, 42, 10
```
width 42 (the answer to all questions) will work here as well, as proven by the other dlg.

2024-03-27 20:08 UTC, merged

2024-03-28 08:36 UTC, Matriks404 commented
I don't get these changes. I understand somewhat why would you want to shrink the labels to make window smaller, but Windows doesn't do that as far as I am aware. And I especially don't understand why is "Otwierany za pomocą" changed to "Program:". That makes no sense. Wouldn't it be better to translate it to "Otwórz w:" (perfective) or "Otwieraj w:" (imperfective and probably better)?

2024-03-28 10:44 UTC, archeYR commented
> I don't get these changes. I understand somewhat why would you want to shrink the labels to make window smaller, but Windows doesn't do that as far as I am aware. And I especially don't understand why is "Otwierany za pomocą" changed to "Program:". That makes no sense. Wouldn't it be better to translate it to "Otwórz w:" (perfective) or "Otwieraj w:" (imperfective and probably better)?

Windows does adjust the window size depending on language, while ReactOS tends to keep the same window size for all. I suppose this is to reduce the burden when modifying the interface, as still many windows and dialogs are subject to change. While "Program:" seems obvious enough for me, "Otwieraj w" is a valid suggestion indeed. You may propose it via PR.