[REACTOS][CMAKE] Attempt to support C++98
reactos/reactos pull request #6723
Opened 2024-04-09 11:48 UTC by katahiromz

## Purpose

@JoachimHenze said he wants C++98 support of ReactOS.
JIRA issue: [CORE-19509](https://jira.reactos.org/browse/CORE-19509)

## Proposed changes

- Modify `CMakeLists.txt`

## TODO

- [ ] Do build.

2024-04-09 12:06 UTC, JoachimHenze approved these changes
Approved. I am interested to see where it will lead us. A good idea to comment with all the changes with the CORE-19509 tag like you did here.

2024-04-09 12:11 UTC, DarkFire01 requested changes
This was already discussed and voted on when it was dropped, No.

If backwards is the only way ROS want's to move then I don't want to be associated with this project anymore.

Ignoring the vote and merging this will make us lose several members of our already small core team.


EDIT: LOL glad to see majority doesn’t want this to happen either

2024-04-09 15:08 UTC, GeoB99 commented
***aheeeem***
![jakobglanc](https://github.com/reactos/reactos/assets/34916900/923b5627-37ab-49f4-a095-a7785c70c403)

2024-04-09 15:08 UTC, closed without merging

2024-04-10 11:12 UTC, K4sum1 commented
I don't know much about C++, but I was linked here by someone saying "lol" and I don't think the meaning is positive. towards what happened.

What is C++98, and why are so many people here against it?

2024-04-10 11:14 UTC, binarymaster commented
@K4sum1 we're not using GitHub for discussions like this, ask in the chat instead: https://chat.reactos.org