[NOTEPAD] Add FILE_SHARE_READ for CreateFileW
reactos/reactos pull request #6880
Opened 2024-05-13 09:01 UTC by katahiromz

## Purpose

JIRA issue: [CORE-19575](https://jira.reactos.org/browse/CORE-19575)

## Proposed changes

- Add `FILE_SHARE_READ` flag for `CreateFileW` call in writing a file.

## TODO

- [ ] Do tests.

2024-05-13 10:27 UTC, HBelusca requested changes
I don't really understand the fix.
Freeldr.ini is probably in read-only mode.
Have you checked how Windows XP/2003 notepad behaves in this case, when trying to open and save our freeldr.ini ?

2024-05-13 10:39 UTC, katahiromz commented
1. `FILE_SHARE_READ` is necessary because the file is open by the system that wants read access.
2. `CREATE_NEW` truncates the file content but `OPEN_ALWAYS` doesn't truncate the content, so `SetEndOfFile` is necessary.

2024-05-13 10:52 UTC, HBelusca commented
_**Important**_ second observation:

When resetting the file attributes of freeldr.ini to A S H (attribute system hidden), _**but NOT read-only**_, I confirm that ReactOS' notepad still shows the same error; however this time, Windows' notepad is able to save freeldr.ini without problems.

2024-05-13 10:53 UTC, HBelusca commented
@katahiromz I'll later today test your changes in all the possible combinatons and give approval if it's OK (so please be patient before going to merge this).

2024-05-13 14:41 UTC, HBelusca commented
> You shouldn't move nor copy the `freeldr.ini` file. There's file access in the system.

Not sure how I understand your command. Nothing else apart from notepad is accessing the "freeldr.ini" file at this point in time (and in my examples I'm testing our notepad and windows' one on windows 7)

2024-05-13 16:03 UTC, HBelusca requested changes
Amusingly, https://github.com/rust-lang/rust/issues/115745 also observed the same behaviour.

2024-05-13 19:57 UTC, whindsaks commented on base/applications/notepad/dialog.c
> +                        FILE_SHARE_READ | FILE_SHARE_WRITE,
But FILE_SHARE_DELETE is acceptable.

2024-05-14 00:02 UTC, katahiromz commented on base/applications/notepad/dialog.c
> +    hFile = CreateFileW(Globals.szFileName,
Comment added. OK.

2024-05-14 00:02 UTC, katahiromz commented on base/applications/notepad/dialog.c
> +    SetEndOfFile(hFile);
Comment added.

2024-05-14 00:03 UTC, katahiromz commented on base/applications/notepad/dialog.c
> +                        GENERIC_READ | GENERIC_WRITE,
`GENERIC_READ` is deleted. OK.

2024-05-14 00:11 UTC, katahiromz commented on base/applications/notepad/dialog.c
> +                        FILE_SHARE_READ | FILE_SHARE_WRITE,
OK.

2024-05-14 00:11 UTC, katahiromz commented on base/applications/notepad/dialog.c
> +                        NULL);
Reverted formatting. OK.

2024-05-14 14:57 UTC, HBelusca approved these changes
LGTM now.
Final commit log should mention the JIRA number.

2024-05-14 16:22 UTC, merged