Korean
reactos/reactos pull request #6907
Opened 2024-05-18 14:28 UTC by VenusGirl

Korean

2024-05-18 14:58 UTC, katahiromz commented
Welcome to ReactOS development.
Thank you for contribution.

At first, please read carefully the following articles:

https://github.com/reactos/reactos/blob/master/CONTRIBUTING.md

https://reactos.org/wiki/Translation_Introduction

https://reactos.org/wiki/RC_File_Standards

2024-05-18 15:23 UTC, katahiromz commented
Do you agree with it?

2024-05-18 15:33 UTC, VenusGirl reviewed
Modify Font

2024-05-18 15:35 UTC, katahiromz commented
Do you agree?

2024-05-18 15:37 UTC, VenusGirl commented
Yes

2024-05-18 15:42 UTC, katahiromz commented on base/applications/notepad/lang/ko-KR.rc
> +Please use a different editor."
There are some not translated English text.

2024-05-18 15:47 UTC, VenusGirl reviewed
Completed translation of untranslated strings

2024-05-18 15:49 UTC, katahiromz commented
Can you edit this file?
`base/applications/notepad/rsrc.rc`

2024-05-18 15:56 UTC, VenusGirl commented
Added Korean

#ifdef LANGUAGE_KO_KR
    #include "lang/ko-KR.rc"

2024-05-18 15:58 UTC, binarymaster commented
Cc @manatails for review.

Also wanted to ping Luke Luo, but he's deleted.

2024-05-18 16:51 UTC, VenusGirl commented
I would like to have the same VenusGirl as the contributor's name in Risoh Editor.

2024-05-18 17:21 UTC, binarymaster requested changes
Thanks for your interest in ReactOS!
We ask our contributors [to use their full name when committing](https://github.com/reactos/reactos/blob/master/CONTRIBUTING.md#rules-and-recommendations).
[Please amend your commit with your full name](https://stackoverflow.com/a/3042512), and update this PR.

To change this for future PR's, you can update it for globally (for the system):
```
git config --global user.name "Your Name"
git config --global user.email you@example.com
```

Or just for the current repository:
```
git config user.name "Your Name"
git config user.email you@example.com
```

Also please set up your GitHub account accordingly, so maintainers can use Squash & Merge button without getting the author field modified back to nickname by GitHub, it's done in two steps:

1. Set your full name in [GitHub profile settings](https://github.com/settings/profile) (it should match your `user.name` setting)
1. ~~Uncheck `Keep my email addresses private` in [GitHub email settings](https://github.com/settings/emails)~~ (addressed now)

Regards,

2024-05-18 17:21 UTC, binarymaster commented on base/applications/notepad/lang/ko-KR.rc
> +﻿LANGUAGE LANG_KOREAN, SUBLANG_KOREAN
```suggestion
/*
 * PROJECT:     ReactOS Notepad
 * LICENSE:     LGPL-2.1-or-later (https://spdx.org/licenses/LGPL-2.1-or-later)
 * PURPOSE:     Korean resource file
 * TRANSLATOR:  Copyright 2024 Your Name <your@email.com>
 */

﻿LANGUAGE LANG_KOREAN, SUBLANG_DEFAULT
```

2024-05-19 02:42 UTC, VenusGirl reviewed
Fix...

2024-05-19 03:31 UTC, manatails requested changes
I made a few modifications to make the translation more coherent.

2024-05-19 03:31 UTC, manatails commented on base/applications/notepad/lang/ko-KR.rc
> +    STRING_PRINTERROR "'%s' 파일을 인쇄할 수 없습니다.\n\n프린터가 켜져 있고 올바르게 구성되었는지 확인합니다."
구성되었는지 확인합니다. -> 구성되어 있는지 확인하세요.

2024-05-19 03:31 UTC, manatails commented on base/applications/notepad/lang/ko-KR.rc
> +    STRING_UTF8_BOM "UTF-8 (BOM 포함)"
Other languages don't translate the names of encoding types so it would be better to follow the convention

2024-05-19 03:31 UTC, manatails commented on base/applications/notepad/lang/ko-KR.rc
> +하나 이상의 응용 프로그램을 닫아 사용 가능한 메모리를 늘립니다."
늘립니다. -> 늘리세요.

2024-05-19 03:31 UTC, manatails commented on base/applications/notepad/lang/ko-KR.rc
> +    LTEXT "끝 줄:", 0x156, 65, 20, 41, 12
끝 줄: -> 개행 문자:

2024-05-19 03:31 UTC, manatails commented on base/applications/notepad/lang/ko-KR.rc
> +        MENUITEM "새창 만들기(&W)\tCtrl+Shift+N", CMD_NEW_WINDOW
새창 만들기 -> 새 창

2024-05-19 11:09 UTC, SigmaTel71 commented on base/applications/notepad/lang/ko-KR.rc
> + * TRANSLATOR:  Copyright 2024 VenusGirl <venusgirl@outlook.com>
This still has to be your real name.

2024-10-01 01:05 UTC, closed without merging