[MSPAINT] Set wallpaper automatically
reactos/reactos pull request #6948
Opened 2024-05-26 06:11 UTC by katahiromz

## Purpose

Enable us to set wallpaper from command line.
JIRA issue: [CORE-19618](https://jira.reactos.org/browse/CORE-19618)

## Proposed changes

- Add `g_bNoUI` and `g_bSetWallpaper` variable.
- If the 1st parameter of command line was an image file and the 2rd parameter was `"/Wallpaper"`, set the wallpaper.
- If `g_bNoUI` was TRUE, then hide the main window and quit silently.

## TODO

- [x] Do tests.

2024-05-26 15:42 UTC, HBelusca commented
Is this a feature that also exists on Windows' mspaint? Or a ROS-only one?

2024-05-26 22:04 UTC, katahiromz commented
> Is this a feature that also exists on Windows' mspaint? Or a ROS-only one?

ReactOS specific, ReactOS only.

2024-05-30 08:06 UTC, roybaer commented
If there is a practical use case for this feature, then why not?
As far as I can tell, its presence is not going to confuse anyone.

2024-05-30 08:16 UTC, katahiromz commented
> practical use case

A typical use case is registering a command line to the `RunOnce` registry key.

2024-05-30 09:21 UTC, whindsaks commented
> register a command line to the `RunOnce` registry key

Users are not going to type this in. Also, RunOnce is only executed by admins so this cannot be a typical use case.

However, this could be used to implement right-click "Set as wallpaper" on images?

2024-05-30 20:06 UTC, HBelusca commented
> However, this could be used to implement right-click "Set as wallpaper" on image files in SystemFileAssociations

This looks like a COM-based feature.

For example for `.png` files, we find a `HKEY_CLASSES_ROOT\SystemFileAssociations\.png\Shell\setdesktopwallpaper\Command` key.
The `setdesktopwallpaper` key contains the following values:
![image](https://github.com/reactos/reactos/assets/1969829/1d494562-05f1-44b5-b63d-18f7d787a5a5)
and the `Command` subkey contains the values:
![image](https://github.com/reactos/reactos/assets/1969829/58f0fe3d-0fe4-4c4b-95e9-21759a5d1a37)

The contents of this `HKEY_CLASSES_ROOT\CLSID\{ff609cc7-d34d-4049-a1aa-2293517ffcc6}` is as follows:
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\CLSID\{ff609cc7-d34d-4049-a1aa-2293517ffcc6}]
@="SetBackgroundContextMenu"

[HKEY_CLASSES_ROOT\CLSID\{ff609cc7-d34d-4049-a1aa-2293517ffcc6}\InProcServer32]
@=hex(2):25,00,53,00,79,00,73,00,74,00,65,00,6d,00,52,00,6f,00,6f,00,74,00,25,\
  00,5c,00,73,00,79,00,73,00,74,00,65,00,6d,00,33,00,32,00,5c,00,73,00,74,00,\
  6f,00,62,00,6a,00,65,00,63,00,74,00,2e,00,64,00,6c,00,6c,00,00,00
"ThreadingModel"="Apartment"
```

2024-05-30 20:25 UTC, whindsaks commented
> This looks like a COM-based feature

DelegateExecute does not exist on NT5, this was invented in Vista or 7.

XP uses `HKEY_CLASSES_ROOT\SystemFileAssociations\image\shellex\contextmenuhandlers\ShellImagePreview` where CLSID_PhotoVerbs (shimgvw.dll) implements IContextMenu. I guess shimgvw in ROS does not implement this.

2024-05-30 22:44 UTC, cbialorucki commented
>>This looks like a COM-based feature

>DelegateExecute does not exist on NT5, this was invented in Vista or 7.

We don't target NT5 anymore.

2024-05-30 22:48 UTC, cbialorucki requested changes
I don't think this feature should be implemented this way, we should properly implement the COM object that facilitates the "set as wallpaper" feature and extend explorer if needed.

2024-05-30 22:50 UTC, katahiromz commented
Wrong implementation. Closed.

2024-05-30 22:50 UTC, closed without merging

2024-05-30 22:57 UTC, whindsaks commented
> We don't target NT5 anymore.

That may be but I have not implemented support for DelegateExecute yet.

I see no reason that this needs to live as a COM object in shimgvw.dll (and shimgvw is dead on Windows 10+ IIRC). And if you insist on a COM object, we do support DropTarget which is basically the same as DelegateExecute, just without the fancy execute options that are not relevant in this context.