[*_VISTA] Add/Improve version resources
reactos/reactos pull request #7004
Opened 2024-06-08 16:23 UTC by SergeGautherie

## Purpose

Add 'Version' tab to Vista DLL properties.

## Proposed changes

- [CMAKE] Rename nt_0600 directory to nt_vista
- [*_VISTA] Add/Improve version resources

2024-06-09 12:34 UTC, learn-more requested changes
`[CMAKE] Rename nt_0600 directory to nt_vista` once again, completely unrelated to your 'add/improve version resources', and personal preference.

2024-06-13 00:40 UTC, SergeGautherie commented
> `[CMAKE] Rename nt_0600 directory to nt_vista`

Removed.

2024-06-13 06:52 UTC, learn-more approved these changes

2024-07-08 17:31 UTC, cbialorucki approved these changes

2024-08-09 22:08 UTC, SergeGautherie commented
Looking for a committer.

2024-08-13 10:39 UTC, merged