[RAPPS] Disable certificate pinning
reactos/reactos pull request #7071
Opened 2024-07-02 23:16 UTC by JoachimHenze

Fixes CORE-19666 '[RAPPS] Let's encrypt certificate (expired?), first seen 2024-06-30'
Yes, we could also groom the hardcodes within rapps to make the cert work again, but that wouldn't be a sustainable solution.

This stuff breaks recurrently every few years:
- When the cert is changed
- When the cert expires
- when the cert authority changes its name
- and when the cert issuer's CEO's dog pisses on the street

Crypto-BS at its finest.

Yes, disabling it may have a slight negative impact on the DB's transmission security.

JIRA issue: [CORE-19666](https://jira.reactos.org/browse/CORE-19666)

2024-07-02 23:38 UTC, JoachimHenze commented
Although rapps isn't covered by the bots at all, I did out of routine a comparison
0.4.14-release-116-g8754623 vs. 0.4.14-release-117-g a452db5d6a53e098372437ef549632d4ad1dab65 :
(/) VBox LGTM https://reactos.org/testman/compare.php?ids=96123,96236
(/)  KVM LGTM https://reactos.org/testman/compare.php?ids=96124,96237

2024-07-08 00:36 UTC, DarkFire01 commented
Isn’t it good to have a first warning about when the certs are expiring, these certs also do serve a purpose…

2024-07-08 13:45 UTC, learn-more requested changes
This makes no sense at all.

If you don't understand something that does not mean it is BS.

2024-07-08 13:50 UTC, binarymaster requested changes
It took me some time to consider this, and I came to the conclusion that I'm against such hacks.

2024-07-08 15:05 UTC, closed without merging