[COMDLG32] *.rc Tweak AUTORADIOBUTTONS
reactos/reactos pull request #7178
Opened 2024-07-24 20:54 UTC by JoachimHenze

- Tweak AUTORADIOBUTTONS (AUTORADIOBUTTON implies BS_AUTORADIOBUTTON). This saves a bit of memory and binary size.
- and use the backspace key for improving alignment to column 39 for the controls names in PRINT32_SETUP DIALOG & PRINT32 DIALOG
- and fix 3 accel collisions for upper chinese translation &OA &A &R
- and add a few FIXMEs for existing accel collisions in other languages

JIRA issue: none

Note1: I **intentionally** used only the backspace-key and not the space key to improve the alignment in PRINT32_SETUP DIALOG & PRINT32 DIALOG, so please refrain from any review-suggestions of the form "oh you could and another space here, or another space there". I will not do that in this PR.
Note2: I will only accept accelerator suggestions as replacement for the added FIXMEs that have been double-checked by a native translator from the native 2k3sp2, but **no guesses**.

2024-07-25 02:44 UTC, katahiromz approved these changes

2024-07-29 11:21 UTC, HBelusca requested changes
These translations are wine-synced with Wine, so I would refrain, if I were you, to modify anything here.
https://git.reactos.org/?p=reactos.git;a=blob;f=media/doc/WINESYNC.txt;h=2b34250f63c6924bada5b32c1b1d4b22a8fbba6c;hb=HEAD#l61

2024-07-29 13:55 UTC, JoachimHenze commented
Hermes this is an rc only change, and we do change these rc-files daily to our hearts desire.

2024-08-03 14:05 UTC, HBelusca commented
> Hermes this is an rc only change, and we do change these rc-files daily to our hearts desire. And if you look at my indentation changes to column 39, you will see that my changes bring us actually much closer to Wine than we were before, because that restores the original Wine-indentation of the Wine-guys, which was destroyed by **our** translators! So this brings the translations closer to en-US and Wine! see https://github.com/wine-mirror/wine/blob/master/dlls/comdlg32/comdlg32.rc
> 
> For the record: no ros developer ever marked any diff that he introduced before to comdlg32/en.rc (including yourself!): ![image](https://private-user-images.githubusercontent.com/33393466/353181014-d659a9be-776e-4fc9-9162-69e0e41dba10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2OTQwOTUsIm5iZiI6MTcyMjY5Mzc5NSwicGF0aCI6Ii8zMzM5MzQ2Ni8zNTMxODEwMTQtZDY1OWE5YmUtNzc2ZS00ZmM5LTkxNjItNjllMGU0MWRiYTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDE0MDMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMzcwMzAzOWYzZjE4ZWY3YmZiYWM0MDBjNGU2ZjBiOWNmYWNhY2IxYjM5MzIxYWYzMWZjYTQ5NmVjZDU1MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hMWUsauIHxQ_qA25VMgkJndgud6dbfLNfdVjAWRBaC8) and that was ok imho, because rc-changes are a trivial thing compared to real code-changes where marking the diff can be beneficial.

Note that my change in this file was because it was forgotten on our side, and the other changes from Doug and co are usability bugfixes.

2024-08-07 22:28 UTC, merged