[CONSOLE] Update Romanian (ro-RO) translation
reactos/reactos pull request #7404
Opened 2024-09-28 21:38 UTC by AndreiMiloiu

Improvements based on recent Romanian translation document revision https://github.com/reactos/reactos/commit/06e89b2e81cd7de029fac2c595a6371eba13d797.

This files was not translated in Romanian language in any Win version (neither XP/2k3+, nor in the previous ones). I tried to translate this file as close as possible in the way I did in the previous PRs with this attendum.

2024-09-28 21:38 UTC, AndreiMiloiu commented
Cc @reactos/lang-romanian for review

2024-09-28 21:41 UTC, JoachimHenze commented on dll/cpl/console/lang/ro-RO.rc
> +    AUTORADIOBUTTON "&Mare", IDC_RADIO_LARGE_CURSOR, 15, 60, 90, 10, WS_CHILD | WS_VISIBLE | WS_TABSTOP
**mandatory** change requested: accel collision &Mare vs. &Mica

2024-09-28 21:42 UTC, JoachimHenze requested changes
see the collisions

2024-09-28 22:08 UTC, AndreiMiloiu commented on dll/cpl/console/lang/ro-RO.rc
> +    AUTORADIOBUTTON "&Mare", IDC_RADIO_LARGE_CURSOR, 15, 60, 90, 10, WS_CHILD | WS_VISIBLE | WS_TABSTOP
Fixed!

2024-09-28 22:08 UTC, AndreiMiloiu commented
> see the collisions

Fixed now!

2024-11-07 18:34 UTC, AndreiMiloiu commented
@GeoB99 is it good now?

2024-11-20 21:01 UTC, HBelusca approved these changes
Looks ok from a pure technical point of view.
@AndreiMiloiu Have you checked your modifications correctly fit into the controls?
Cc @GeoB99 for review.

2024-11-20 21:26 UTC, AndreiMiloiu commented
> Looks ok from a pure technical point of view. @AndreiMiloiu Have you checked your modifications correctly fit into the controls? Cc @GeoB99 for review.

Yes

2024-12-01 15:20 UTC, AndreiMiloiu commented
Any news?

2024-12-06 20:12 UTC, merged