[NTOS:PS] Basic support for jobs in the kernel: Create/Open/Assign/Terminate/Delete
reactos/reactos pull request #7500
Opened 2024-11-11 11:41 UTC by wnstngs

## Abstract

Jobs are kernel objects that allow processes to be grouped and manipulated as a single entity (for example, in order to apply constraints to them and the threads they contain). If a process is in a job, then all processes’ threads that those processes create will also be in the job, with no escape.

## Background

This PR supersedes the old WIP PR #40 by  Mark Jansen and is partially based on it (which in turn was based on the patch by Samuel Serapión Vega). Moreover, the implementation of `JobObjectBasicLimitInformation` and `JobObjectExtendedLimitInformation` limits in `NtSetInformationJobObject()` is based on  Timo Kreuzer's patch.

This PR adds basic support for pre-Windows 8 job objects to the kernel. It adapts the previous patch part-by-part, gradually adding to its unfinished parts as well fixing some things (like handling job status flags or fixing input validation) because the patch did not produce satisfactory results when running WINE tests, and adds more functionality on top of it. 

This is not the final version of what functional job support should look like; some features are intentionally left untouched in this PR.

## Current status

- Creating a job object (`NtCreateJobObject`)
- Opening a job object (`NtOpenJobObject`)
- Adding a process to a job (`NtAssignProcessToJobObject`, `PspAssignProcessToJob`)
- Removing a process from a job (`PspRemoveProcessFromJob`)
- Exiting a process from a job (`PspExitProcessFromJob`)
- Checking if a process is in the job (`NtIsProcessInJob`)
- Terminating processes in a job (`NtTerminateJobObject`, `PspTerminateJobObject`)
- Enumeration of processes in a job (`PspEnumerateProcessesInJob`)
- Closing a job object (`PspCloseJob`)
- Deleting a job object (`PspDeleteJob`)
- Querying job object information (`NtQueryInformationJobObject`)
  - `JobObjectBasicAccountingInformation`, `JobObjectBasicAndIoAccountingInformation`, `JobObjectBasicLimitInformation`, JobObjectExtendedLimitInformation, JobObjectBasicProcessIdList
- Setting job object information (`NtSetInformationJobObject`)
  - `JobObjectBasicLimitInformation`, `JobObjectExtendedLimitInformation`

Job-related tests from the WINE kernel32 test suite:

<details>
  <summary>Before (60 failures):</summary>

  ![kernel32 process - after](https://imgur.com/A6ulmtm.jpg)
</details>

<details>
  <summary>After (16 failures):</summary>

  ![kernel32 process - after](https://imgur.com/ELQhtfy.jpg)
</details>

## TODO

Plans for future PRs:
- Add support for job limits.
- Add support for job sets.
- Figure out and support more job/job status flags.
- Support more job information classes in `NtQueryInformationJobObject`/`NtSetInformationJobObject`.
- 100% pass rate of job related tests in the WINE kernel32 test suite.

2025-01-27 14:15 UTC, DarkFire01 commented
PR part of the bundle that allowed firefox 75 to work!
![image](https://github.com/user-attachments/assets/71989e07-634f-4dd8-aa66-2316ffe4533d)

2025-03-27 14:09 UTC, learn-more requested changes
I think the reference counting could do with another pass over it,
other than that a lot of the stuff looks good.

2025-04-14 12:33 UTC, wnstngs commented on ntoskrnl/ps/job.c
> +        return;
Done.

2025-04-14 12:34 UTC, wnstngs commented on ntoskrnl/ps/job.c
> +    Job->CompletionPort = NULL;
Thanks, fixed.

2025-04-14 12:34 UTC, wnstngs commented on ntoskrnl/ps/job.c
> +        DPRINT1("Invalid LimitFlags specified\n");
Done.

2025-04-14 12:39 UTC, wnstngs commented on ntoskrnl/ps/job.c
> +    ExAcquireResourceSharedLite(&Job->JobLock, TRUE);
You're right, switched to exclusive and APCs are already disabled before this point.

2025-04-14 12:40 UTC, wnstngs commented on ntoskrnl/ps/job.c
> +                ExtendedLimit->BasicLimitInformation.MaximumWorkingSetSize))
Thanks, fixed.

2025-04-14 12:40 UTC, wnstngs commented on ntoskrnl/ps/job.c
> +    Status = PspEnumerateProcessesInJob(Job,
Done.

2025-04-14 12:40 UTC, wnstngs commented on ntoskrnl/ps/job.c
> +    if (ProcessHandle == PsGetCurrentProcess())
Thanks, fixed.

2025-04-14 12:42 UTC, wnstngs commented on ntoskrnl/ps/job.c
> +                break;
Thanks, added dereference.

2025-04-14 12:43 UTC, wnstngs commented on ntoskrnl/ps/job.c
> +
That's right, thanks - added it.

2025-08-14 12:45 UTC, wnsntgs commented on ntoskrnl/ps/job.c
> +                KeSetEvent(&Job->Event, IO_NO_INCREMENT, FALSE);
A process can be a member of a job but in a transient state, and there is a distinction between "a process is in the job list" and "a process is actively counted against the job." It is intended that the event is set to a signaled state only in the termination path so waiters can be released even when you don't go through the usual remove/exit flow.

Added `IoSetIoCompletion` in `PspTerminateProcessCallback`, thanks!

2025-08-14 12:48 UTC, wnstngs commented on ntoskrnl/ps/job.c
> +            ObDereferenceObjectEx(Job, 2);
It looks correct now.

2025-12-02 15:27 UTC, tkreuzer reviewed
Can we get this completed?

2025-12-02 15:27 UTC, tkreuzer commented on ntoskrnl/ps/job.c
> +        if (Job->ActiveProcesses > Job->ActiveProcessLimit)
```suggestion
        if (Job->ActiveProcesses => Job->ActiveProcessLimit)
```

2025-12-02 15:27 UTC, tkreuzer commented on ntoskrnl/ps/job.c
> +        return STATUS_INVALID_PARAMETER;
Leaking the lock here and below.

```suggestion
        Status = STATUS_INVALID_PARAMETER;
        goto Exit;
```

2025-12-02 15:27 UTC, tkreuzer commented on ntoskrnl/ps/job.c
> +    if (Process->Job == Job)
There is only 1 caller for this function and is passes `Process->Job`, and I don't see any reason why anything else could be passed. So this should probably ASSERT. Or not even pass the Job as a parameter.

2025-12-02 15:27 UTC, tkreuzer commented on ntoskrnl/ps/job.c
> +    ExAcquireResourceExclusiveLite(&Job->JobLock, TRUE);
Add an ASSERT that this is run within a guarded region.

2025-12-02 15:27 UTC, tkreuzer commented on ntoskrnl/ps/job.c
> +                             RequiredAlign);
Please no. We don't live in the 80ies anymore, we can handle 81 columns.

2025-12-02 18:05 UTC, HBelusca commented on ntoskrnl/ps/job.c
> +        if (Job->ActiveProcesses > Job->ActiveProcessLimit)
Should read `>=`

2025-12-04 12:33 UTC, wnsntgs commented on ntoskrnl/ps/job.c
> +        if (Job->ActiveProcesses > Job->ActiveProcessLimit)
You are looking at some older version. In the latest version (4 months ago), this has already been fixed.

2025-12-04 12:34 UTC, wnsntgs commented on ntoskrnl/ps/job.c
> +        return STATUS_INVALID_PARAMETER;
Ditto, already fixed.

2026-07-28 11:57 UTC, wnsntgs commented on ntoskrnl/ps/job.c
> +    if (Process->Job == Job)
Agreed, now PspRemoveProcessFromJob and PspExitProcessFromJob only accept a process as a parameter.

2026-08-05 09:00 UTC, learn-more approved these changes

2026-08-05 09:00 UTC, learn-more commented on ntoskrnl/ps/job.c
> +                  sizeof(JOBOBJECT_BASIC_ACCOUNTING_INFORMATION));
nit: could do `sizeof(BasicAndIo->BasicInfo)`

2026-08-05 09:00 UTC, learn-more commented on ntoskrnl/ps/job.c
> +    if (!(Process->JobStatus & JOB_NOT_REALLY_ACTIVE) &&
Might as well use the `BooleanFlagOn` family of functions?

2026-08-05 09:00 UTC, learn-more commented on ntoskrnl/ps/job.c
> +        }
else, should it be cleaned up?

2026-08-05 11:54 UTC, wnsntgs commented on ntoskrnl/ps/job.c
> +        }
ObInsertObject consumes the ref returned by ObCreateObject and dereferences the object on failure, so PspDeleteJob performs the cleanup

2026-08-05 11:55 UTC, wnsntgs commented on ntoskrnl/ps/job.c
> +    if (!(Process->JobStatus & JOB_NOT_REALLY_ACTIVE) &&
I didn't know that, switched to using BooleanFlagOn where it made sense

2026-08-05 11:55 UTC, wnsntgs commented on ntoskrnl/ps/job.c
> +                  sizeof(JOBOBJECT_BASIC_ACCOUNTING_INFORMATION));
Done here and in a few other places

2026-08-05 12:19 UTC, tkreuzer commented on ntoskrnl/ps/job.c
> +#if DBG
The `#if DBG` is not needed here and in other cases below.

2026-08-05 12:19 UTC, tkreuzer commented on ntoskrnl/ps/job.c
> +    PLIST_ENTRY NextEntry;
I would recommend to use a `PEPROCESS` here, which is more convenient for debugging.

2026-08-05 12:19 UTC, tkreuzer commented on ntoskrnl/ps/job.c
> +PspAdvanceJobEnumerator(
Is the discrepency in the naming (`JobEnumerator` vs `JobIterator`) intended?

2026-08-05 12:19 UTC, tkreuzer commented on ntoskrnl/ps/job.c
> +    while ((Candidate = PspAdvanceJobIteratorLocked(&Iterator)) != NULL)
All of the code above this function could be replaced with something like
```
    ListLink = Process ? Process ->JobLinks.Flink : Job->ProcessListHead.Flink;
    for ( ; ListLink != &Job->ProcessListHead; ListLink = ListLink->Flink)
    {
        Candidate = CONTAINING_RECORD(ListLink, EPROCESS, JobLinks);
        ...
```
In other words: it seems a bit overengineered to abstract a simple linked list iteration with an iterator structure and 2 functions.
Alternatively something as simple as
```
static PEPROCESS PspGetNextProcessInJob(PEJOB Job, PEPROCESS Process)
{
    PLIST_ENTRY ListLink = Process ? Process ->JobLinks.Flink : Job->ProcessListHead.Flink;
    if (ListLink == &Job->ProcessListHead)
        return NULL;
    return CONTAINING_RECORD(ListLink, EPROCESS, JobLinks);
}
```
would also do it, make the loop a bit more elegant and avoid all the clutter.

2026-08-05 12:19 UTC, tkreuzer commented on ntoskrnl/ps/job.c
> +    while (Process)
Alternatively
```
    Process = NULL;
    while ((Process = PspAdvanceJobEnumerator(Job, Process)) != NULL)
```
Like it's done above and below.

2026-08-05 12:19 UTC, tkreuzer commented on ntoskrnl/ps/job.c
> +    ObReferenceObject(Job);
You could do that below after successfully assigning it.

2026-08-05 12:19 UTC, tkreuzer commented on ntoskrnl/ps/job.c
> +    if (!(Process->JobStatus & JOB_NOT_REALLY_ACTIVE) &&
Just FYI: `FlagOn` would be enough here. `BooleanFlagOn` is only to guarantee that the result is either `TRUE` or `FALSE`, e.g. when you want to assign it to a `BOOLEAN`.

2026-08-05 12:19 UTC, tkreuzer commented on ntoskrnl/ps/job.c
> +PspQueryLimitInformation(
I know this is a function that is local to the `job.c` file, but I'd still prefer a more specific name like `PspQueryJobLimitInformation`. Same for `PspQueryBasicAccountingInfo`.

2026-08-05 16:31 UTC, wnsntgs commented on ntoskrnl/ps/job.c
> +PspQueryLimitInformation(
Done

2026-08-05 16:32 UTC, wnsntgs commented on ntoskrnl/ps/job.c
> +    while ((Candidate = PspAdvanceJobIteratorLocked(&Iterator)) != NULL)
Simplified the enumeration implementation

2026-08-05 16:32 UTC, wnsntgs commented on ntoskrnl/ps/job.c
> +#if DBG
Removed

2026-08-05 16:32 UTC, wnsntgs commented on ntoskrnl/ps/job.c
> +    PLIST_ENTRY NextEntry;
Removed PSP_JOB_ITERATOR

2026-08-05 16:35 UTC, wnsntgs commented on ntoskrnl/ps/job.c
> +PspAdvanceJobEnumerator(
This is no longer relevant, simplified the implementation. The point of making it overengineered was to prepare for Windows 8+ jobs, where they can be nested, making it more difficult to enumerate them. I was trying to separate: a locked iterator returning borrowed processes and an unlocked enumerator returning referenced processes, with the idea that the iterator state could later grow into something suitable for nesting.

2026-08-05 16:36 UTC, wnsntgs commented on ntoskrnl/ps/job.c
> +    ObReferenceObject(Job);
This ordering is intentional (at least now). The ref is acquired before publishing Process->Job, so any observer of a non NULL pointer sees an object already backed by the ref owned by that field. If the CAS fails, the ref is released. Clarified in the comment.

2026-08-06 11:42 UTC, tkreuzer approved these changes
Some nits, otherwise lgtm.

2026-08-06 11:42 UTC, tkreuzer commented on ntoskrnl/ps/job.c
Can be removed

2026-08-06 11:42 UTC, tkreuzer commented on ntoskrnl/ps/job.c
Can be removed

2026-08-06 11:42 UTC, tkreuzer commented on ntoskrnl/ps/job.c
`_SEH2_YIELD` is no longer required, a simple return is enough.

2026-08-06 11:42 UTC, tkreuzer commented on ntoskrnl/ps/job.c
I'd prefer an early return with a `DPRINT1` here.

2026-08-10 21:48 UTC, MishaProductions commented
`D:\a\reactos\reactos\src\ntoskrnl\ps\psmgr.c(437): error C4113: 'void (__cdecl *)(PEPROCESS,PVOID,ACCESS_MASK,ULONG,ULONG)' differs in parameter lists from 'OB_CLOSE_METHOD'`

2026-08-12 19:42 UTC, wnsntgs commented
> `D:\a\reactos\reactos\src\ntoskrnl\ps\psmgr.c(437): error C4113: 'void (__cdecl *)(PEPROCESS,PVOID,ACCESS_MASK,ULONG,ULONG)' differs in parameter lists from 'OB_CLOSE_METHOD'`

Thanks, fixed

2026-08-12 20:06 UTC, DarkFire01 approved these changes

2026-08-12 20:11 UTC, MishaProductions approved these changes

2026-08-12 20:58 UTC, HBelusca reviewed
stuff

2026-08-12 20:58 UTC, HBelusca commented on dll/win32/kernel32/client/job.c
> +    lpJobObjectInformation,
```suggestion
    _Out_writes_bytes_to_(cbJobObjectInformationLength, *lpReturnLength)
        LPVOID lpJobObjectInformation,
```

2026-08-12 20:58 UTC, HBelusca commented on dll/win32/kernel32/client/job.c
> +                 _In_ LPCSTR lpName)
```suggestion
CreateJobObjectA(
    _In_ LPSECURITY_ATTRIBUTES lpJobAttributes,
    _In_ LPCSTR lpName)
```

2026-08-12 20:58 UTC, HBelusca commented on dll/win32/kernel32/client/job.c
> +                 _In_ LPCWSTR lpName)
```suggestion
CreateJobObjectW(
    _In_ LPSECURITY_ATTRIBUTES lpJobAttributes,
    _In_ LPCWSTR lpName)
```

2026-08-12 20:58 UTC, HBelusca commented on dll/win32/kernel32/client/job.c
> +               _In_ LPCWSTR lpName)
```suggestion
OpenJobObjectW(
    _In_ DWORD dwDesiredAccess,
    _In_ BOOL bInheritHandle,
    _In_ LPCWSTR lpName)
```

2026-08-12 20:58 UTC, HBelusca commented on dll/win32/kernel32/client/job.c
> +               _In_ LPCSTR lpName)
```suggestion
OpenJobObjectA(
    _In_ DWORD dwDesiredAccess,
    _In_ BOOL bInheritHandle,
    _In_ LPCSTR lpName)
```

2026-08-12 20:58 UTC, HBelusca commented on dll/win32/kernel32/client/job.c
> +               _Out_ PBOOL Result)
```suggestion
IsProcessInJob(
    _In_ HANDLE ProcessHandle,
    _In_opt_ HANDLE JobHandle,
    _Out_ PBOOL Result)
```

2026-08-12 20:58 UTC, HBelusca commented on dll/win32/kernel32/client/job.c
> +                         _In_ HANDLE hProcess)
```suggestion
AssignProcessToJobObject(
    _In_ HANDLE hJob,
    _In_ HANDLE hProcess)
```

2026-08-12 20:58 UTC, HBelusca commented on dll/win32/kernel32/client/job.c
> +                   _In_ UINT uExitCode)
```suggestion
TerminateJobObject(
    _In_ HANDLE hJob,
    _In_ UINT uExitCode)
```

2026-08-12 20:58 UTC, HBelusca commented on dll/win32/kernel32/client/proc.c
> +       away from the job associated with the calling process */
```suggestion
    /* CREATE_BREAKAWAY_FROM_JOB allows the child process to break
     * away from the job associated with the calling process */
```

2026-08-12 20:58 UTC, HBelusca commented on ntoskrnl/include/internal/ps.h
> +// version 6.0
```suggestion
// These are based on the layout of bit fields in the Flags2 set
// introduced in version 6.0
```

2026-08-12 20:58 UTC, HBelusca commented on ntoskrnl/ps/kill.c
> +               and do I/O completion if needed */
```suggestion
            /* Check if we are part of a job that has a completion port
             * and do I/O completion if needed */
```

2026-08-12 20:58 UTC, HBelusca commented on ntoskrnl/ps/process.c
> +     *  c) parent's job does NOT allow silent breakaway
```suggestion
     *  c) parent's job does NOT allow silent breakaway.
```

2026-08-12 20:58 UTC, HBelusca commented on ntoskrnl/ps/process.c
> +    PEJOB ParentJob;
```suggestion
```

2026-08-12 20:58 UTC, HBelusca commented on ntoskrnl/ps/process.c
> +        ParentJob = Parent->Job;
```suggestion
        PEJOB ParentJob = Parent->Job;
```

2026-08-12 20:58 UTC, HBelusca commented on sdk/include/ndk/pstypes.h
> +
```suggestion
```

2026-08-12 20:58 UTC, HBelusca commented on sdk/include/ndk/pstypes.h
> +// Job message flags
Note that since these are consecutive numbers, they look more like an enumeration to me (and so, a given value excludes the others, and cannot combines with them).

2026-08-12 20:58 UTC, HBelusca commented on sdk/include/ndk/pstypes.h
> +#define JOB_OBJECT_MSG_NEW_PROCESS              6
There isn't a define for value 5 ?

2026-08-12 20:58 UTC, HBelusca commented on ntoskrnl/ps/kill.c
> +                (VOID)PspSendJobMessageLocked(Process->Job,
Maybe retrieve the status and do a DPRINT1 or whatever if the Status isn't a success code?

2026-08-12 20:58 UTC, HBelusca commented on ntoskrnl/include/internal/ps.h
> +(*PJOB_ENUMERATOR_CALLBACK)(
I would recommend making the callback NTAPI; what do you think about that?

2026-08-12 20:58 UTC, HBelusca commented on ntoskrnl/ps/job.c
> + *                  for managing multiple processes as a single unit
```suggestion
 *                  for managing multiple processes as a single unit.
```

2026-08-12 20:58 UTC, HBelusca commented on ntoskrnl/ps/job.c
> +
```suggestion
    ASSERT(Process->Job == Job);
```

2026-08-12 20:58 UTC, HBelusca commented on ntoskrnl/ps/job.c
> +    while (Process != NULL)
Note that this could be condensed in a more elegant for-loop:
```suggestion
    /* Iterate through all processes in the job */
    for (Process = PspGetNextProcessInJob(Job, NULL);
         Process != NULL;
         Process = PspGetNextProcessInJob(Job, Process))
```

2026-08-12 20:58 UTC, HBelusca commented on ntoskrnl/ps/job.c
> +        Process = PspGetNextProcessInJob(Job, Process);
This goes together with the for-loop suggestion:
```suggestion
```

2026-08-12 20:58 UTC, HBelusca commented on ntoskrnl/ps/job.c
> +             * reference. On failure, it must be released explicitly.
```suggestion
             * On successful iteration, PspGetNextProcessInJob consumes
             * this reference. On failure, it must be released explicitly.
```

2026-08-12 20:58 UTC, HBelusca commented on ntoskrnl/ps/job.c
> +
```suggestion
```

2026-08-12 20:58 UTC, HBelusca commented on ntoskrnl/ps/job.c
> +        }
```suggestion
        if (!NT_SUCCESS(Status))
            break;
```

2026-08-12 20:58 UTC, HBelusca commented on ntoskrnl/ps/job.c
> +    Status = IoSetIoCompletion(Job->CompletionPort,
Suggestion:
`    return IoSetIoCompletion(...);`
without the intermediate `Status` variable.

2026-08-12 20:58 UTC, HBelusca commented on ntoskrnl/ps/job.c
> +    ExReleaseRundownProtection(&Process->RundownProtect);
```suggestion
    ExReleaseResourceAndLeaveCriticalRegion(&Job->JobLock);
    ExReleaseRundownProtection(&Process->RundownProtect);
```

2026-08-12 21:07 UTC, HBelusca commented on ntoskrnl/ps/job.c
>   */
Replacement for the whole header:
```suggestion
/*
 * PROJECT:     ReactOS Kernel
 * LICENSE:     GPL-2.0-or-later (https://spdx.org/licenses/GPL-2.0-or-later)
 * PURPOSE:     Core functions for managing Job Objects, a kernel mechanism
 *              for managing multiple processes as a single unit.
 * COPYRIGHT:   Copyright 2004-2012 Alex Ionescu (alex@relsoft.net) (stubs)
 *              Copyright 2004-2005 Thomas Weidenmueller <w3seek@reactos.com>
 *              Copyright 2015-2016 Samuel Serapión Vega <encoded@reactos.org>
 *              Copyright 2017 Mark Jansen <mark.jansen@reactos.org>
 *              Copyright 2018 Pierre Schweitzer <pierre@reactos.org>
 *              Copyright 2022 Timo Kreuzer <timo.kreuzer@reactos.org>
 *              Copyright 2024-2026 Gleb Surikov <glebs.surikovs@gmail.com>
 */
```

2026-08-13 20:18 UTC, wnsntgs commented on ntoskrnl/ps/kill.c
> +                (VOID)PspSendJobMessageLocked(Process->Job,
SendJobMessageLocked can fail under memory pressure, but ordinary job messages are best-effort notifications and their delivery is not guaranteed. Eg, see https://learn.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-jobobject_associate_completion_port ("except for limits set with the JobObjectNotificationLimitInformation information class, messages are intended only as notifications and their delivery to the completion port is not guaranteed"). Other job notifications ignore the status as well, so I'd prefer to keep the exit path consistent.

2026-08-13 20:19 UTC, wnsntgs commented on sdk/include/ndk/pstypes.h
> +#define JOB_OBJECT_MSG_NEW_PROCESS              6
No

2026-08-14 12:42 UTC, wnsntgs commented on ntoskrnl/ps/job.c
>   */
Done

2026-08-14 12:42 UTC, wnsntgs commented on ntoskrnl/ps/job.c
> +    Status = IoSetIoCompletion(Job->CompletionPort,
Done

2026-08-14 12:43 UTC, wnsntgs commented on ntoskrnl/include/internal/ps.h
> +(*PJOB_ENUMERATOR_CALLBACK)(
Done

2026-08-14 12:43 UTC, wnsntgs commented on ntoskrnl/ps/job.c
> +    while (Process != NULL)
Done

2026-08-14 12:44 UTC, wnsntgs commented on sdk/include/ndk/pstypes.h
> +// Job message flags
I think the word "flags" is wrong here, changed to "Job Messages"

2026-08-14 21:45 UTC, Doug-Lyons approved these changes

2026-08-14 22:53 UTC, HBelusca commented on ntoskrnl/include/internal/ps.h
> +#define ACCOUNTING_FOLDED       0x00000002
Wouldn't it be best to prefix these with a "JOB_" or "PS_JOB_" or something? Just a name like that could pretty much collide with a completely unrelated macro someone could define somewhere.

2026-08-14 22:53 UTC, HBelusca commented on ntoskrnl/ps/job.c
> +        ASSERT(((RequiredAlign) == 1) ||
Since you've modified the formatting, you may also remove the redundant parentheses around "RequiredAlign".

2026-08-14 22:53 UTC, HBelusca commented on ntoskrnl/ps/job.c
> +                                       (PVOID *)&Job,
Not necessary

2026-08-14 22:53 UTC, HBelusca commented on ntoskrnl/ps/job.c
>      KeEnterGuardedRegionThread(CurrentThread);
Naive question: what's the reason for the guarded region? Does it play a role similar to "locking the thread" in order to modify the job info?

2026-08-14 22:53 UTC, HBelusca commented on ntoskrnl/ps/job.c
> +            if (JobInformationClass == JobObjectExtendedLimitInformation)
```suggestion
            if (IsExtendedLimit)
```

2026-08-14 22:53 UTC, HBelusca commented on ntoskrnl/ps/job.c
> +               ((RequiredAlign) == 16));
See other comment

2026-08-14 22:53 UTC, HBelusca commented on ntoskrnl/ps/job.c
> +    if (!(NT_SUCCESS(Status)))
```suggestion
    if (!NT_SUCCESS(Status))
```
and in other similar places.

2026-08-14 22:53 UTC, HBelusca commented on ntoskrnl/ps/job.c
> +    if (!(NT_SUCCESS(Status)))
for example there...

2026-08-14 22:53 UTC, HBelusca commented on ntoskrnl/ps/job.c
> +       "Windows 10 System Programming, Part 1", p.264, (2020) */
There's no existing defines for these scheduling classes (and for this "5' in particular)?

2026-08-14 22:53 UTC, HBelusca commented on ntoskrnl/ps/job.c
> +    ASSERT(NT_SUCCESS(Status));
Why not just returning the actual status code below? (I don't fully understand the reason exposed in the associated comment)

2026-08-14 22:53 UTC, HBelusca commented on ntoskrnl/ps/job.c
> +    const ULONG AllowedExtendedFlags = AllowedBasicFlags |
Or make defines?

2026-08-14 22:53 UTC, HBelusca commented on ntoskrnl/ps/job.c
> + *
```suggestion
```

2026-08-15 13:10 UTC, wnsntgs commented on ntoskrnl/ps/job.c
> +    const ULONG AllowedExtendedFlags = AllowedBasicFlags |
Done

2026-08-15 13:11 UTC, wnsntgs commented on ntoskrnl/ps/job.c
> +       "Windows 10 System Programming, Part 1", p.264, (2020) */
No, but added a define for the default class

2026-08-15 13:12 UTC, wnsntgs commented on ntoskrnl/ps/job.c
> +        ASSERT(((RequiredAlign) == 1) ||
Done

2026-08-15 13:12 UTC, wnsntgs commented on ntoskrnl/include/internal/ps.h
> +#define ACCOUNTING_FOLDED       0x00000002
Done

2026-08-15 13:13 UTC, wnsntgs commented on ntoskrnl/ps/job.c
> +    ASSERT(NT_SUCCESS(Status));
Returning status would be equivalent with the current callback, since it always returns success. I think keeping the explicit success is preferable though, as by the time we enumerate, the IOCP association has already been committed, while the initial notifications are best-effort. Propagating a later notification/enumeration failure would report failure to the caller even though the job remains associated with the port. I clarified the comment a bit.

2026-08-15 13:14 UTC, wnsntgs commented on ntoskrnl/ps/job.c
>      KeEnterGuardedRegionThread(CurrentThread);
It disables kernel APC delivery for the duration of the set operation. This is established once at the NtSetInformationJobObject level so helpers that require APCs to be disabled can use the corresponding unsafe operations without entering/leaving another guarded region themselves. I clarified the comment.

2026-08-22 22:42 UTC, merged

2026-08-22 22:59 UTC, HBelusca commented on ntoskrnl/ps/job.c
>      KeEnterGuardedRegionThread(CurrentThread);
Thanks

2026-08-22 23:04 UTC, HBelusca approved these changes